### ISSUE TITLE
Failed to rename error

### ISSUE THREAD

**Issue by davidrdguezarias** [zigbee2mqtt/hassio-zigbee2mqtt#101]
**Description of problem:**
Tried to rename a device and in the debugger I received the error Failed to rename. The devices worked always correctly, I have only 2 devices, so I am sure that the ID is unique as well
Old name: light.salon_tvled
New name: light.luz_TV_00_01_00_salon_interior_AC

**Zigbee2mqtt add-on version (if edge, please report commit hash):**
```
1.18.3-1
```

**Your entire configuration from the frontend (with sensitive fields redacted)**:
```
data_path: /config/zigbee2mqtt
external_converters: []
devices: devices.yaml
groups: groups.yaml
homeassistant: true
permit_join: false
mqtt:
  base_topic: zigbee2mqtt
  server: '!secret mqtt_server'
  user: '!secret mqtt_user'
  password: '!secret mqtt_password'
serial:
  port: /dev/ttyACM0
advanced:
  log_level: warn
  pan_id: 6754
  channel: 11
  network_key:
    - xx
    - xx
    - xx
    - xx
    - xx
    - xx
    - xx
    - xx
    - xx
    - xx
    - xx
    - xx
    - xx
    - xx
    - xx
    - xx
  availability_blocklist: []
  availability_passlist: []
device_options: {}
blocklist: []
passlist: []
queue: {}
frontend:
  port: 8099
experimental: {}
socat:
  enabled: false
  master: 'pty,raw,echo=0,link=/tmp/ttyZ2M,mode=777'
  slave: 'tcp-listen:8485,keepalive,nodelay,reuseaddr,keepidle=1,keepintvl=1,keepcnt=5'
  options: '-d -d'
  log: false
```

**Running platform (details from Suypervisor > System)**
```
core-2021.4.6
Home Assistant OS
5.4.83-v7
```

**Your logs from Home Assistant Supervisor**
```
// Your logs here
[cont-init.d] zigbee2mqtt.sh: exited 0.
[cont-init.d] done.
[services.d] starting services
[services.d] done.
[16:56:26] INFO: Handing over control to Zigbee2mqtt Core ...
> zigbee2mqtt@1.18.3 start /app
> node index.js
Zigbee2MQTT:error 2021-05-02 01:05:20: Failed to rename - light.salon_tvled to light.luz_TV_00_01_00_salon_interior_AC
Zigbee2MQTT:error 2021-05-02 01:08:17: Failed to rename - light.salon_tvled to light.luz_TV_00_01_00_salon_interior_AC
```
