### ISSUE TITLE
Unknown option: retain

### ISSUE THREAD

**Issue by SPEC1AL1ST** [zigbee2mqtt/hassio-zigbee2mqtt#108]
**Description of problem:**
In supervisor logs i see that:
```
21-05-11 10:24:12 WARNING (MainThread) [supervisor.addons.options] Unknown option 'retain' for Zigbee2mqtt (45df7312_zigbee2mqtt)
21-05-11 10:24:12 WARNING (SyncWorker_0) [supervisor.addons.options] Unknown option 'retain' for Zigbee2mqtt (45df7312_zigbee2mqtt)
```

But in [configuration guide](https://www.zigbee2mqtt.io/information/configuration.html) it is written
`retain: Retain MQTT messages of this device (default false).`

**Your entire configuration from the frontend (with sensitive fields redacted)**:
```
data_path: /config/zigbee2mqtt
external_converters: []
devices: devices.yaml
groups: groups.yaml
homeassistant: true
permit_join: false
mqtt:
  base_topic: zigbee2mqtt
  server: 'mqtt://core-mosquitto'
  user: user
  password: pass
serial:
  port: /dev/ttyUSB0
advanced:
  rtscts: false
  baudrate: 115200
  pan_id: 5727
  log_level: info
  channel: 25
  network_key:
    - 1
    - 3
    - 5
    - 7
    - 9
    - 11
    - 13
    - 15
    - 0
    - 2
    - 4
    - 6
    - 8
    - 10
    - 12
    - 13
  availability_blocklist: []
  availability_passlist: []
  last_seen: ISO_8601_local
device_options:
  retain: true
blocklist: []
passlist: []
queue:
  delay: 5
frontend:
  port: 8099
experimental: {}
socat:
  enabled: false
  master: 'pty,raw,echo=0,link=/tmp/ttyZ2M,mode=777'
  slave: 'tcp-listen:8485,keepalive,nodelay,reuseaddr,keepidle=1,keepintvl=1,keepcnt=5'
  options: '-d -d'
  log: false

```

**Running platform (details from Suypervisor > System)**
```
Core: core-2021.5.2
Supervisor: supervisor-2021.04.3
Operating System: Raspbian GNU/Linux 10 (buster)
```

**Your logs from Home Assistant Supervisor**
```
21-05-11 17:47:47 INFO (MainThread) [supervisor.resolution.evaluate] Starting system evaluation with state CoreState.RUNNING
21-05-11 17:47:48 ERROR (SyncWorker_3) [supervisor.resolution.evaluations.container] Corrupt docker overlayfs detect: 500 Server Error for http+docker://localhost/v1.41/images/sha256:944007910474e3d91add364f49663fde260cc4081511524e2c3248e52e0b8571/json: Internal Server Error ("readlink /var/lib/docker/overlay2: invalid argument")
21-05-11 17:47:48 INFO (MainThread) [supervisor.resolution.evaluate] System evaluation complete
21-05-11 17:47:48 INFO (MainThread) [supervisor.resolution.fixup] Starting system autofix at state CoreState.RUNNING
21-05-11 17:47:48 INFO (MainThread) [supervisor.resolution.fixup] System autofix complete
21-05-11 17:48:57 INFO (MainThread) [supervisor.homeassistant.api] Updated Home Assistant API token
21-05-11 17:49:44 INFO (MainThread) [supervisor.api.security] /snapshots access from cebe7a76_hassio_google_drive_backup
21-05-11 17:49:50 INFO (MainThread) [supervisor.store.git] Update add-on https://github.com/sabeechen/hassio-google-drive-backup repository
21-05-11 17:49:50 INFO (MainThread) [supervisor.store.git] Update add-on https://github.com/hassio-addons/repository repository
21-05-11 17:49:50 INFO (MainThread) [supervisor.store.git] Update add-on https://github.com/zigbee2mqtt/hassio-zigbee2mqtt repository
21-05-11 17:49:50 INFO (MainThread) [supervisor.store.git] Update add-on https://github.com/home-assistant/addons repository
21-05-11 17:49:50 INFO (MainThread) [supervisor.store.git] Update add-on https://github.com/Draggon/hassio-hdd-tools repository
21-05-11 17:49:53 INFO (MainThread) [supervisor.store] Loading add-ons from store: 67 all - 0 new - 0 remove
21-05-11 17:49:53 INFO (MainThread) [supervisor.store] Loading add-ons from store: 67 all - 0 new - 0 remove
21-05-11 18:18:45 WARNING (MainThread) [supervisor.addons.options] Unknown option 'retain' for Zigbee2mqtt (45df7312_zigbee2mqtt)
21-05-11 18:19:02 INFO (MainThread) [supervisor.homeassistant.api] Updated Home Assistant API token
```
