### ISSUE TITLE
Coordinator failed to start, probably the panID is already in use

### ISSUE THREAD

**Issue by tomasz-grobelny** [zigbee2mqtt/hassio-zigbee2mqtt#113]
**Description of problem:**
Zigbee2mqtt addon fails to start with the following message:
```
Error: Coordinator failed to start, probably the panID is already in use, try a different panID or channel
```

I don't like the 'probably' part - of course I tried changing the panID several times but nothing changes. I am not sure what are the implications of changing channel, so haven't tried that. How do I get more detailed output to actually know what went wrong? Is it a problem with the device (slae.sh CC2652RB, flashed with https://github.com/Koenkk/Z-Stack-firmware/raw/master/coordinator/Z-Stack_3.x.0/bin/CC2652RB_coordinator_20210120.zip)? Or configuration? Or system?

Previously the stick worked on Odroid N2 (but I use that for something else now).

**Zigbee2mqtt add-on version (if edge, please report commit hash):**
```
Current version: 1.18.3-1
```

**Your entire configuration from the frontend (with sensitive fields redacted)**:
```
data_path: /config/zigbee2mqtt
external_converters: []
devices: devices.yaml
groups: groups.yaml
homeassistant: true
permit_join: false
mqtt:
  base_topic: zigbee2mqtt
serial:
  port: /dev/ttyUSB0
advanced:
  log_level: info
  pan_id: 6756
  channel: 11
  network_key:
    - 1
    - 3
    - 5
    - 7
    - 9
    - 11
    - 13
    - 15
    - 0
    - 2
    - 4
    - 6
    - 8
    - 10
    - 12
    - 13
  availability_blocklist: []
  availability_passlist: []
device_options: {}
blocklist: []
passlist: []
queue: {}
frontend:
  port: 8099
experimental: {}
socat:
  enabled: false
  master: 'pty,raw,echo=0,link=/tmp/ttyZ2M,mode=777'
  slave: 'tcp-listen:8485,keepalive,nodelay,reuseaddr,keepidle=1,keepintvl=1,keepcnt=5'
  options: '-d -d'
  log: false
```

**Running platform (details from Suypervisor > System)**
```
core-2021.5.4
supervisor-2021.04.3
Debian GNU/Linux 10 (buster)
```

**Your logs from Home Assistant Supervisor**
```
[22:50:06] INFO: Handing over control to Zigbee2mqtt Core ...
> zigbee2mqtt@1.18.3 start /app
> node index.js
Zigbee2MQTT:info  2021-05-18 22:50:15: Logging to console and directory: '/config/zigbee2mqtt/log/2021-05-18.22-50-11' filename: log.txt
Zigbee2MQTT:info  2021-05-18 22:50:15: Starting Zigbee2MQTT version 1.18.3 (commit #1.18.3)
Zigbee2MQTT:info  2021-05-18 22:50:15: Starting zigbee-herdsman (0.13.92)
Zigbee2MQTT:error 2021-05-18 22:51:31: Error while starting zigbee-herdsman
Zigbee2MQTT:error 2021-05-18 22:51:31: Failed to start zigbee
Zigbee2MQTT:error 2021-05-18 22:51:31: Check https://www.zigbee2mqtt.io/information/FAQ.html#help-zigbee2mqtt-fails-to-start for possible solutions
Zigbee2MQTT:error 2021-05-18 22:51:31: Exiting...
Zigbee2MQTT:error 2021-05-18 22:51:31: Error: Coordinator failed to start, probably the panID is already in use, try a different panID or channel
    at /app/node_modules/zigbee-herdsman/dist/adapter/z-stack/adapter/startZnp.js:172:23
    at Generator.throw (<anonymous>)
    at rejected (/app/node_modules/zigbee-herdsman/dist/adapter/z-stack/adapter/startZnp.js:25:65)
npm ERR! code ELIFECYCLE
npm ERR! errno 1
npm ERR! zigbee2mqtt@1.18.3 start: `node index.js`
npm ERR! Exit status 1
npm ERR! 
npm ERR! Failed at the zigbee2mqtt@1.18.3 start script.
npm ERR! This is probably not a problem with npm. There is likely additional logging output above.
npm ERR! A complete log of this run can be found in:
npm ERR!     /root/.npm/_logs/2021-05-18T20_51_31_306Z-debug.log
```
