### ISSUE TITLE
Getting a lot of warnings: Unknown option ...

### ISSUE THREAD

**Issue by ovizii** [zigbee2mqtt/hassio-zigbee2mqtt#115]
**Description of problem:**
Running home assistent and Zigbee2mqtt Current version: 1.18.1-1 for some time all worked and still works but now I noticed a lot of warnings in the supervisor logs.

**Zigbee2mqtt add-on version (if edge, please report commit hash):**
```
Zigbee2mqtt
Current version: 1.18.1-1
```

**Your entire configuration from the frontend (with sensitive fields redacted)**:
```
not sure exactly how to provide this, what do you mean by "from the frontend"? 

This is the config of the zigbee2mqtt addon cobbled together from countless websites until it worked:

data_path: /share/zigbee2mqtt
external_converters: []
devices: devices.yaml
groups: groups.yaml
homeassistant: true
permit_join: false
mqtt:
  base_topic: zigbee2mqtt
  server: 'mqtt://10.10.10.87:1883'
  user: mosquitto
  password: redacted
  include_device_information: true
  keepalive: 60
serial:
  port: >-
    /dev/serial/by-id/usb-Silicon_Labs_slae.sh_cc2652rb_stick_-_slaesh_s_iot_stuff_00_12_4B_00_21_CB_EC_89-if00-port0
advanced:
  log_level: debug
  pan_id: 6754
  channel: 11
  network_key:
    - x
    - x
    - redacted
    - x
  availability_blocklist: []
  availability_passlist: []
  homeassistant_discovery_topic: homeassistant
  homeassistant_status_topic: homeassistant/status
  report: true
device_options: {}
blocklist: []
passlist: []
queue: {}
frontend:
  port: 8099
experimental:
  new_api: true
socat:
  enabled: false
  master: 'pty,raw,echo=0,link=/dev/ttyZ2M,mode=777'
  slave: 'tcp-listen:8485,keepalive,nodelay,reuseaddr,keepidle=1,keepintvl=1,keepcnt=5'
  restartdelay: 1
  initialdelay: 1
  options: '-d -d'
  log: false
zigbee_herdsman_debug: true
zigbee_shepherd_debug: true

```

**Running platform (details from Suypervisor > System)**
```
Core
Version
core-2021.5.4
Newest Version
core-2021.5.4

Operating System
Home Assistant OS 5.13
```

**Your logs from Home Assistant Supervisor**
```
21-05-19 11:10:51 WARNING (MainThread) [supervisor.addons.options] Unknown option 'new_api' for Zigbee2mqtt (7ad98f9c_zigbee2mqtt)
21-05-19 11:10:51 WARNING (MainThread) [supervisor.addons.options] Unknown option 'restartdelay' for Zigbee2mqtt (7ad98f9c_zigbee2mqtt)
21-05-19 11:10:51 WARNING (MainThread) [supervisor.addons.options] Unknown option 'initialdelay' for Zigbee2mqtt (7ad98f9c_zigbee2mqtt)
21-05-19 11:10:51 WARNING (MainThread) [supervisor.addons.options] Option 'zigbee_shepherd_debug' does not exist in the schema for Zigbee2mqtt (7ad98f9c_zigbee2mqtt)
21-05-19 11:10:51 WARNING (MainThread) [supervisor.addons.options] Unknown option 'new_api' for Zigbee2mqtt (7ad98f9c_zigbee2mqtt)
21-05-19 11:10:51 WARNING (MainThread) [supervisor.addons.options] Unknown option 'restartdelay' for Zigbee2mqtt (7ad98f9c_zigbee2mqtt)
21-05-19 11:10:51 WARNING (MainThread) [supervisor.addons.options] Unknown option 'initialdelay' for Zigbee2mqtt (7ad98f9c_zigbee2mqtt)
21-05-19 11:10:51 WARNING (MainThread) [supervisor.addons.options] Option 'zigbee_shepherd_debug' does not exist in the schema for Zigbee2mqtt (7ad98f9c_zigbee2mqtt)
21-05-19 11:10:51 WARNING (MainThread) [supervisor.addons.options] Unknown option 'new_api' for Zigbee2mqtt (7ad98f9c_zigbee2mqtt)
21-05-19 11:10:51 WARNING (MainThread) [supervisor.addons.options] Unknown option 'restartdelay' for Zigbee2mqtt (7ad98f9c_zigbee2mqtt)
21-05-19 11:10:51 WARNING (MainThread) [supervisor.addons.options] Unknown option 'initialdelay' for Zigbee2mqtt (7ad98f9c_zigbee2mqtt)
21-05-19 11:10:51 WARNING (MainThread) [supervisor.addons.options] Option 'zigbee_shepherd_debug' does not exist in the schema for Zigbee2mqtt (7ad98f9c_zigbee2mqtt)
21-05-19 11:10:51 WARNING (MainThread) [supervisor.addons.options] Unknown option 'new_api' for Zigbee2mqtt (7ad98f9c_zigbee2mqtt)
21-05-19 11:10:51 WARNING (MainThread) [supervisor.addons.options] Unknown option 'restartdelay' for Zigbee2mqtt (7ad98f9c_zigbee2mqtt)
21-05-19 11:10:51 WARNING (MainThread) [supervisor.addons.options] Unknown option 'initialdelay' for Zigbee2mqtt (7ad98f9c_zigbee2mqtt)
21-05-19 11:10:51 WARNING (MainThread) [supervisor.addons.options] Option 'zigbee_shepherd_debug' does not exist in the schema for Zigbee2mqtt (7ad98f9c_zigbee2mqtt)
21-05-19 11:10:51 WARNING (MainThread) [supervisor.addons.options] Unknown option 'new_api' for Zigbee2mqtt (7ad98f9c_zigbee2mqtt)
21-05-19 11:10:51 WARNING (MainThread) [supervisor.addons.options] Unknown option 'restartdelay' for Zigbee2mqtt (7ad98f9c_zigbee2mqtt)
21-05-19 11:10:51 WARNING (MainThread) [supervisor.addons.options] Unknown option 'initialdelay' for Zigbee2mqtt (7ad98f9c_zigbee2mqtt)
21-05-19 11:10:51 WARNING (MainThread) [supervisor.addons.options] Option 'zigbee_shepherd_debug' does not exist in the schema for Zigbee2mqtt (7ad98f9c_zigbee2mqtt)
21-05-19 11:10:51 WARNING (MainThread) [supervisor.addons.options] Unknown option 'new_api' for Zigbee2mqtt (7ad98f9c_zigbee2mqtt)
21-05-19 11:10:51 WARNING (MainThread) [supervisor.addons.options] Unknown option 'restartdelay' for Zigbee2mqtt (7ad98f9c_zigbee2mqtt)
21-05-19 11:10:51 WARNING (MainThread) [supervisor.addons.options] Unknown option 'initialdelay' for Zigbee2mqtt (7ad98f9c_zigbee2mqtt)
21-05-19 11:10:51 WARNING (MainThread) [supervisor.addons.options] Option 'zigbee_shepherd_debug' does not exist in the schema for Zigbee2mqtt (7ad98f9c_zigbee2mqtt)
21-05-19 11:10:51 WARNING (MainThread) [supervisor.addons.options] Unknown option 'new_api' for Zigbee2mqtt (7ad98f9c_zigbee2mqtt)
21-05-19 11:10:51 WARNING (MainThread) [supervisor.addons.options] Unknown option 'restartdelay' for Zigbee2mqtt (7ad98f9c_zigbee2mqtt)
21-05-19 11:10:51 WARNING (MainThread) [supervisor.addons.options] Unknown option 'initialdelay' for Zigbee2mqtt (7ad98f9c_zigbee2mqtt)
21-05-19 11:10:51 WARNING (MainThread) [supervisor.addons.options] Option 'zigbee_shepherd_debug' does not exist in the schema for Zigbee2mqtt (7ad98f9c_zigbee2mqtt)
21-05-19 11:10:51 WARNING (MainThread) [supervisor.addons.options] Unknown option 'new_api' for Zigbee2mqtt (7ad98f9c_zigbee2mqtt)
21-05-19 11:10:51 WARNING (MainThread) [supervisor.addons.options] Unknown option 'restartdelay' for Zigbee2mqtt (7ad98f9c_zigbee2mqtt)
21-05-19 11:10:51 WARNING (MainThread) [supervisor.addons.options] Unknown option 'initialdelay' for Zigbee2mqtt (7ad98f9c_zigbee2mqtt)
21-05-19 11:10:51 WARNING (MainThread) [supervisor.addons.options] Option 'zigbee_shepherd_debug' does not exist in the schema for Zigbee2mqtt (7ad98f9c_zigbee2mqtt)
21-05-19 11:10:51 WARNING (MainThread) [supervisor.addons.options] Unknown option 'new_api' for Zigbee2mqtt (7ad98f9c_zigbee2mqtt)
21-05-19 11:10:51 WARNING (MainThread) [supervisor.addons.options] Unknown option 'restartdelay' for Zigbee2mqtt (7ad98f9c_zigbee2mqtt)
21-05-19 11:10:51 WARNING (MainThread) [supervisor.addons.options] Unknown option 'initialdelay' for Zigbee2mqtt (7ad98f9c_zigbee2mqtt)
21-05-19 11:10:51 WARNING (MainThread) [supervisor.addons.options] Option 'zigbee_shepherd_debug' does not exist in the schema for Zigbee2mqtt (7ad98f9c_zigbee2mqtt)
21-05-19 11:10:51 WARNING (MainThread) [supervisor.addons.options] Unknown option 'new_api' for Zigbee2mqtt (7ad98f9c_zigbee2mqtt)
21-05-19 11:10:51 WARNING (MainThread) [supervisor.addons.options] Unknown option 'restartdelay' for Zigbee2mqtt (7ad98f9c_zigbee2mqtt)
21-05-19 11:10:51 WARNING (MainThread) [supervisor.addons.options] Unknown option 'initialdelay' for Zigbee2mqtt (7ad98f9c_zigbee2mqtt)
21-05-19 11:10:51 WARNING (MainThread) [supervisor.addons.options] Option 'zigbee_shepherd_debug' does not exist in the schema for Zigbee2mqtt (7ad98f9c_zigbee2mqtt)
21-05-19 11:10:51 WARNING (MainThread) [supervisor.addons.options] Unknown option 'new_api' for Zigbee2mqtt (7ad98f9c_zigbee2mqtt)
21-05-19 11:10:51 WARNING (MainThread) [supervisor.addons.options] Unknown option 'restartdelay' for Zigbee2mqtt (7ad98f9c_zigbee2mqtt)
21-05-19 11:10:51 WARNING (MainThread) [supervisor.addons.options] Unknown option 'initialdelay' for Zigbee2mqtt (7ad98f9c_zigbee2mqtt)
21-05-19 11:10:51 WARNING (MainThread) [supervisor.addons.options] Option 'zigbee_shepherd_debug' does not exist in the schema for Zigbee2mqtt (7ad98f9c_zigbee2mqtt)
21-05-19 11:10:51 WARNING (MainThread) [supervisor.addons.options] Unknown option 'new_api' for Zigbee2mqtt (7ad98f9c_zigbee2mqtt)
21-05-19 11:10:51 WARNING (MainThread) [supervisor.addons.options] Unknown option 'restartdelay' for Zigbee2mqtt (7ad98f9c_zigbee2mqtt)
21-05-19 11:10:51 WARNING (MainThread) [supervisor.addons.options] Unknown option 'initialdelay' for Zigbee2mqtt (7ad98f9c_zigbee2mqtt)
21-05-19 11:10:51 WARNING (MainThread) [supervisor.addons.options] Option 'zigbee_shepherd_debug' does not exist in the schema for Zigbee2mqtt (7ad98f9c_zigbee2mqtt)
21-05-19 11:10:51 WARNING (MainThread) [supervisor.addons.options] Unknown option 'new_api' for Zigbee2mqtt (7ad98f9c_zigbee2mqtt)
21-05-19 11:10:51 WARNING (MainThread) [supervisor.addons.options] Unknown option 'restartdelay' for Zigbee2mqtt (7ad98f9c_zigbee2mqtt)
21-05-19 11:10:51 WARNING (MainThread) [supervisor.addons.options] Unknown option 'initialdelay' for Zigbee2mqtt (7ad98f9c_zigbee2mqtt)
21-05-19 11:10:51 WARNING (MainThread) [supervisor.addons.options] Option 'zigbee_shepherd_debug' does not exist in the schema for Zigbee2mqtt (7ad98f9c_zigbee2mqtt)
```
