### ISSUE TITLE
Xiaomi/Aqara WSDCGQ11LMstop updating

### ISSUE THREAD

**Issue by rcxrbt** [zigbee2mqtt/hassio-zigbee2mqtt#137]
**Description of problem:**
```
Xiaomi/Aquara WSDCGQ11LM stop updating
Re-adopting device, work fine some hours or days.
```

**Zigbee2mqtt add-on version:**
```
Zigbee2mqtt add-on 1.18.1-1
```

**Your entire configuration from the frontend (with sensitive fields redacted)**:
```
data_path: /share/zigbee2mqtt
external_converters: []
devices: devices.yaml
groups: groups.yaml
homeassistant: true
permit_join: false
mqtt:
  base_topic: zigbee2mqtt
  server: mqtt://core-mosquitto
  user: xxx
  password: xxx
serial:
  port: /dev/ttyACM0
  disable_led: true
advanced:
  log_level: info
  pan_id: 6754
  channel: 11
  network_key:
    - 1
    - 3
    - 5
    - 7
    - 9
    - 11
    - 13
    - 15
    - 0
    - 2
    - 4
    - 6
    - 8
    - 10
    - 12
    - 13
  availability_blocklist: []
  availability_passlist: []
device_options: {}
blocklist: []
passlist: []
queue: {}
frontend:
  port: 8099
experimental: {}
socat:
  enabled: false
  master: pty,raw,echo=0,link=/dev/ttyZ2M,mode=777
  slave: tcp-listen:8485,keepalive,nodelay,reuseaddr,keepidle=1,keepintvl=1,keepcnt=5
  options: '-d -d'
  log: false

```

**Running platform (details from Suypervisor > System)**
```
Core: core-2021.5.5
Supervisor: supervisor-2021.05.4
Operating System: Home Assistant OS 5.13
```

**Your logs from Home Assistant Supervisor**
```
Not rilevant
```
