### ISSUE TITLE
Frontend fails to load

### ISSUE THREAD

**Issue by hank86** [zigbee2mqtt/hassio-zigbee2mqtt#138]
**Description of problem:**
After switching to the new Repro and Zigbee2mqtt 1.19.1-1, my frontend fails to load. So far, I used port 8099 for the frontend, which worked fine. 
Now with Zigbee2mqtt 1.19.1-1 the frontend is starting up, keeps loading, but in the end fails to load any entities. 

```
Loading devices takes too long time. Consider reading documentation
```

With standard port 8080, I get the following message:

```
502: Bad Gateway
```

edit:
There might be a specific Firefox 89.0 issue. I tried Safari 14.1.1 and it actually works just fine. Here the Firefox console output:

```
Firefox kann keine Verbindung zu dem Server unter wss://hassio.local:8123/api/hassio_ingress/icud41yOOa_lpxBB9e1HVQMhRSY6dBFkdvYLePEt-jY/api aufbauen. vendor.215ef97a9e734a42331c.js:2:1151562

Source-Map-Fehler: Error: NetworkError when attempting to fetch resource.
Ressourcen-Adresse: http://hassio.local:8123/api/hassio_ingress/icud41yOOa_lpxBB9e1HVQMhRSY6dBFkdvYLePEt-jY/scripts/vendor.215ef97a9e734a42331c.js
Source-Map-Adresse: vendor.215ef97a9e734a42331c.js.map
```

edit 2:
This error is related to the new HTTPS-only mode in Firefox. I deactivated it before specifically for http://hassio.local:8123, which did not work. Deactivating the HTTPS-only mode for all pages in the Firefox setting did the trick.

**Zigbee2mqtt add-on version:**
```
> zigbee2mqtt@1.19.1 start /app
```

**Your entire configuration from the frontend (with sensitive fields redacted)**:
```
data_path: /config/zigbee2mqtt
external_converters: []
devices: devices.yaml
groups: groups.yaml
homeassistant: true
permit_join: false
mqtt:
  base_topic: zigbee2mqtt
  server: mqtt://core-mosquitto
  user: [xy]
  password: [xy]
serial:
  disable_led: true
  port: /dev/ttyACM0
advanced:
  log_level: info
  pan_id: 6754
  channel: 11
  network_key:
    - 1
    - 3
    - 5
    - 7
    - 9
    - 11
    - 13
    - 15
    - 0
    - 2
    - 4
    - 6
    - 8
    - 10
    - 12
    - 13
  availability_blocklist: []
  availability_passlist: []
device_options: {}
blocklist: []
passlist: []
queue: {}
frontend:
  port: 8099
experimental:
  new_api: true
socat:
  enabled: false
  master: pty,raw,echo=0,link=/dev/ttyZ2M,mode=777
  slave: tcp-listen:8485,keepalive,nodelay,reuseaddr,keepidle=1,keepintvl=1,keepcnt=5
  restartdelay: 1
  initialdelay: 1
  options: '-d -d'
  log: false
```

**Running platform**
```
Core: core-2021.6.3
Supervisor: supervisor-2021.05.4
Operating System: Home Assistant OS 5.13
```

**Your logs from Home Assistant Supervisor**
```
Zigbee2MQTT:info  2021-06-09 12:21:20: Started frontend on port 0.0.0.0:8099
```
