### ISSUE TITLE
Zigbee2mqtt needs restarting every couple of days - UnhandledPromiseRejectionWarning

### ISSUE THREAD

**Issue by andymk3** [zigbee2mqtt/hassio-zigbee2mqtt#140]
**Description of problem:**
```
Every couple of days, my Zigbee devices stop responding. 

The only way to fix the problem is to restart the Zigbee2mqtt addon 
and it all works perfectly again for a few days until it happens again. 

Not sure if this is a bug or a setup problem. 

It's been happening for a few months now.

I am using a Conbee-II remotely connected via ser2net on a Pi Zero W.

This is my first issue report so I hope I have covered everything.

```
**Zigbee2mqtt add-on version (if edge, please report commit hash):**
```
> zigbee2mqtt@1.19.1 start /app
```

**Your entire configuration from the frontend (with sensitive fields redacted)**:
```
data_path: /share/zigbee2mqtt
external_converters: []
devices: devices.yaml
groups: groups.yaml
homeassistant: true
permit_join: false
mqtt:
  base_topic: zigbee2mqtt
  server: mqtt://core-mosquitto:1883
  user: *******
  password: ********
serial:
  port: tcp://10.0.1.59:20108
  adapter: deconz
advanced:
  log_level: info
  pan_id: 6754
  channel: 11
  network_key:
    - 1
    - 3
    - 5
    - 7
    - 9
    - 11
    - 13
    - 15
    - 0
    - 2
    - 4
    - 6
    - 8
    - 10
    - 12
    - 13
  availability_blocklist: []
  availability_passlist: []
  rtscts: false
device_options: {}
blocklist: []
passlist: []
queue: {}
frontend:
  port: 8099
experimental: {}
socat:
  enabled: false
  master: pty,raw,echo=0,link=/dev/ttyZ2M,mode=777,end-close
  slave: tcp4:10.0.1.59:20108,ignoreeof
  restartdelay: 1
  initialdelay: 1
  options: '-d -d'
  log: true

```

**Running platform (details from Supervisor > System)**
```

Version
Core: core-2021.6.2
Supervisor: supervisor-2021.06.0
OS: Home Assistant OS 5.13
```

**Your logs from Home Assistant Supervisor**
```
(node:328) UnhandledPromiseRejectionWarning: Unhandled promise rejection. This error originated either by throwing inside of an async function without a catch block, or by rejecting a promise which was not handled with .catch(). To terminate the node process on unhandled promise rejection, use the CLI flag `--unhandled-rejections=strict` (see https://nodejs.org/api/cli.html#cli_unhandled_rejections_mode). (rejection id: 757)
(node:328) UnhandledPromiseRejectionWarning: TypeError: Cannot read property 'isOpen' of undefined
    at Driver.<anonymous> (/app/node_modules/zigbee-herdsman/dist/adapter/deconz/driver/driver.js:430:45)
    at Generator.next (<anonymous>)
    at /app/node_modules/zigbee-herdsman/dist/adapter/deconz/driver/driver.js:8:71
    at new Promise (<anonymous>)
    at __awaiter (/app/node_modules/zigbee-herdsman/dist/adapter/deconz/driver/driver.js:4:12)
    at Driver.processBusyQueue (/app/node_modules/zigbee-herdsman/dist/adapter/deconz/driver/driver.js:411:16)
    at Timeout._onTimeout (/app/node_modules/zigbee-herdsman/dist/adapter/deconz/driver/driver.js:117:34)
    at listOnTimeout (internal/timers.js:554:17)
    at processTimers (internal/timers.js:497:7)


// This is repeated over and over.
```
