### ISSUE TITLE
Zigbee2mqtt add-on using deprecated command, no longer starting on restart

### ISSUE THREAD

**Issue by jyavenard** [zigbee2mqtt/hassio-zigbee2mqtt#141]
**Description of problem:**
Following update to 1.19.1-1 (from 1.18.1-1) ; zigbee2mqtt no longer start on restart.
Logs indicate use of related command now deprecated, not sure if that's related.

**Zigbee2mqtt add-on version (if edge, please report commit hash):**
```
1.19.1-1
```

**Your entire configuration from the frontend (with sensitive fields redacted)**:
```
data_path: /config/zigbee2mqtt
external_converters: []
devices: devices.yaml
groups: groups.yaml
homeassistant: true
permit_join: false
mqtt:
  base_topic: zigbee2mqtt
  server: mqtt://core-mosquitto
  user: mqtt
  password: password
serial:
  port: /dev/ttyUSB0
advanced:
  log_level: info
  pan_id: 6755
  channel: 11
  network_key:
    - 1
    - 3
    - 5
    - 7
    - 9
    - 11
    - 13
    - 15
    - 0
    - 2
    - 4
    - 6
    - 8
    - 10
    - 12
    - 13
  availability_timeout: 30
  availability_blocklist: []
  availability_passlist:
    - kitchen_light_1
    - kitchen_light_2
    - kitchen_light_3
    - cinema_light
    - dressing_light_1
    - dressing_light_2
    - living_light_1
    - porch_light
    - sebastien_light_1
    - sebastien_light_2
device_options: {}
blocklist: []
passlist: []
queue: {}
frontend:
  port: 8099
experimental: {}
socat:
  enabled: false
  master: pty,raw,echo=0,link=/dev/ttyZ2M,mode=777
  slave: tcp-listen:8485,keepalive,nodelay,reuseaddr,keepidle=1,keepintvl=1,keepcnt=5
  options: '-d -d'
  log: false
```

**Running platform (details from Suypervisor > System)**
```
Version core-2021.6.4 
Core: core-2021.2.2
supervisor-2021.06.0
Armbian 21.05.2 Focal
```

**Your logs from Home Assistant Supervisor**
```
21-06-15 03:26:30 WARNING (MainThread) [supervisor.addons.validate] Add-on config 'startup' with 'before' is deprecated. Please report this to the maintainer of Zigbee2mqtt
21-06-15 03:26:30 WARNING (MainThread) [supervisor.addons.validate] Add-on config 'auto_uart' is deprecated, use 'uart'. Please report this to the maintainer of Zigbee2mqtt
21-06-15 03:26:30 WARNING (MainThread) [supervisor.addons.validate] Add-on config 'startup' with 'before' is deprecated. Please report this to the maintainer of zigbee2mqtt-edge
21-06-15 03:26:30 WARNING (MainThread) [supervisor.addons.validate] Add-on config 'auto_uart' is deprecated, use 'uart'. Please report this to the maintainer of zigbee2mqtt-edge
```
