### ISSUE TITLE
Zigbee2mqtt 1.19.1-1 - sensors missing or frozen

### ISSUE THREAD

**Issue by danros3** [zigbee2mqtt/hassio-zigbee2mqtt#142]
From the day I connect new aqara WSDCGQ11LM sensor on my HA with zigbee2mqtt some mija sensor WSDCGQ11LM was missing and some stay frozed. Finally blitzwolf TS0121_plug didn't work as router (before Updating they worked without problem). 

I tried to pass to edge version: now new sensor aqara work fine only if connected direct to cc2530 antenna, mijia still frozed and 3 of 4 didn't show lqi on zigbee web page, blitzwolf plug work except router funcion.

My config is
```
data_path: /config/zigbee2mqtt
external_converters: []
devices: devices.yaml
groups: groups.yaml
homeassistant: true
permit_join: false
mqtt:
  base_topic: zigbee2mqtt
  server: mqtt://core-mosquitto
  user: xxx
  password: xxx
serial:
  port: /dev/ttyUSB0
advanced:
  log_level: info
  pan_id: 6754
  channel: 11
  network_key:
    - 1
    - 3
    - 5
    - 7
    - 9
    - 11
    - 13
    - 15
    - 0
    - 2
    - 4
    - 6
    - 8
    - 10
    - 12
    - 13
  availability_blocklist: []
  availability_passlist: []
device_options: {}
blocklist: []
passlist: []
queue: {}
frontend:
  port: 8099
experimental: {}
socat:
  enabled: false
  master: pty,raw,echo=0,link=/tmp/ttyZ2M,mode=777
  slave: tcp-listen:8485,keepalive,nodelay,reuseaddr,keepidle=1,keepintvl=1,keepcnt=5
  options: '-d -d'
  log: false
```

Thank you
