### ISSUE TITLE
Error while starting zigbee-herdsman

### ISSUE THREAD

**Issue by empatel96** [zigbee2mqtt/hassio-zigbee2mqtt#147]
**Description of problem:**
My CC2531 stick has been running fine for a while. On occasions when it stops, I usually unplug and plug back in or uninstall/install zigbee2mqtt add on in Home Assistant.
Home Assistant installed with IOTStack

**Zigbee2mqtt add-on version (if edge, please report commit hash):**
```
> zigbee2mqtt@1.18.1 start /app
```

**Your entire configuration from the frontend (with sensitive fields redacted)**:
```
data_path: /share/zigbee2mqtt
external_converters: []
devices: devices.yaml
groups: groups.yaml
homeassistant: true
permit_join: false
mqtt:
  base_topic: zigbee2mqtt
  server: mqtt://192.xxx.xxx.xxx:1883
  user: user
  password: password
serial:
  port: /dev/ttyAMA0
  disable_led: false
advanced:
  pan_id: 6754
  channel: 11
  network_key:
    - 1
    - 3
    - 5
    - 7
    - 9
    - 11
    - 13
    - 15
    - 0
    - 2
    - 4
    - 6
    - 8
    - 10
    - 12
    - 13
  availability_blocklist: []
  availability_passlist: []
device_options: {}
blocklist: []
passlist: []
queue: {}
frontend:
  port: 8099
experimental: {}
socat:
  enabled: false
  master: pty,raw,echo=0,link=/dev/ttyZ2M,mode=777
  slave: tcp-listen:8485,keepalive,nodelay,reuseaddr,keepidle=1,keepintvl=1,keepcnt=5
  restartdelay: 1
  initialdelay: 1
  options: '-d -d'
  log: false
ban: []
whitelist: []

```

**Running platform (details from Suypervisor > System)**
```
// Example
Core: core-2021.6.6
Supervisor: supervisor-2021.06.6
Operating System: Raspbian 10
```

**Your logs from Home Assistant Supervisor**
```
[s6-init] making user provided files available at /var/run/s6/etc...exited 0.
[s6-init] ensuring user provided files have correct perms...exited 0.
[fix-attrs.d] applying ownership & permissions fixes...
[fix-attrs.d] done.
[cont-init.d] executing container initialization scripts...
[cont-init.d] socat.sh: executing... 
[20:07:17] INFO: Socat not enabled, marking service as down
[cont-init.d] socat.sh: exited 0.
[cont-init.d] zigbee2mqtt.sh: executing... 
[20:07:18] INFO: MQTT available, fetching server detail ...
[20:07:18] INFO: Previous config file found, checking backup
[20:07:18] INFO: Creating backup config in '/share/zigbee2mqtt/.configuration.yaml.bk'
[20:07:18] INFO: Adjusting Zigbee2mqtt core yaml config with add-on quirks ...
[cont-init.d] zigbee2mqtt.sh: exited 0.
[cont-init.d] done.
[services.d] starting services
[services.d] done.
[20:07:19] INFO: Handing over control to Zigbee2mqtt Core ...
> zigbee2mqtt@1.18.1 start /app
> node index.js
Zigbee2MQTT:info  2021-06-28 20:07:23: Logging to console and directory: '/share/zigbee2mqtt/log/2021-06-28.20-07-22' filename: log.txt
Zigbee2MQTT:info  2021-06-28 20:07:23: Starting Zigbee2MQTT version 1.18.1 (commit #1.18.1)
Zigbee2MQTT:info  2021-06-28 20:07:23: Starting zigbee-herdsman (0.13.71)
Zigbee2MQTT:error 2021-06-28 20:07:43: Error while starting zigbee-herdsman
Zigbee2MQTT:error 2021-06-28 20:07:43: Failed to start zigbee
Zigbee2MQTT:error 2021-06-28 20:07:43: Exiting...
Zigbee2MQTT:error 2021-06-28 20:07:43: Error: Failed to connect to the adapter (Error: SRSP - SYS - ping after 6000ms)
    at ZStackAdapter.<anonymous> (/app/node_modules/zigbee-herdsman/dist/adapter/z-stack/adapter/zStackAdapter.js:94:31)
    at Generator.throw (<anonymous>)
    at rejected (/app/node_modules/zigbee-herdsman/dist/adapter/z-stack/adapter/zStackAdapter.js:25:65)
npm ERR! code ELIFECYCLE
npm ERR! errno 1
npm ERR! zigbee2mqtt@1.18.1 start: `node index.js`
npm ERR! Exit status 1
npm ERR! 
npm ERR! Failed at the zigbee2mqtt@1.18.1 start script.
npm ERR! This is probably not a problem with npm. There is likely additional logging output above.
npm ERR! A complete log of this run can be found in:
npm ERR!     /root/.npm/_logs/2021-06-28T19_07_43_439Z-debug.log
```

I've been through the troubleshooting process too, so checked if it finds the stick on the Pi, and installed latest firmware

```
crw-rw----  1 root dialout 166,   0 Jun 28 19:52 ttyACM0
```

**Comment by empatel96** [comment]
Updated my configuration to match the default and it now stalls at the following:

```
[s6-init] making user provided files available at /var/run/s6/etc...exited 0.
[s6-init] ensuring user provided files have correct perms...exited 0.
[fix-attrs.d] applying ownership & permissions fixes...
[fix-attrs.d] done.
[cont-init.d] executing container initialization scripts...
[cont-init.d] socat.sh: executing... 
[05:01:51] INFO: Socat not enabled, marking service as down
[cont-init.d] socat.sh: exited 0.
[cont-init.d] zigbee2mqtt.sh: executing... 
[05:01:52] INFO: MQTT available, fetching server detail ...
[05:01:53] INFO: Previous config file found, checking backup
[05:01:53] INFO: Creating backup config in '/share/zigbee2mqtt/.configuration.yaml.bk'
[05:01:53] INFO: Adjusting Zigbee2mqtt core yaml config with add-on quirks ...
[cont-init.d] zigbee2mqtt.sh: exited 0.
[cont-init.d] done.
[services.d] starting services
[services.d] done.
[05:01:54] INFO: Handing over control to Zigbee2mqtt Core ...
> zigbee2mqtt@1.18.1 start /app
> node index.js
```

Configuration:
```
data_path: /share/zigbee2mqtt
external_converters: []
devices: devices.yaml
groups: groups.yaml
homeassistant: true
permit_join: false
mqtt:
  base_topic: zigbee2mqtt
  server: mqtt://192.xxx.xxx.xxx:1883
  user: user
  password: password
serial:
  port: /dev/ttyACM0
advanced:
  log_level: warn
  pan_id: 6754
  channel: 11
  network_key:
    - 1
    - 3
    - 5
    - 7
    - 9
    - 11
    - 13
    - 15
    - 0
    - 2
    - 4
    - 6
    - 8
    - 10
    - 12
    - 13
  availability_blocklist: []
  availability_passlist: []
device_options: {}
blocklist: []
passlist: []
queue: {}
frontend:
  port: 8099
experimental: {}
socat:
  enabled: false
  master: pty,raw,echo=0,link=/tmp/ttyZ2M,mode=777
  slave: tcp-listen:8485,keepalive,nodelay,reuseaddr,keepidle=1,keepintvl=1,keepcnt=5
  options: '-d -d'
  log: false

```
