### ISSUE TITLE
Cannot set "homeassistant_legacy_entity_attributes" option

### ISSUE THREAD

**Issue by darootler** [zigbee2mqtt/hassio-zigbee2mqtt#149]
**Description of problem:**
I am not able to set the configuration option "homeassistant_legacy_entity_attributes" within the add on configuration tab

**Zigbee2mqtt add-on version (if edge, please report commit hash):**
```
zigbee2mqtt@1.20.0-1
```

**Your entire configuration from the frontend (with sensitive fields redacted)**:
```
data_path: /share/zigbee2mqtt
external_converters: []
devices: devices.yaml
groups: groups.yaml
homeassistant: true
permit_join: false
mqtt:
  base_topic: zigbee
  password: '!secret zigbee_password'
  server: mqtt://core-mosquitto:1883
  user: '!secret zigbee_username'
serial:
  port: /dev/serial/by-id/usb-1a86_USB_Serial-if00-port0
advanced:
  availability_timeout: 600
  channel: 25
  homeassistant_legacy_entity_attributes: false
  last_seen: ISO_8601_local
  log_level: warn
  network_key: []
  network_key_string: '!secret zigbee_network_key'
  pan_id: '!secret zigbee_pan_id'
  report: true
device_options: {}
blocklist: []
passlist: []
queue: {}
frontend:
  port: 8099
experimental: {}
socat:
  enabled: false
```

**Running platform (details from Suypervisor > System)**
```
// Example
Core: core-2021.6.6
Supervisor: supervisor-2021.06.6
Operating System: Home Assistant OS 6.1
```

**Your logs from Home Assistant Supervisor**
```
21-07-01 20:38:26 WARNING (MainThread) [supervisor.addons.options] Unknown option 'homeassistant_legacy_entity_attributes' for Zigbee2mqtt (45df7312_zigbee2mqtt)
```
