### ISSUE TITLE
Failed to start zigbee

### ISSUE THREAD

**Issue by flayy73** [zigbee2mqtt/hassio-zigbee2mqtt#151]
I have problem to start the HA supervised Zigbee2Mqtt (No edge) addon.
HA supervised (docker version), Ubuntu 21.04 into a VBox.

**Zigbee2mqtt add-on version 1.20.0-1**

**Zigbee2Mqtt Configuration**:
```
data_path: /config/zigbee2mqtt
external_converters: []
devices: devices.yaml
groups: groups.yaml
homeassistant: true
permit_join: false
mqtt:
  server: xxxxxxxxx1883
  user: xxxxxx
  password: xxxxxxxx
  base_topic: zigbee2mqtt
serial:
  port: >-
    /dev/serial/by-id/usb-dresden_elektronik_ingenieurtechnik_GmbH_ConBee_II_DE2439063-if00
advanced:
  log_level: warn
  pan_id: 6754
  channel: 11
  network_key:
    - 1
    - 3
    - 5
    - 7
    - 9
    - 11
    - 13
    - 15
    - 0
    - 2
    - 4
    - 6
    - 8
    - 10
    - 12
    - 13
  availability_blocklist: []
  availability_passlist: []
device_options: {}
blocklist: []
passlist: []
queue: {}
frontend:
  port: 8099
experimental: {}
socat:
  enabled: false
  master: pty,raw,echo=0,link=/tmp/ttyZ2M,mode=777
  slave: tcp-listen:8485,keepalive,nodelay,reuseaddr,keepidle=1,keepintvl=1,keepcnt=5
  options: '-d -d'
  log: false
```

**Running platform**
```
core-2021.6.6
supervisor-2021.06.6
Operating System: Ubuntu 21.04
Conbee 2 USB stick
Virtual Box 6.1
```

The Conbee 2 USB stick is correctly map and recognized by HA
![Screenshot from 2021-07-09 11-02-35](https://user-images.githubusercontent.com/86019626/125068867-7f021280-e0a5-11eb-9c2b-3a23a4a1f601.png)

**Log**
```
Zigbee2MQTT:error 2021-07-09 12:56:18: Error while starting zigbee-herdsman
Zigbee2MQTT:error 2021-07-09 12:56:18: Failed to start zigbee
Zigbee2MQTT:error 2021-07-09 12:56:18: Check https://www.zigbee2mqtt.io/information/FAQ.html#help-zigbee2mqtt-fails-to-start for possible solutions
Zigbee2MQTT:error 2021-07-09 12:56:18: Exiting...
Zigbee2MQTT:error 2021-07-09 12:56:18: Error: Failed to connect to the adapter (Error: SRSP - SYS - ping after 6000ms)
    at ZStackAdapter.<anonymous> (/app/node_modules/zigbee-herdsman/dist/adapter/z-stack/adapter/zStackAdapter.js:93:31)
    at Generator.throw (<anonymous>)
    at rejected (/app/node_modules/zigbee-herdsman/dist/adapter/z-stack/adapter/zStackAdapter.js:25:65)
npm ERR! code ELIFECYCLE
npm ERR! errno 1
npm ERR! zigbee2mqtt@1.20.0 start: `node index.js`
npm ERR! Exit status 1
npm ERR! 
npm ERR! Failed at the zigbee2mqtt@1.20.0 start script.
npm ERR! This is probably not a problem with npm. There is likely additional logging output above.
npm ERR! A complete log of this run can be found in:
npm ERR!     /root/.npm/_logs/2021-07-09T10_56_19_084Z-debug.log
[12:56:19] INFO: Handing over control to Zigbee2mqtt Core ...
> zigbee2mqtt@1.20.0 start /app
> node index.js
```

any idea how to fix this?
tks
