### ISSUE TITLE
Fresh install of Zigbee2MQTT won't connect to fresh install of Mosquitto

### ISSUE THREAD

**Issue by markheloking** [zigbee2mqtt/hassio-zigbee2mqtt#156]
**Description of problem:**
Freshly installed Mosquitto add-on, freshly installed Zigbee2MQTT add-on, followed tutorial from youtube: https://www.youtube.com/watch?v=-YeObwEZqL4

It seems that the Zigbee2MQTT add-on does connect to the MQTT broker, but then the Zigbee2mqtt Core doesn't for some reason as it's only causing socket errors.

**Zigbee2mqtt add-on version (if edge, please report commit hash):**
```
> zigbee2mqtt@1.20.0 start /app
```

**Your entire configuration from the frontend (with sensitive fields redacted)**:
```
data_path: /config/zigbee2mqtt
external_converters: []
devices: devices.yaml
groups: groups.yaml
homeassistant: true
permit_join: false
mqtt:
  base_topic: zigbee2mqtt
  server: mqtt://core-mosquitto:1883
  user: mqtt_user
  password: mqtt_pass
serial:
  port: >-
    /dev/serial/by-id/usb-Silicon_Labs_slae.sh_cc2652rb_stick_-_slaesh_s_iot_stuff_00_12_4B_00_23_90_DB_F7-if00-port0
advanced:
  log_level: warn
  pan_id: 6754
  channel: 11
  network_key: [*network key snipped*]
  availability_blocklist: []
  availability_passlist: []
device_options: {}
blocklist: []
passlist: []
queue: {}
frontend:
  port: 8099
experimental:
  new_api: true
socat:
  enabled: false
  master: pty,raw,echo=0,link=/tmp/ttyZ2M,mode=777
  slave: tcp-listen:8485,keepalive,nodelay,reuseaddr,keepidle=1,keepintvl=1,keepcnt=5
  options: '-d -d'
  log: false
```

**Running platform (details from Suypervisor > System)**
```
Core: core-2021.7.4
Supervisor: supervisor-2021.06.8
Operating System: Home Assistant OS 6.1
```

**Your logs from Home Assistant Supervisor**
```
[s6-init] making user provided files available at /var/run/s6/etc...exited 0.
[s6-init] ensuring user provided files have correct perms...exited 0.
[fix-attrs.d] applying ownership & permissions fixes...
[fix-attrs.d] done.
[cont-init.d] executing container initialization scripts...
[cont-init.d] socat.sh: executing... 
[17:21:58] INFO: Socat not enabled, marking service as down
[cont-init.d] socat.sh: exited 0.
[cont-init.d] zigbee2mqtt.sh: executing... 
[17:22:00] INFO: MQTT available, fetching server detail ...
[17:22:01] INFO: Previous config file found, checking backup
[17:22:01] INFO: Creating backup config in '/config/zigbee2mqtt/.configuration.yaml.bk'
[17:22:02] INFO: Adjusting Zigbee2mqtt core yaml config with add-on quirks ...
[cont-init.d] zigbee2mqtt.sh: exited 0.
[cont-init.d] done.
[services.d] starting services
[services.d] done.
[17:22:04] INFO: Handing over control to Zigbee2mqtt Core ...
> zigbee2mqtt@1.20.0 start /app
> node index.js
Zigbee2MQTT:error 2021-08-01 17:22:36: Not connected to MQTT server!
Zigbee2MQTT:error 2021-08-01 17:22:46: Not connected to MQTT server!
...
```

**Mosquitto add-on version (if edge, please report commit hash):**
```
Current version: 6.0.1
```

**Your entire configuration from the frontend (with sensitive fields redacted)**:
```
logins: []
customize:
  active: false
  folder: mosquitto
certfile: fullchain.pem
keyfile: privkey.pem
require_certificate: false
anonymous: true
```

**Your logs from Home Assistant Supervisor**
```
[s6-init] making user provided files available at /var/run/s6/etc...exited 0.
[s6-init] ensuring user provided files have correct perms...exited 0.
[fix-attrs.d] applying ownership & permissions fixes...
[fix-attrs.d] done.
[cont-init.d] executing container initialization scripts...
[cont-init.d] mosquitto.sh: executing... 
[17:26:14] INFO: SSL is not enabled
[cont-init.d] mosquitto.sh: exited 0.
[cont-init.d] nginx.sh: executing... 
[cont-init.d] nginx.sh: exited 0.
[cont-init.d] done.
[services.d] starting services
[services.d] done.
[17:26:16] INFO: Starting NGINX for authentication handling...
[17:26:17] INFO: Starting mosquitto MQTT broker...
1627831577: mosquitto version 1.6.12 starting
1627831577: |-- *** auth-plug: startup
[17:26:19] INFO: Successfully send discovery information to Home Assistant.
[17:26:20] INFO: Successfully send service information to the Supervisor.
1627831577: Config loaded from /etc/mosquitto/mosquitto.conf.
1627831577: Loading plugin: /usr/share/mosquitto/auth-plug.so
1627831577:  ├── Username/password checking enabled.
1627831577:  ├── TLS-PSK checking enabled.
1627831577:  └── Extended authentication not enabled.
1627831577: Opening ipv4 listen socket on port 1883.
1627831577: Opening ipv6 listen socket on port 1883.
1627831577: Opening websockets listen socket on port 1884.
1627831577: Warning: Mosquitto should not be run as root/administrator.
1627831577: mosquitto version 1.6.12 running
1627831577: New connection from 127.0.0.1 on port 1883.
1627831577: Socket error on client <unknown>, disconnecting.
1627831577: New connection from 172.30.33.2 on port 1883.
401: Unauthorized1627831578: Socket error on client <unknown>, disconnecting.
1627831579: New connection from 172.30.33.2 on port 1883.
1627831579: Socket error on client <unknown>, disconnecting.
1627831580: New connection from 172.30.33.2 on port 1883.
...
```

**Comment by markheloking** [comment]
May be related to https://github.com/home-assistant/addons/issues/2053. It looks like it starts normally after changing to Mosquitto config:

```
logins:
  - username: mqtt_user
    password: mqtt_pass
customize:
  active: false
  folder: mosquitto
certfile: fullchain.pem
keyfile: privkey.pem
require_certificate: false
anonymous: true
```
