### ISSUE TITLE
Failed to start zigbee - Table length not divisible by entry length

### ISSUE THREAD

**Issue by Amiyah14** [zigbee2mqtt/hassio-zigbee2mqtt#163]
**Description of problem:**

Happened after reboot of whole server. Reinstall didnt help. Same problem with Edge Version

**Zigbee2mqtt add-on version (if edge, please report commit hash):**
```
> zigbee2mqtt@1.21.0 start
```

**Your entire configuration from the frontend (with sensitive fields redacted)**:
```
data_path: /config/zigbee2mqtt
external_converters: []
devices: devices.yaml
groups: groups.yaml
homeassistant: true
permit_join: false
mqtt:
  base_topic: zigbee2mqtt
  server: mqtt://***
serial:
  port: /dev/ttyACM0
  disable_led: true
advanced:
  log_level: warn
  pan_id: 6754
  channel: 11
  network_key:
    - 1
    - 3
    - 5
    - 7
    - 9
    - 11
    - 13
    - 15
    - 0
    - 2
    - 4
    - 6
    - 8
    - 10
    - 12
    - 13
  availability_blocklist: []
  availability_passlist: []
device_options: {}
blocklist: []
passlist: []
queue: {}
frontend:
  port: 8099
experimental:
  new_api: true
socat:
  enabled: false
  master: pty,raw,echo=0,link=/tmp/ttyZ2M,mode=777
  slave: tcp-listen:8485,keepalive,nodelay,reuseaddr,keepidle=1,keepintvl=1,keepcnt=5
  options: '-d -d'
  log: true
zigbee_herdsman_debug: false

```

**Running platform (details from Suypervisor > System)**
```
Core: core-2021.8.4
Supervisor: supervisor-2021.06.8
Operating System: Debian GNU/Linux 10 (buster)
```

**Your logs from Home Assistant Supervisor**
```
[12:21:01] INFO: Handing over control to Zigbee2mqtt Core ...
> zigbee2mqtt@1.21.0 start
> node index.js
Zigbee2MQTT:error 2021-08-08 12:21:04: Error while starting zigbee-herdsman
Zigbee2MQTT:error 2021-08-08 12:21:04: Failed to start zigbee
Zigbee2MQTT:error 2021-08-08 12:21:04: Check https://www.zigbee2mqtt.io/information/FAQ.html#help-zigbee2mqtt-fails-to-start for possible solutions
Zigbee2MQTT:error 2021-08-08 12:21:04: Exiting...
Zigbee2MQTT:error 2021-08-08 12:21:04: Error: Table length not divisible by entry length (alignment=aligned, data_length=253, entry_length=12)
    at Table.build (/app/node_modules/zigbee-herdsman/src/adapter/z-stack/structs/table.ts:181:23)
    at addressManagerTable (/app/node_modules/zigbee-herdsman/src/adapter/z-stack/structs/entries/address-manager-table.ts:20:19)
    at AdapterNvMemory.readItem (/app/node_modules/zigbee-herdsman/src/adapter/z-stack/adapter/adapter-nv-memory.ts:73:21)
    at AdapterBackup.createBackup (/app/node_modules/zigbee-herdsman/src/adapter/z-stack/adapter/adapter-backup.ts:93:37)
    at Controller.backup (/app/node_modules/zigbee-herdsman/src/controller/controller.ts:306:28)
    at Controller.start (/app/node_modules/zigbee-herdsman/src/controller/controller.ts:158:13)
    at Zigbee.start (/app/lib/zigbee.js:67:27)
    at Controller.start (/app/lib/controller.js:106:27)
    at start (/app/index.js:94:5)
[12:21:04] INFO: Handing over control to Zigbee2mqtt Core ...
> zigbee2mqtt@1.21.0 start
> node index.js
Zigbee2MQTT:error 2021-08-08 12:21:07: Error while starting zigbee-herdsman
Zigbee2MQTT:error 2021-08-08 12:21:07: Failed to start zigbee
Zigbee2MQTT:error 2021-08-08 12:21:07: Check https://www.zigbee2mqtt.io/information/FAQ.html#help-zigbee2mqtt-fails-to-start for possible solutions
Zigbee2MQTT:error 2021-08-08 12:21:07: Exiting...
Zigbee2MQTT:error 2021-08-08 12:21:07: Error: Table length not divisible by entry length (alignment=aligned, data_length=253, entry_length=12)
    at Table.build (/app/node_modules/zigbee-herdsman/src/adapter/z-stack/structs/table.ts:181:23)
    at addressManagerTable (/app/node_modules/zigbee-herdsman/src/adapter/z-stack/structs/entries/address-manager-table.ts:20:19)
    at AdapterNvMemory.readItem (/app/node_modules/zigbee-herdsman/src/adapter/z-stack/adapter/adapter-nv-memory.ts:73:21)
    at AdapterBackup.createBackup (/app/node_modules/zigbee-herdsman/src/adapter/z-stack/adapter/adapter-backup.ts:93:37)
    at Controller.backup (/app/node_modules/zigbee-herdsman/src/controller/controller.ts:306:28)
    at Controller.start (/app/node_modules/zigbee-herdsman/src/controller/controller.ts:158:13)
    at Zigbee.start (/app/lib/zigbee.js:67:27)
    at Controller.start (/app/lib/controller.js:106:27)
    at start (/app/index.js:94:5)
[12:21:07] INFO: Handing over control to Zigbee2mqtt Core ...
> zigbee2mqtt@1.21.0 start
> node index.js
```
