### ISSUE TITLE
rtscts config on Home Assistant disappears

### ISSUE THREAD

**Issue by duhow** [zigbee2mqtt/hassio-zigbee2mqtt#173]
**Description of problem:**
Option `rtscts` disappears from Home Assistant when saving, so next configuration editing removes this check.

**Zigbee2mqtt add-on version (if edge, please report commit hash):**
```
zigbee2mqtt@1.21.0 start
Addon: 1.21.0-4
```

**Your entire configuration from the frontend (with sensitive fields redacted)**:
```yaml
data_path: /config/zigbee2mqtt
external_converters: []
devices: devices.yaml
groups: groups.yaml
homeassistant: true
permit_join: true
mqtt:
  base_topic: zigbee2mqtt_cc2530
serial:
  port: tcp://192.168.10.21:6638
advanced:
  log_level: info
  pan_id: 6754
  channel: 1
  rtscts: false # <<< this gets removed after saving
  network_key: REDACTED
  availability_blocklist: []
  availability_passlist: []
device_options: {}
blocklist: []
passlist: []
queue: {}
frontend:
  port: 8099
experimental: {}
```

**Running platform (details from Suypervisor > System)**
```
Core: core-2021.8.8
Supervisor: supervisor-2021.06.8
Operating System: HassOS 6.2
```
