### ISSUE TITLE
Cover TS130F inverted state

### ISSUE THREAD

**Issue by Jens-Wymeersch** [zigbee2mqtt/hassio-zigbee2mqtt#174]
**Description of problem:**

The state of the cover is **inverted**. Meaning, when the state within Z2M/HA indicates that the cover is closed, it is actually open and vice versa. Also on the blacklight, high gives no light whereas low is full light.
In Koen's document, https://www.zigbee2mqtt.io/devices/TS130F.html, it states there is an invert_cover option which is not present in the addon. 
I've tried to sort out the problem using calibration, reverse_motor option, but i'm not able to fix it.

**Zigbee2mqtt add-on version (if edge, please report commit hash):**
```
zigbee2mqtt@1.21.0-4  start /app
```

**Your entire configuration from the frontend (with sensitive fields redacted)**:
```
data_path: /config/zigbee2mqtt
external_converters: []
devices: devices.yaml
groups: groups.yaml
homeassistant: true
permit_join: false
mqtt:
  base_topic: zigbee2mqtt
  server: mqtt://XX.YY.ZZ.UU:1883
  user: User
  password: PW
serial:
  port: /dev/ttyUSB0
advanced:
  log_level: warn
  pan_id: 6754
  rtscts: false
  channel: 20
  network_key:
    - 1
    - 3
    - 5
    - 7
    - 9
    - 11
    - 13
    - 15
    - 0
    - 2
    - 4
    - 6
    - 8
    - 10
    - 12
    - 13
  availability_blocklist: []
  availability_passlist: []
device_options: {}
blocklist: []
passlist: []
queue: {}
frontend:
  port: 8099
experimental: {}
socat:
  enabled: false
  master: pty,raw,echo=0,link=/tmp/ttyZ2M,mode=777
  slave: tcp-listen:8485,keepalive,nodelay,reuseaddr,keepidle=1,keepintvl=1,keepcnt=5
  options: '-d -d'
  log: false

```

**Running platform (details from Suypervisor > System)**
```
core-2021.8.8
supervisor-2021.06.8
```

**Your logs from Home Assistant Supervisor**
```
NA
```
