### ISSUE TITLE
addon stopped updating through supervisor dashboard

### ISSUE THREAD

**Issue by darkenbula** [zigbee2mqtt/hassio-zigbee2mqtt#186]
**Description of problem:**
zigbee2mqtt has stopped showing updates available in the supervisor menu. All other addons continue to update fine. I'm stuck on version 1.18-1

**Zigbee2mqtt add-on version (if edge, please report commit hash):**
Current version: 1.18.1-1 

**Your entire configuration from the frontend (with sensitive fields redacted)**:
```
data_path: /share/zigbee2mqtt
external_converters: []
devices: devices.yaml
groups: groups.yaml
homeassistant: true
permit_join: true
mqtt:
  base_topic: zigbee2mqtt
  server: mqtt://172.17.0.1
  user: zigbee
  password: vqPs7Rubc7GwdNWcDtYu
serial:
  port: /dev/ttyUSB0
advanced:
  pan_id: 6769
  channel: 11
  rtscts: false
  network_key:
    - 1
    - 3
    - 5
    - 7
    - 9
    - 11
    - 13
    - 15
    - 0
    - 2
    - 4
    - 6
    - 8
    - 10
    - 12
    - 13
  availability_blocklist: []
  availability_passlist: []
device_options: {}
blocklist: []
passlist: []
queue: {}
frontend:
  port: 8099
experimental:
  new_api: true
socat:
  enabled: false
  master: pty,raw,echo=0,link=/dev/ttyZ2M,mode=777
  slave: tcp-listen:8485,keepalive,nodelay,reuseaddr,keepidle=1,keepintvl=1,keepcnt=5
  restartdelay: 1
  initialdelay: 1
  options: '-d -d'
  log: false
```

**Running platform (details from Suypervisor > System)**
```
// Example
Core: core-2021.9.5
Supervisor: supervisor-2021.09.0
Operating System: Home Assistant OS 6.2
```

**Your logs from Home Assistant Supervisor**
```
// Your logs here
```
