### ISSUE TITLE
Door Sensor flips when restarting Home Assistant Core

### ISSUE THREAD

**Issue by stefangries** [zigbee2mqtt/hassio-zigbee2mqtt#187]
**Description of problem:**
I use an Aqara Door Sensor (MCCGQ11LM) and count how often the door was closed in Home Assistant using the history_stats component. 

So my door is open 99% of the time and only closed very briefly a few times a day.

If I restart Home Assistant, the previous state of the sensor ("Door open"), which is still correct, is not retained. Instead, the sensor is initialised with "door closed" and changes to the correct status "open" after 2-5 seconds.

Restarting the core thus corrupts the count of my history_stats. I think this is a bug, because the sensor in Home Assistant changes the state, although this is not correct. 

**Zigbee2mqtt add-on version (if edge, please report commit hash):**
`zigbee2mqtt@1.21.1-1
`

**Your entire configuration from the frontend (with sensitive fields redacted)**:
```
sensor:
  - platform: history_stats
    name: Doorsensor FLIPS 48h
    entity_id: binary_sensor.doorsensor_contact
    state: 'off'
    type: count
    start: '{{ as_timestamp(now())-172800 }}'
    end: '{{ now() }}'
```

**Running platform**
```
core-2021.9.6
supervisor-2021.09.0
Home Assistant OS 6.3
```
