### ISSUE TITLE
Possibility to expose external the fronted from addon installation 

### ISSUE THREAD

**Issue by michelebossa** [zigbee2mqtt/hassio-zigbee2mqtt#192]
**Description of problem:**
Hi,
I'd like it to have the possibility to use the fronted page without to use ingress functionality. (keept boot way it will the best )

I suppose we need to have into container to exposing of port 8099
![image](https://user-images.githubusercontent.com/38975058/134678766-846c0df0-642f-458a-ae61-45d2d9a80a15.png)

into config file maybe this it is the point to be enanched.

![image](https://user-images.githubusercontent.com/38975058/134678946-fbf9383b-26c7-40d6-a95f-d59877cf1ef1.png)

There is the possibility to add this request?

**Zigbee2mqtt add-on version (if edge, please report commit hash):**
Current version: 1.21.1-1

**Your entire configuration from the frontend (with sensitive fields redacted)**:
```
data_path: /share/zigbee2mqtt
external_converters: []
devices: devices.yaml
groups: groups.yaml
homeassistant: true
permit_join: false
mqtt:
  base_topic: zigbee2mqtt
  server: mqtt://core-mosquitto
  user: xxxxxxx
  password: xxxxxx
serial:
  port: /dev/ttyUSB0
advanced:
  report: true
  rtscts: false
  log_level: info
  pan_id: 6754
  channel: 11
  last_seen: epoch
  network_key:
    - 1
    - 3
    - 5
    - 7
    - 9
    - 11
    - 13
    - 15
    - 0
    - 2
    - 4
    - 6
    - 8
    - 10
    - 12
    - 13
  availability_blocklist: []
  availability_passlist: []
device_options: {}
blocklist: []
passlist: []
queue: {}
frontend:
  port: 8099
experimental: {}
socat:
  enabled: false
  master: pty,raw,echo=0,link=/dev/ttyZ2M,mode=777
  slave: tcp-listen:8485,keepalive,nodelay,reuseaddr,keepidle=1,keepintvl=1,keepcnt=5
  options: '-d -d'
  log: false
```

**Running platform (details from Suypervisor > System)**
```
// Example
Core: core-2021.9.7
Supervisor: supervisor-2021.09.0
Operating System: Raspbian GNU/Linux 10 (buster)
```

**Your logs from Home Assistant Supervisor**
```
 
```
