### ISSUE TITLE
Sensors unavailable

### ISSUE THREAD

**Issue by thommycgn** [zigbee2mqtt/hassio-zigbee2mqtt#202]
**Description of problem:**
I'm using the CC2531 Stick (on a USB extension cable) with Z-Stack_Home_1.2 (source_routing) on Home Assistant. 
I have several Xiaomi MiJia temperature & humidity sensor (WSDCGQ01LM) in use. After some time, the sensors are displayed as **unavailable** in Home Assistant. Various Zigbee lamps and switches I use still work. Only the temperature sensors are unavailable.
Only restarting Zigbee2mqtt in Supervisor can fix the problem for a while.

**Zigbee2mqtt add-on version (if edge, please report commit hash):**
```
Current version: 1.21.2-1 
```

**Your entire configuration from the frontend (with sensitive fields redacted)**:
```
data_path: /config/zigbee2mqtt
external_converters: []
devices: devices.yaml
groups: groups.yaml
homeassistant: true
permit_join: false
mqtt:
  base_topic: zigbee2mqtt
serial:
  port: /dev/ttyACM0
advanced:
  log_level: warn
  pan_id: 6754
  channel: 11
  network_key:
    - 1
    - 3
    - 5
    - 7
    - 9
    - 11
    - 13
    - 15
    - 0
    - 2
    - 4
    - 6
    - 8
    - 10
    - 12
    - 13
  availability_blocklist: []
  availability_passlist: []
  availability_timeout: 60
device_options: {}
blocklist: []
passlist: []
queue: {}
frontend:
  port: 8099
experimental: {}
socat:
  enabled: false
  master: pty,raw,echo=0,link=/tmp/ttyZ2M,mode=777
  slave: tcp-listen:8485,keepalive,nodelay,reuseaddr,keepidle=1,keepintvl=1,keepcnt=5
  options: '-d -d'
  log: false

```

**Running platform (details from Suypervisor > System)**
```
Core: core-2021.9.6
Supervisor: supervisor-2021.09.6
Operating System: HassOS 6.3
```
