### ISSUE TITLE
Home Assistant can not track statistics from zigbee devices

### ISSUE THREAD

**Issue by chrisilan** [zigbee2mqtt/hassio-zigbee2mqtt#205]
Hi, 
I try to use the new "Statistics Graph Card" in Home Assistant in combination with several Xiaomi Temperature sensors.
But none of my zigbee devices are available as statistics.
I searched in Home Assistant documentary and I find this hint here https://www.home-assistant.io/more-info/statistics/ :

"You’re configuring a statistic but you couldn’t find your source in the dropdown? That’s caused by a bug in the integration providing the entity. Integrations need to configure their entities correctly so Home Assistant knows that we need to track statistics for it and how.
Open an issue with the author of the integration and link them to https://developers.home-assistant.io/docs/core/entity/sensor#long-term-statistics."

**Zigbee2mqtt add-on version (if edge, please report commit hash):**
```
Current version: 1.18.1-1 
```

**Your entire configuration from the frontend (with sensitive fields redacted)**:
```
data_path: /share/zigbee2mqtt
external_converters: []
devices: devices.yaml
groups: groups.yaml
homeassistant: true
permit_join: false
mqtt:
  base_topic: zigbee2mqtt
serial:
  port: >-
    /dev/serial/by-id/usb-Silicon_Labs_slae.sh_cc2652rb_stick_-_slaesh_s_iot_stuff_00_12_4B_00_21_CB_FE_56-if00-port0
  disable_led: false
advanced:
  log_level: debug
  pan_id: 6755
  channel: 11
  network_key:
    - 1
    - 3
    - 5
    - 7
    - 9
    - 11
    - 13
    - 15
    - 0
    - 2
    - 4
    - 6
    - 8
    - 10
    - 12
    - 13
  availability_blocklist: []
  availability_passlist: []
device_options: {}
blocklist: []
passlist: []
queue: {}
frontend:
  port: 8099
experimental:
  new_api: true
socat:
  enabled: false
  master: pty,raw,echo=0,link=/dev/ttyZ2M,mode=777
  slave: tcp-listen:8485,keepalive,nodelay,reuseaddr,keepidle=1,keepintvl=1,keepcnt=5
  options: '-d -d'
  log: true
  restartdelay: 1
  initialdelay: 1
  log_level: debug

```

**Running platform (details from Suypervisor > System)**
```
// Example
Core: core-2021.10.4
Supervisor: supervisor-2021.10.0
Operating System: Home Assistant OS 6.5
```

I hope anyone can help and the question makes sense.
