### ISSUE TITLE
Can't change text in icon row in fronend of add-on.

### ISSUE THREAD

**Issue by DJTerentjev** [zigbee2mqtt/hassio-zigbee2mqtt#207]
**Description of problem:**
Can't change text in icon row in fronend of add-on. From the begin row icon was empty, then i put the wrong name of file. Now I can't change text in icon row. Can't delete or type anything.
Same with Debounce row. I change once to "1" and now can't modify or delete.

**Zigbee2mqtt add-on version (if edge, please report commit hash):**
```
// Example:
// > zigbee2mqtt@1.21.1-1 start /app
```

**Your entire configuration from the frontend (with sensitive fields redacted)**:
```
data_path: /share/zigbee2mqtt
external_converters:
  - INA3321_Alarm.js
  - Pressure_temp.js
  - avatto.js
  - SSM-U02.js
  - TS0001.js
  - UART_TV.js
devices: devices.yaml
groups: groups.yaml
homeassistant: true
permit_join: false
mqtt:
  base_topic: zigbee2mqtt
  server: mqtt://core-mosquitto
  user: DJTerentjev
  password: nat@0611
serial:
  port: /dev/serial/by-id/usb-Texas_Instruments_CC2538_USB_CDC-if00
advanced:
  log_level: debug
  pan_id: 6755
  channel: 26
  network_key:
    - 1
    - 3
    - 5
    - 7
    - 9
    - 11
    - 13
    - 15
    - 0
    - 2
    - 4
    - 6
    - 8
    - 10
    - 12
    - 13
  availability_blocklist: []
  availability_passlist: []
  last_seen: ISO_8601
device_options: {}
blocklist: []
passlist: []
queue: {}
frontend:
  port: 8099
experimental:
  new_api: true
socat:
  enabled: false
  master: pty,raw,echo=0,link=/dev/ttyZ2M,mode=777
  slave: tcp-listen:8485,keepalive,nodelay,reuseaddr,keepidle=1,keepintvl=1,keepcnt=5
  options: '-d -d'
  log: false
  restartdelay: 1
  initialdelay: 1
```

**Running platform (details from Suypervisor > System)**
```
// Example
Core: core-2021.9.7
Supervisor: supervisor-2021.10.0
Operating System: Raspbian GNU/Linux 10 (buster)
```

**Your logs from Home Assistant Supervisor**
```
// I don't have any errors in the log
![Err1](https://user-images.githubusercontent.com/1267473/137402180-be32aad1-1896-4266-add4-831dc843549c.jpg)
![Err2](https://user-images.githubusercontent.com/1267473/137402174-cf38c6f2-6f44-44fe-92ac-b8ab4d7a9547.jpg)


```
