### ISSUE TITLE
HomeAssistant integration doesn't work

### ISSUE THREAD

**Issue by sergimola** [zigbee2mqtt/hassio-zigbee2mqtt#214]
**Description of problem:**
When I start zigbee2mqtt I see this error in the log and the integration with Home Assistant doesn't work

```
Zigbee2MQTT:error 2021-10-22 17:15:31: Failed to call 'HomeAssistant' 'start' (AssertionError [ERR_ASSERTION]: The expression evaluated to a falsy value:,
  (0, assert_1.default)(allowed.includes(s)),
    at /app/lib/extension/homeassistant.ts:393:51,
    at Array.forEach (<anonymous>),
    at HomeAssistant.exposeToConfig (/app/lib/extension/homeassistant.ts:393:30),
    at HomeAssistant.populateMapping (/app/lib/extension/homeassistant.ts:649:54),
    at HomeAssistant.start (/app/lib/extension/homeassistant.ts:67:14),
    at processTicksAndRejections (internal/process/task_queues.js:95:5),
    at Controller.callExtensionMethod (/app/lib/controller.js:427:58),
    at Controller.start (/app/lib/controller.js:184:9),
    at start (/app/index.js:95:5))
```

**Zigbee2mqtt add-on version (if edge, please report commit hash):**
```
1.21.2 commit: 4492212
```

**Your entire configuration from the frontend (with sensitive fields redacted)**:
```
homeassistant: true
permit_join: true
mqtt:
  base_topic: zigbee2mqtt
  server: mqtt://server
serial:
  port: /dev/ttyUSB0
frontend:
  port: 8880
advanced:
  pan_id: 49783
  homeassistant_legacy_entity_attributes: false
  legacy_api: false
  log_level: debug
devices:
  '0x00158d000245f43d':
    friendly_name: XTHPS_2
device_options:
  legacy: false

```

**Running platform (details from Suypervisor > System)**
```
1.21.2 commit: 4492212 running in Docker
```

**Your logs from Home Assistant Supervisor**
```
Zigbee2MQTT:error 2021-10-22 17:15:31: Failed to call 'HomeAssistant' 'start' (AssertionError [ERR_ASSERTION]: The expression evaluated to a falsy value:,
  (0, assert_1.default)(allowed.includes(s)),
    at /app/lib/extension/homeassistant.ts:393:51,
    at Array.forEach (<anonymous>),
    at HomeAssistant.exposeToConfig (/app/lib/extension/homeassistant.ts:393:30),
    at HomeAssistant.populateMapping (/app/lib/extension/homeassistant.ts:649:54),
    at HomeAssistant.start (/app/lib/extension/homeassistant.ts:67:14),
    at processTicksAndRejections (internal/process/task_queues.js:95:5),
    at Controller.callExtensionMethod (/app/lib/controller.js:427:58),
    at Controller.start (/app/lib/controller.js:184:9),
    at start (/app/index.js:95:5))
```
