### ISSUE TITLE
v1.22.0-2: availability configuration not available

### ISSUE THREAD

**Issue by cmorlok** [zigbee2mqtt/hassio-zigbee2mqtt#225]
**Description of problem:**
Available configuration is not available, even though the change log says

> * Fix availability configuration

The new version essentially changes nothing, the configuration is only available in ege:
https://github.com/zigbee2mqtt/hassio-zigbee2mqtt/compare/v1.22.0-1...v1.22.0-2

**Zigbee2mqtt add-on version (if edge, please report commit hash):**
```
> zigbee2mqtt@1.22.0-2
```

**Your entire configuration from the frontend (with sensitive fields redacted)**:
```
data_path: /config/zigbee2mqtt
external_converters: []
devices: devices.yaml
groups: groups.yaml
homeassistant: true
permit_join: false
mqtt:
  base_topic: zigbee2mqtt
serial:
  port: /dev/ttyUSB0
advanced:
  log_level: debug
  pan_id: x
  channel: x
  network_key:
    - 1
  availability_blocklist: []
  availability_passlist: []
  rtscts: false
device_options: {}
blocklist: []
passlist: []
queue: {}
frontend:
  port: 8099
experimental:
  availability_new: true
socat:
  enabled: false
  master: pty,raw,echo=0,link=/tmp/ttyZ2M,mode=777
  slave: tcp-listen:8485,keepalive,nodelay,reuseaddr,keepidle=1,keepintvl=1,keepcnt=5
  options: '-d -d'
  log: false
availability: true
```

**Your logs from Home Assistant Supervisor**
```
21-11-02 16:29:45 WARNING (MainThread) [supervisor.addons.options] Unknown option 'availability_new' for Zigbee2mqtt (45df7312_zigbee2mqtt)
21-11-02 16:29:45 WARNING (MainThread) [supervisor.addons.options] Option 'availability' does not exist in the schema for Zigbee2mqtt (45df7312_zigbee2mqtt)
```
