### ISSUE TITLE
[supervisor.addons.options] Option 'ota' does not exist in the schema for Zigbee2mqtt / Feature Request

### ISSUE THREAD

**Issue by Arakon** [zigbee2mqtt/hassio-zigbee2mqtt#229]
**Description of problem:**
According to the [docs](https://www.zigbee2mqtt.io/guide/usage/ota_updates.html#automatic-checking-for-available-updates), ota updates should be configurable from the configuration yaml file in HA. However, this option does not seem valid, throwing the above error.

**Zigbee2mqtt add-on version (if edge, please report commit hash):**
```
1.22.0-2
```

**Your entire configuration from the frontend (with sensitive fields redacted)**:
```
data_path: /config/zigbee2mqtt
external_converters: []
devices: devices.yaml
groups: groups.yaml
homeassistant: true
permit_join: false
mqtt:
  base_topic: zigbee2mqtt
serial:
  port: /dev/ttyACM0
advanced:
  log_level: warn
  pan_id: *
  channel: 11
  network_key:
*
  availability_blocklist: []
  availability_passlist: []
  ikea_ota_use_test_url: false
device_options: {}
blocklist: []
passlist: []
queue: {}
frontend:
  port: 8099
experimental: {}
socat:
  enabled: false
  master: pty,raw,echo=0,link=/tmp/ttyZ2M,mode=777
  slave: tcp-listen:8485,keepalive,nodelay,reuseaddr,keepidle=1,keepintvl=1,keepcnt=5
  options: '-d -d'
  log: false
ota:
  disable_automatic_update_check: true
```

**Running platform (details from Suypervisor > System)**
```
Core: core-2021.11.0
Supervisor: supervisor-2021.10.8
Operating System: Armbian 21.08.3 Bullseye
```

**Your logs from Home Assistant Supervisor**
```
21-11-04 23:31:40 WARNING (MainThread) [supervisor.addons.options] Option 'ota' does not exist in the schema for Zigbee2mqtt (45df7312_zigbee2mqtt)
21-11-04 23:31:40 WARNING (MainThread) [supervisor.addons.options] Option 'ota' does not exist in the schema for Zigbee2mqtt (45df7312_zigbee2mqtt)
21-11-04 23:31:40 WARNING (MainThread) [supervisor.addons.options] Option 'ota' does not exist in the schema for Zigbee2mqtt (45df7312_zigbee2mqtt)
```
