### ISSUE TITLE
CC2531 adapter keeps removing itself when the zigbee2mqtt addon is started

### ISSUE THREAD

**Issue by mikepruett3** [zigbee2mqtt/hassio-zigbee2mqtt#231]
**Description of problem:**
My CC2531 adapter (sonoff) is removed after starting the zigbee2mqtt addon. I have tried several different USB (USB2 & USB3) ports on my server, and they all do the same thing. The CC2531 was flashed with the firmware from the zigbee2mqtt project.

All of this was working up until a few days ago.

**Zigbee2mqtt add-on version (if edge, please report commit hash):**
```
zigbee2mqtt@1.22.0-2
```

**Your entire configuration from the frontend (with sensitive fields redacted)**:
```
data_path: /config/zigbee2mqtt
external_converters:
  - ‎BA19-08027OMF-12CE26-1C100.js
devices: devices.yaml
groups: groups.yaml
homeassistant: true
permit_join: false
mqtt:
  base_topic: zigbee2mqtt
serial:
  port: /dev/ttyACM0
advanced:
  log_level: warn
  pan_id: 6754
  channel: 11
  network_key:[<redacted>]
  availability_blocklist: []
  availability_passlist: []
device_options: {}
blocklist: []
passlist: []
queue: {}
frontend:
  port: 8099
experimental: {}
socat:
  enabled: false
  master: pty,raw,echo=0,link=/tmp/ttyZ2M,mode=777
  slave: tcp-listen:8485,keepalive,nodelay,reuseaddr,keepidle=1,keepintvl=1,keepcnt=5
  options: '-d -d'
  log: false
```

**Running platform (details from Suypervisor > System)**
```
Core: core-2021.10.6
Supervisor: supervisor-2021.10.8
Operating System: Home Assistant OS 6.6
```

**Your logs from Home Assistant Supervisor**
```
21-11-05 10:37:07 INFO (MainThread) [supervisor.hardware.monitor] Detecting HardwareAction.REMOVE hardware /dev/ttyACM0 - /dev/serial/by-id/usb-Texas_Instruments_TI_CC2531_USB_CDC___0X00124B001CCC65C6-if00
21-11-05 10:37:07 INFO (MainThread) [supervisor.hardware.monitor] Detecting HardwareAction.REMOVE hardware /dev/bus/usb/004/002 - None
21-11-05 10:37:12 INFO (MainThread) [supervisor.hardware.monitor] Detecting HardwareAction.ADD hardware /dev/bus/usb/004/003 - None
21-11-05 10:37:12 INFO (MainThread) [supervisor.hardware.monitor] Detecting HardwareAction.ADD hardware /dev/ttyACM0 - /dev/serial/by-id/usb-Texas_Instruments_TI_CC2531_USB_CDC___0X00124B001CCC65C6-if00
21-11-05 10:37:30 INFO (MainThread) [supervisor.api.middleware.security] /network/info access from core_ssh
21-11-05 10:37:30 INFO (MainThread) [supervisor.api.middleware.security] /network/info access from core_ssh
21-11-05 10:37:30 INFO (MainThread) [supervisor.api.middleware.security] /host/info access from core_ssh
21-11-05 10:37:30 INFO (MainThread) [supervisor.api.middleware.security] /core/info access from core_ssh
21-11-05 10:38:40 INFO (MainThread) [supervisor.api.middleware.security] /network/info access from core_ssh
21-11-05 10:38:40 INFO (MainThread) [supervisor.api.middleware.security] /network/info access from core_ssh
21-11-05 10:38:40 INFO (MainThread) [supervisor.api.middleware.security] /host/info access from core_ssh
21-11-05 10:38:40 INFO (MainThread) [supervisor.api.middleware.security] /core/info access from core_ssh
21-11-05 10:42:57 INFO (SyncWorker_2) [supervisor.docker.interface] Cleaning addon_45df7312_zigbee2mqtt application
21-11-05 10:42:59 INFO (SyncWorker_2) [supervisor.docker.addon] Starting Docker add-on zigbee2mqtt/zigbee2mqtt-amd64 with version 1.22.0-2
21-11-05 10:43:09 INFO (MainThread) [supervisor.hardware.monitor] Detecting HardwareAction.REMOVE hardware /dev/ttyACM0 - /dev/serial/by-id/usb-Texas_Instruments_TI_CC2531_USB_CDC___0X00124B001CCC65C6-if00
21-11-05 10:43:09 INFO (MainThread) [supervisor.hardware.monitor] Detecting HardwareAction.REMOVE hardware /dev/bus/usb/004/003 - None
```
