### ISSUE TITLE
For battery powered device RH3052 power source appears as question mark.

### ISSUE THREAD

**Issue by DJTerentjev** [zigbee2mqtt/hassio-zigbee2mqtt#232]
**Description of problem:**
For specific battery device: Zigbee Model - RH3052 power source appears as question mark. 
I have several battery device and for them power source appears as battery, but only for this device it is question mark. 
Same time device provide remaining battery in %. I try to look at the z2m converters and everything looks same as other devices. 

**Zigbee2mqtt add-on version (if edge, please report commit hash):**
```
 zigbee2mqtt@1.22.0-2
```

```
data_path: /share/zigbee2mqtt
external_converters:
  - INA3321_Alarm.js
  - Pressure_temp.js
  - UART_TV.js
devices: devices.yaml
groups: groups.yaml
homeassistant: true
permit_join: false
mqtt:
  base_topic: zigbee2mqtt
  server: mqtt://core-mosquitto
  user: ****
  password: ****
serial:
  port: /dev/serial/by-id/usb-Texas_Instruments_CC2538_USB_CDC-if00
advanced:
  log_level: debug
  pan_id: ****
  channel: ***
  network_key:
    - 1
    - 3
    - 5
    - 7
    - 9
    - 11
    - 13
    - 15
    - 0
    - 2
    - 4
    - 6
    - 8
    - 10
    - 12
    - 13
  availability_blocklist: []
  availability_passlist: []
  last_seen: ISO_8601
device_options: {}
blocklist: []
passlist: []
queue: {}
frontend:
  port: 8099
experimental:
  new_api: true
socat:
  enabled: false
  master: pty,raw,echo=0,link=/dev/ttyZ2M,mode=777
  slave: tcp-listen:8485,keepalive,nodelay,reuseaddr,keepidle=1,keepintvl=1,keepcnt=5
  options: '-d -d'
  log: false
  restartdelay: 1
  initialdelay: 1
```

**Running platform (details from Suypervisor > System)**
```
Core: core-2021.9.7
Supervisor: supervisor-2021.10.8
Operating System: Raspbian GNU/Linux 10 (buster)
Docker version: 20.10.8 
```

**Your logs from Home Assistant Supervisor**
```
// Your logs here
```
