### ISSUE TITLE
Event state_changed trigger

### ISSUE THREAD

**Issue by DJTerentjev** [zigbee2mqtt/hassio-zigbee2mqtt#233]
**Description of problem:**
I was trying to use event state_changed trigger. 
Both _trigger.event.data.old_state.state_ and _trigger.event.data.new_state.state_ stays the same. Both values of _trigger.event.data.old_state.state_. It's affect only zigbee2mqtt switches. To check I tried with another (not zigbee2mqtt) switches and I received correct values.

**Zigbee2mqtt add-on version (if edge, please report commit hash):**
```
zigbee2mqtt@1.22.0-2
```

**Your entire configuration from the frontend (with sensitive fields redacted)**:
```
data_path: /share/zigbee2mqtt
external_converters:
  - INA3321_Alarm.js
  - Pressure_temp.js
  - UART_TV.js
devices: devices.yaml
groups: groups.yaml
homeassistant: true
permit_join: false
mqtt:
  base_topic: zigbee2mqtt
  server: mqtt://core-mosquitto
  user: ****
  password: ****
serial:
  port: /dev/serial/by-id/usb-Texas_Instruments_CC2538_USB_CDC-if00
advanced:
  log_level: debug
  pan_id: ****
  channel: ***
  network_key:
    - 1
    - 3
    - 5
    - 7
    - 9
    - 11
    - 13
    - 15
    - 0
    - 2
    - 4
    - 6
    - 8
    - 10
    - 12
    - 13
  availability_blocklist: []
  availability_passlist: []
  last_seen: ISO_8601
device_options: {}
blocklist: []
passlist: []
queue: {}
frontend:
  port: 8099
experimental:
  new_api: true
socat:
  enabled: false
  master: pty,raw,echo=0,link=/dev/ttyZ2M,mode=777
  slave: tcp-listen:8485,keepalive,nodelay,reuseaddr,keepidle=1,keepintvl=1,keepcnt=5
  options: '-d -d'
  log: false
  restartdelay: 1
  initialdelay: 1
```

**Running platform (details from Suypervisor > System)**
```
Core: core-2021.9.7
Supervisor: supervisor-2021.10.8
Operating System: Raspbian GNU/Linux 10 (buster)
Docker version: 20.10.8 
```

**Your logs from Home Assistant Supervisor**
```
// Your logs here
```
