### ISSUE TITLE
No device showed ufter pairing

### ISSUE THREAD

**Issue by smagedy** [zigbee2mqtt/hassio-zigbee2mqtt#252]
**Description of problem:**
No device's (ikea tradfri round and motion sensor) showed up after pairing. Only in mosquitto log but can't do anything with it. It is a fresh installation of HA. The next log is from mosquitto:
```
1639079941: New connection from 172.30.32.1 on port 1883.
{"result": "ok", "data": {}}1639079941: New client connected from 172.30.32.1 as 0up1geLm6w1Q2EM3kzmiXr (p1, c1, k60, u'mqtt-user').
```

**Zigbee2mqtt add-on version (if edge, please report commit hash):**

```
Zigbee2MQTT version
1.22.1-dev commit: d0195d0
Coordinator type
ConBee2/RaspBee2
Coordinator revision
0x26700700
Frontend version
0.6.59
```

**Your entire configuration from the frontend (with sensitive fields redacted)**:
```
data_path: /config/zigbee2mqtt
external_converters: []
devices: devices.yaml
groups: groups.yaml
homeassistant: true
permit_join: true
mqtt:
  base_topic: zigbee2mqtt
  user: mqtt-user
  password: *****
serial:
  port: /dev/ttyACM0
  adapter: deconz
advanced:
  log_level: warn
  pan_id: 6754
  channel: 11
  network_key:
    - 1
    - 3
    - 5
    - 7
    - 9
    - 11
    - 13
    - 15
    - 0
    - 2
    - 4
    - 6
    - 8
    - 10
    - 12
    - 13
  availability_blocklist: []
  availability_passlist: []
device_options: {}
blocklist: []
passlist: []
queue: {}
frontend:
  port: 8099
experimental: {}
availability: false
socat:
  enabled: false
  master: pty,raw,echo=0,link=/tmp/ttyZ2M,mode=777
  slave: tcp-listen:8485,keepalive,nodelay,reuseaddr,keepidle=1,keepintvl=1,keepcnt=5
  options: '-d -d'
  log: false
```

**Running platform (details from Suypervisor > System)**
```
core-2021.11.5
supervisor-2021.10.8
Home Assistant OS 6.6
```

**Your logs from Home Assistant Supervisor**
```
21-12-09 21:15:02 INFO (SyncWorker_3) [supervisor.docker.interface] Stopping addon_45df7312_zigbee2mqtt_edge application
21-12-09 21:15:04 INFO (SyncWorker_3) [supervisor.docker.interface] Cleaning addon_45df7312_zigbee2mqtt_edge application
21-12-09 21:15:04 INFO (SyncWorker_0) [supervisor.docker.addon] Starting Docker add-on zigbee2mqtt/zigbee2mqtt-edge-amd64 with version edge
21-12-09 21:15:09 INFO (MainThread) [supervisor.auth] Auth request from 'core_mosquitto' for 'mqtt-user'
21-12-09 21:15:10 INFO (MainThread) [supervisor.auth] Successful login for 'mqtt-user'
```
