### ISSUE TITLE
After a while zigbee2mqtt not connected to MQTT server!

### ISSUE THREAD

**Issue by Korte68** [zigbee2mqtt/hassio-zigbee2mqtt#268]
**Short description**

A few days ago connection lost to MQTT server. Restarting the add-on the connection working again for a while, then lost the connection again.

**Zigbee2mqtt add-on version (if edge, please report commit hash):**
```
zigbee2mqtt@1.18.1 start /app

```

**Your entire configuration from the frontend (with sensitive fields redacted)**:
```
data_path: /config/zigbee2mqtt
external_converters: []
devices: devices.yaml
groups: groups.yaml
homeassistant: true
permit_join: false
mqtt:
  base_topic: zigbee2mqtt
  server: mqtt://192.168.4.200:1883
  user: xxxx
  password: xxxx
serial:
  port: /dev/ttyUSB0
advanced:
  log_level: warn
  pan_id: 6754
  channel: 11
  network_key:
    - 1
    - 3
    - 5
    - 7
    - 9
    - 11
    - 13
    - 15
    - 0
    - 2
    - 4
    - 6
    - 8
    - 10
    - 12
    - 13
  availability_blocklist: []
  availability_passlist: []
device_options: {}
blocklist: []
passlist: []
queue: {}
frontend:
  port: 8099
experimental:
  new_api: true
socat:
  enabled: false
  master: pty,raw,echo=0,link=/tmp/ttyZ2M,mode=777
  slave: tcp-listen:8485,keepalive,nodelay,reuseaddr,keepidle=1,keepintvl=1,keepcnt=5
  options: '-d -d'
  log: false

```

**Running platform (details from Suypervisor > System)**
```
// Example
Core: core-2021.12.7
Supervisor: supervisor-2021.12.2
Operating System: Home Assistant OS 7.0
```

**Your logs from Home Assistant Supervisor**
```
Boot normally:
[s6-init] making user provided files available at /var/run/s6/etc...exited 0.
[s6-init] ensuring user provided files have correct perms...exited 0.
[fix-attrs.d] applying ownership & permissions fixes...
[fix-attrs.d] done.
[cont-init.d] executing container initialization scripts...
[cont-init.d] socat.sh: executing... 
[13:50:26] INFO: Socat not enabled, marking service as down
[cont-init.d] socat.sh: exited 0.
[cont-init.d] zigbee2mqtt.sh: executing... 
[13:50:27] INFO: MQTT available, fetching server detail ...
[13:50:27] INFO: Previous config file found, checking backup
[13:50:27] INFO: Creating backup config in '/config/zigbee2mqtt/.configuration.yaml.bk'
[13:50:28] INFO: Adjusting Zigbee2mqtt core yaml config with add-on quirks ...
[cont-init.d] zigbee2mqtt.sh: exited 0.
[cont-init.d] done.
[services.d] starting services
[services.d] done.
[13:50:29] INFO: Handing over control to Zigbee2mqtt Core ...
> zigbee2mqtt@1.18.1 start /app
> node index.js

Later:

error 2022-01-01 11:44:31: Not connected to MQTT server!
error 2022-01-01 11:45:30: Not connected to MQTT server!
error 2022-01-01 11:45:30: Cannot send message: topic: 'zigbee2mqtt/Szivattyú', payload: '{"current":0,"energy":3.21,"linkquality":57,"power":0,"power_outage_memory":"restore","state":"ON","voltage":231}
error 2022-01-01 11:45:30: Not connected to MQTT server!


```

**Comment by Bascht74** [comment]
I have the same problem after updating from v1.22.1-1 to v1.22.2-1.
After the restart I get this response: 

```
[s6-init] making user provided files available at /var/run/s6/etc...exited 0.
[s6-init] ensuring user provided files have correct perms...exited 0.
[fix-attrs.d] applying ownership & permissions fixes...
[fix-attrs.d] done.
[cont-init.d] executing container initialization scripts...
[cont-init.d] socat.sh: executing... 
[09:53:13] INFO: Socat not enabled, marking service as down
[cont-init.d] socat.sh: exited 0.
[cont-init.d] zigbee2mqtt.sh: executing... 
[09:53:14] INFO: MQTT available, fetching server detail ...
[09:53:14] INFO: Previous config file found, checking backup
[09:53:14] INFO: Creating backup config in '/config/zigbee2mqtt/.configuration.yaml.bk'
[09:53:14] INFO: Adjusting Zigbee2mqtt core yaml config with add-on quirks ...
[cont-init.d] zigbee2mqtt.sh: exited 0.
[cont-init.d] done.
[services.d] starting services
[services.d] done.
[09:53:15] INFO: Handing over control to Zigbee2mqtt Core ...
> zigbee2mqtt@1.22.2 start
> node index.js
CREATED DECONZ ADAPTER
Zigbee2MQTT:error 2022-01-07 09:53:23: Not connected to MQTT server!
Zigbee2MQTT:error 2022-01-07 09:53:23: Cannot send message: topic: 'zigbee2mqtt/Lampe_OG_Flur_Komode/availability', payload: 'online
Zigbee2MQTT:error 2022-01-07 09:53:46: Failed to configure 'Rauchmelder_Aussen_Schuppen (2)', attempt 1 (Error: Bind 0x0015bc003100bea0/35 genBasic from '0x00212effff0657d6/1' failed (Error: status: 140)
    at DeconzAdapter.bind (/app/node_modules/zigbee-herdsman/src/adapter/deconz/adapter/deconzAdapter.ts:753:19)
    at Endpoint.bind (/app/node_modules/zigbee-herdsman/src/controller/model/endpoint.ts:517:13)
    at Object.bind (/app/node_modules/zigbee-herdsman-converters/lib/reporting.js:33:9)
    at Object.configure (/app/node_modules/zigbee-herdsman-converters/devices/develco.js:165:13)
    at Configure.configure (/app/lib/extension/configure.ts:115:13))
Zigbee2MQTT:warn  2022-01-07 09:54:28: Failed to ping 'Lampe_EG_Wohnzimmer_Sideboard' (attempt 1/1, Read 0x001788010124504c/11 genBasic(["zclVersion"], {"timeout":10000,"disableResponse":false,"disableRecovery":true,"disableDefaultResponse":true,"direction":0,"srcEndpoint":null,"reservedBits":0,"manufacturerCode":null,"transactionSequenceNumber":null,"writeUndiv":false}) failed (no response received))
Zigbee2MQTT:error 2022-01-07 09:56:04: Failed to configure 'Rauchmelder_EG_Wohnzimmer', attempt 1 (Error: Bind 0x0015bc003100c740/35 genBasic from '0x00212effff0657d6/1' failed (Error: status: 140)
    at DeconzAdapter.bind (/app/node_modules/zigbee-herdsman/src/adapter/deconz/adapter/deconzAdapter.ts:753:19)
    at Endpoint.bind (/app/node_modules/zigbee-herdsman/src/controller/model/endpoint.ts:517:13)
    at Object.bind (/app/node_modules/zigbee-herdsman-converters/lib/reporting.js:33:9)
    at Object.configure (/app/node_modules/zigbee-herdsman-converters/devices/develco.js:165:13)
    at Configure.configure (/app/lib/extension/configure.ts:115:13))
Zigbee2MQTT:error 2022-01-07 09:56:47: Failed to configure 'Rauchmelder_OG_Flur', attempt 1 (Error: Bind 0x0015bc003100bae5/35 genBasic from '0x00212effff0657d6/1' failed (Error: status: 140)
    at DeconzAdapter.bind (/app/node_modules/zigbee-herdsman/src/adapter/deconz/adapter/deconzAdapter.ts:753:19)
    at Endpoint.bind (/app/node_modules/zigbee-herdsman/src/controller/model/endpoint.ts:517:13)
    at Object.bind (/app/node_modules/zigbee-herdsman-converters/lib/reporting.js:33:9)
    at Object.configure (/app/node_modules/zigbee-herdsman-converters/devices/develco.js:165:13)
    at Configure.configure (/app/lib/extension/configure.ts:115:13))
Zigbee2MQTT:error 2022-01-07 09:57:36: Failed to configure 'Rauchmelder_Aussen_Carport (3)', attempt 1 (Error: Bind 0x0015bc003100bb13/35 genBasic from '0x00212effff0657d6/1' failed (Error: status: 140)
    at DeconzAdapter.bind (/app/node_modules/zigbee-herdsman/src/adapter/deconz/adapter/deconzAdapter.ts:753:19)
    at Endpoint.bind (/app/node_modules/zigbee-herdsman/src/controller/model/endpoint.ts:517:13)
    at Object.bind (/app/node_modules/zigbee-herdsman-converters/lib/reporting.js:33:9)
    at Object.configure (/app/node_modules/zigbee-herdsman-converters/devices/develco.js:165:13)
    at Configure.configure (/app/lib/extension/configure.ts:115:13))
Zigbee2MQTT:error 2022-01-07 09:58:45: Failed to configure 'Rauchmelder_Aussen_Schuppen (2)', attempt 2 (Error: Bind 0x0015bc003100bea0/35 genBasic from '0x00212effff0657d6/1' failed (Error: status: 140)
    at DeconzAdapter.bind (/app/node_modules/zigbee-herdsman/src/adapter/deconz/adapter/deconzAdapter.ts:753:19)
    at Endpoint.bind (/app/node_modules/zigbee-herdsman/src/controller/model/endpoint.ts:517:13)
    at Object.bind (/app/node_modules/zigbee-herdsman-converters/lib/reporting.js:33:9)
    at Object.configure (/app/node_modules/zigbee-herdsman-converters/devices/develco.js:165:13)
    at Configure.configure (/app/lib/extension/configure.ts:115:13))
...
```

I tried to set a user name and passwort for mqtt that I configured in HA: 

```
data_path: /config/zigbee2mqtt
external_converters: []
devices: devices.yaml
groups: groups.yaml
homeassistant: true
permit_join: false
mqtt:
  base_topic: zigbee2mqtt
  server: mqtt://core-mosquitto:1883
  user: z2m
  password: 3....d
serial:
  port: >-
    /dev/serial/by-id/usb-dresden_elektronik_ingenieurtechnik_GmbH_ConBee_II_DE2252350-if00
  adapter: deconz
advanced:
  log_level: warn
  pan_id: 5843
  channel: 11
  network_key:
...
  availability_blocklist: []
  availability_passlist: []
  adapter_delay: 0
  ext_pan_id_string: ...
device_options:
  simulated_brightness: true
blocklist: []
passlist: []
queue:
  delay: 50
  simultaneously: 5
frontend:
  port: 8099
experimental: {}
availability:
  active:
    timeout: 10
  passive:
    timeout: 1500
socat:
  enabled: false
  master: pty,raw,echo=0,link=/tmp/ttyZ2M,mode=777
  slave: tcp-listen:8485,keepalive,nodelay,reuseaddr,keepidle=1,keepintvl=1,keepcnt=5
  options: '-d -d'
  log: false
zigbee_herdsman_debug: false
```

but nothing changed.

Log output from the MQTT side: 
```
[10:19:23] INFO: Successfully send discovery information to Home Assistant.
[10:19:24] INFO: Successfully send service information to the Supervisor.
1641547162: New connection from 172.30.33.10 on port 1883.
1641547162: New client connected from 172.30.33.10 as mqttjs_ab81d47e (p2, c1, k60, u'z2m').
1641547227: New connection from 172.30.32.2 on port 1883.
1641547227: Socket error on client <unknown>, disconnecting.
1641547258: Socket error on client mqttjs_ab81d47e, disconnecting.
```
