### ISSUE TITLE
unknown option & does not exist in the schema

### ISSUE THREAD

**Issue by DavyRoswinkel** [zigbee2mqtt/hassio-zigbee2mqtt#284]
**Description of problem:**
Multiple warnings in the supervisor log:
unknown option 
does not exist in the schema
Warnings came after updating the HA supervisor

**Zigbee2mqtt add-on version (if edge, please report commit hash):**
```
1.22.2-dev commit: 9fc413d
```

**Your entire configuration from the frontend (with sensitive fields redacted)**:
```
data_path: /share/zigbee2mqtt
socat:
  enabled: false
  master: pty,raw,echo=0,link=/tmp/ttyZ2M,mode=777
  slave: tcp-listen:8485,keepalive,nodelay,reuseaddr,keepidle=1,keepintvl=1,keepcnt=5
  options: '-d -d'
  log: false
mqtt:
  base_topic: zigbee2mqtt
  server: mqtt://server:1883
  user: ****
  password: ****
serial:
  port: >-
    /dev/serial/by-id/usb-dresden_elektronik_ingenieurtechnik_GmbH_ConBee_II_DE2403707-if00
  adapter: deconz
external_converters: []
devices: devices.yaml
groups: groups.yaml
homeassistant: true
permit_join: false
advanced:
  log_level: info
  pan_id: 6754
  channel: 11
  network_key:
    - 1
    - 3
    - 5
    - 7
    - 9
    - 11
    - 13
    - 15
    - 0
    - 2
    - 4
    - 6
    - 8
    - 10
    - 12
    - 13
  availability_blocklist: []
  availability_passlist: []
device_options: {}
blocklist: []
passlist: []
queue: {}
frontend:
  port: 8099
experimental: {}
availability: false
```

**Running platform (details from Suypervisor > System)**
```
Core: core-2021.12.10
Supervisor: supervisor-2022.01.0
Operating System: Home Assistant OS 7.2
```

**Your logs from Home Assistant Supervisor**
```
22-01-31 16:34:22 WARNING (MainThread) [supervisor.addons.options] Unknown option 'base_topic' for Zigbee2mqtt Edge (45df7312_zigbee2mqtt_edge)
22-01-31 16:34:22 WARNING (MainThread) [supervisor.addons.options] Option 'external_converters' does not exist in the schema for Zigbee2mqtt Edge (45df7312_zigbee2mqtt_edge)
22-01-31 16:34:22 WARNING (MainThread) [supervisor.addons.options] Option 'devices' does not exist in the schema for Zigbee2mqtt Edge (45df7312_zigbee2mqtt_edge)
22-01-31 16:34:22 WARNING (MainThread) [supervisor.addons.options] Option 'groups' does not exist in the schema for Zigbee2mqtt Edge (45df7312_zigbee2mqtt_edge)
22-01-31 16:34:22 WARNING (MainThread) [supervisor.addons.options] Option 'homeassistant' does not exist in the schema for Zigbee2mqtt Edge (45df7312_zigbee2mqtt_edge)
22-01-31 16:34:22 WARNING (MainThread) [supervisor.addons.options] Option 'permit_join' does not exist in the schema for Zigbee2mqtt Edge (45df7312_zigbee2mqtt_edge)
22-01-31 16:34:22 WARNING (MainThread) [supervisor.addons.options] Option 'advanced' does not exist in the schema for Zigbee2mqtt Edge (45df7312_zigbee2mqtt_edge)
22-01-31 16:34:22 WARNING (MainThread) [supervisor.addons.options] Option 'device_options' does not exist in the schema for Zigbee2mqtt Edge (45df7312_zigbee2mqtt_edge)
22-01-31 16:34:22 WARNING (MainThread) [supervisor.addons.options] Option 'blocklist' does not exist in the schema for Zigbee2mqtt Edge (45df7312_zigbee2mqtt_edge)
22-01-31 16:34:22 WARNING (MainThread) [supervisor.addons.options] Option 'passlist' does not exist in the schema for Zigbee2mqtt Edge (45df7312_zigbee2mqtt_edge)
22-01-31 16:34:22 WARNING (MainThread) [supervisor.addons.options] Option 'queue' does not exist in the schema for Zigbee2mqtt Edge (45df7312_zigbee2mqtt_edge)
22-01-31 16:34:22 WARNING (MainThread) [supervisor.addons.options] Option 'frontend' does not exist in the schema for Zigbee2mqtt Edge (45df7312_zigbee2mqtt_edge)
22-01-31 16:34:22 WARNING (MainThread) [supervisor.addons.options] Option 'experimental' does not exist in the schema for Zigbee2mqtt Edge (45df7312_zigbee2mqtt_edge)
22-01-31 16:34:22 WARNING (MainThread) [supervisor.addons.options] Option 'availability' does not exist in the schema for Zigbee2mqtt Edge (45df7312_zigbee2mqtt_edge)
```
