### ISSUE TITLE
All devices become unavailable and after refresh appear again

### ISSUE THREAD

**Issue by timknowlden** [zigbee2mqtt/hassio-zigbee2mqtt#286]
**Description of problem:**
All devices become unavailable briefly and after a resfresh appear again

**Zigbee2mqtt add-on version (if edge, please report commit hash):**
```
 1.23.0-1 
```

**Your entire configuration from the frontend (with sensitive fields redacted)**:
```
data_path: /share/zigbee2mqtt
external_converters: []
devices: devices.yaml
groups: groups.yaml
homeassistant: true
permit_join: true
mqtt:
  base_topic: zigbee2mqtt
  server: mqtt://192.168.1.*:1883
  user: *****
  password: *****
serial:
  port: /dev/ttyUSB0
advanced:
  log_level: info
  pan_id: 6755
  channel: 20
  network_key:
    - 1
    - 3
    - 5
    - 7
    - 9
    - 11
    - 13
    - 15
    - 0
    - 2
    - 4
    - 6
    - 8
    - 10
    - 12
    - 13
  availability_blocklist: []
  availability_passlist: []
device_options: {}
blocklist: []
passlist: []
queue: {}
frontend:
  port: 8099
experimental:
  new_api: true
availability: false
socat:
  enabled: false
  master: pty,raw,echo=0,link=/dev/ttyZ2M,mode=777
  slave: tcp-listen:8485,keepalive,nodelay,reuseaddr,keepidle=1,keepintvl=1,keepcnt=5
  options: '-d -d'
  log: false
  restartdelay: 1
  initialdelay: 1

```

**Running platform (details from Suypervisor > System)**
```
// Example
Core: core-2022.2.0
Supervisor: supervisor-2022.01.1
Operating System: Home Assistant OS 7.2
```

**Your logs from Home Assistant Supervisor**

ONLY mqtt errors in log currently.
```
Logger: homeassistant.components.hassio
Source: components/hassio/websocket_api.py:120
Integration: Home Assistant Supervisor (documentation, issues)
First occurred: 13:49:46 (1 occurrences)
Last logged: 13:49:46

Failed to to call /addons/45df7312_zigbee2mqtt/stats -

Logger: homeassistant.components.mqtt.discovery
Source: components/mqtt/discovery.py:104
Integration: MQTT (documentation, issues)
First occurred: 13:02:34 (33 occurrences)
Last logged: 13:02:35

Received message on illegal discovery topic 'homeassistant/switch/Kitchen Switch-relay-0/config'
Received message on illegal discovery topic 'homeassistant/switch/Kitchen Switch-relay-1/config'
Received message on illegal discovery topic 'homeassistant/device_automation/Grace Switch-input-0/push/config'
Received message on illegal discovery topic 'homeassistant/device_automation/Kitchen Switch-input-0/push/config'
Received message on illegal discovery topic 'homeassistant/device_automation/Kitchen Switch-input-1/push/config'
```
