### ISSUE TITLE
Unable to generate panId

### ISSUE THREAD

**Issue by pashaBolshov** [zigbee2mqtt/hassio-zigbee2mqtt#287]
**Description of problem:**
According https://www.zigbee2mqtt.io/guide/configuration/zigbee-network.html#permit-join we can generate "panId" by adding: 
pan_id: GENERATE
But I am not able to do in Zigbee2mqtt addon.

**Zigbee2mqtt add-on version (if edge, please report commit hash):**
```
 1.23.0-1
```

**Your entire configuration from the frontend (with sensitive fields redacted)**:
```
data_path: /config/zigbee2mqtt
external_converters: []
devices: devices.yaml
groups: groups.yaml
homeassistant: true
permit_join: false
mqtt:
  base_topic: zigbee2mqtt
  user: mqtt
  password: mqttmqtt
  server: mqtt://192.168.68.112:1883
serial:
  port: /dev/ttyUSB0
advanced:
  log_level: debug
  pan_id: 28268
  channel: 11
  network_key:
    - 1
    - 3
    - 5
    - 7
    - 9
    - 11
    - 13
    - 15
    - 0
    - 2
    - 4
    - 6
    - 8
    - 10
    - 12
    - 13
  availability_blocklist: []
  availability_passlist: []
device_options: {}
blocklist: []
passlist: []
queue: {}
frontend:
  port: 8099
experimental: {}
availability: false
socat:
  enabled: false
  master: pty,raw,echo=0,link=/tmp/ttyZ2M,mode=777
  slave: tcp-listen:8485,keepalive,nodelay,reuseaddr,keepidle=1,keepintvl=1,keepcnt=5
  options: '-d -d'
  log: false

```

**Running platform (details from Suypervisor > System)**
```
Core: core-2022.2.0
Supervisor: supervisor-2022.01.1
```

**Logs from Home Assistant Supervisor**
```
[s6-init] making user provided files available at /var/run/s6/etc...exited 0.
[s6-init] ensuring user provided files have correct perms...exited 0.
[fix-attrs.d] applying ownership & permissions fixes...
[fix-attrs.d] done.
[cont-init.d] executing container initialization scripts...
[cont-init.d] socat.sh: executing... 
[23:21:09] INFO: Socat not enabled, marking service as down
[cont-init.d] socat.sh: exited 0.
[cont-init.d] zigbee2mqtt.sh: executing... 
[23:21:10] INFO: MQTT available, fetching server detail ...
[23:21:10] INFO: Previous config file found, checking backup
[23:21:10] INFO: Creating backup config in '/config/zigbee2mqtt/.configuration.yaml.bk'
[23:21:11] INFO: Adjusting Zigbee2mqtt core yaml config with add-on quirks ...
[cont-init.d] zigbee2mqtt.sh: exited 0.
[cont-init.d] done.
[services.d] starting services
[services.d] done.
[23:21:12] INFO: Handing over control to Zigbee2mqtt Core ...
> zigbee2mqtt@1.23.0 start
> node index.js
Zigbee2MQTT:debug 2022-02-03 23:21:17: Loaded state from file /config/zigbee2mqtt/state.json
Zigbee2MQTT:info  2022-02-03 23:21:17: Logging to console and directory: '/config/zigbee2mqtt/log/2022-02-03.23-21-15' filename: log.txt
Zigbee2MQTT:debug 2022-02-03 23:21:18: Removing old log directory '/config/zigbee2mqtt/log/2022-02-03.23-09-56'
Zigbee2MQTT:info  2022-02-03 23:21:18: Starting Zigbee2MQTT version 1.23.0 (commit #unknown)
Zigbee2MQTT:info  2022-02-03 23:21:18: Starting zigbee-herdsman (0.14.10)
Zigbee2MQTT:debug 2022-02-03 23:21:18: Using zigbee-herdsman with settings: '{"adapter":{"concurrent":null,"delay":null,"disableLED":false},"backupPath":"/config/zigbee2mqtt/coordinator_backup.json","databaseBackupPath":"/config/zigbee2mqtt/database.db.backup","databasePath":"/config/zigbee2mqtt/database.db","network":{"channelList":[11],"extendedPanID":[221,221,221,221,221,221,221,221],"networkKey":"HIDDEN","panID":28268},"serialPort":{"path":"/dev/ttyUSB0"}}'
Zigbee2MQTT:error 2022-02-03 23:22:31: Error while starting zigbee-herdsman
Zigbee2MQTT:error 2022-02-03 23:22:31: Failed to start zigbee
Zigbee2MQTT:error 2022-02-03 23:22:31: Check https://www.zigbee2mqtt.io/guide/installation/20_zigbee2mqtt-fails-to-start.html for possible solutions
Zigbee2MQTT:error 2022-02-03 23:22:31: Exiting...
Zigbee2MQTT:error 2022-02-03 23:22:32: Error: network commissioning timed out - most likely network with the same panId or extendedPanId already exists nearby
    at ZnpAdapterManager.beginCommissioning (/app/node_modules/zigbee-herdsman/src/adapter/z-stack/adapter/manager.ts:347:23)
    at ZnpAdapterManager.start (/app/node_modules/zigbee-herdsman/src/adapter/z-stack/adapter/manager.ts:92:17)
    at Controller.start (/app/node_modules/zigbee-herdsman/src/controller/controller.ts:123:29)
    at Zigbee.start (/app/lib/zigbee.ts:58:27)
    at Controller.start (/app/lib/controller.ts:100:27)
    at start (/app/index.js:101:5)
```
