### ISSUE TITLE
"GENERATE" option doesn't work on addon

### ISSUE THREAD

**Issue by OldShaterhan** [zigbee2mqtt/hassio-zigbee2mqtt#289]
**Description of problem:**
// Please do a short description of the problem
// Make sure your problem is related to the add-on, not to core Zigbee2mqtt functionality, like problems with specific devices - for such issues use https://github.com/Koenkk/zigbee2mqtt/issues
I try to set advanced.network to GENERATE, but I get an error:

`Nie udało się zapisać konfiguracji dodatku, Invalid list for option 'network_key' in Zigbee2mqtt (45df7312_zigbee2mqtt). Got {'data_path': '/config/zigbee2mqtt', 'external_converters': [], 'devices': 'devices.yaml', 'groups': 'groups.yaml', 'homeassistant': True, 'permit_join': False, 'mqtt': {'base_topic': 'zigbee2mqtt'}, 'serial': {'port': 'tcp://xxx.xxx.xxx.xxx:6638'}, 'advanced': {'log_level': 'warn', 'pan_id': 6754, 'channel': 11, 'network_key': 'GENERATE', 'availability_blocklist': [], 'availability_passlist': []}, 'device_options': {}, 'blocklist': [], 'passlist': [], 'queue': {}, 'frontend': {'port': 8099}, 'ex...`

when I try to save to it. This also didn't work when I placed configuration with `!secret`
**Zigbee2mqtt add-on version (if edge, please report commit hash):**
```
// Example:
// > zigbee2mqtt@1.17.0 start /app
```
1.23.0-1
**Your entire configuration from the frontend (with sensitive fields redacted)**:
```
data_path: /config/zigbee2mqtt
external_converters: []
devices: devices.yaml
groups: groups.yaml
homeassistant: true
permit_join: false
mqtt:
  base_topic: zigbee2mqtt
serial:
  port: tcp://xxx.xxx.xxx.xxx:6638
advanced:
  log_level: warn
  pan_id: 6754
  channel: 11
  network_key: GENERATE
  availability_blocklist: []
  availability_passlist: []
device_options: {}
blocklist: []
passlist: []
queue: {}
frontend:
  port: 8099
experimental: {}
availability: false
socat:
  enabled: false
  master: pty,raw,echo=0,link=/tmp/ttyZ2M,mode=777
  slave: tcp-listen:8485,keepalive,nodelay,reuseaddr,keepidle=1,keepintvl=1,keepcnt=5
  options: '-d -d'
  log: false

```

**Running platform (details from Suypervisor > System)**
```
// Example
Core: core-2021.2.2
Supervisor: supervisor-2021.02.6
Operating System: HassOS 5.4
```

core-2022.2.3
supervisor-2022.01.1
Home Assistant OS 7.3
--

**Your logs from Home Assistant Supervisor**
I didn't see any logs for that issue.
