### ISSUE TITLE
Xiaomi WS-EUK03 (lumi.switch.n1aeu1) zigbee2mqtt show unsupported device

### ISSUE THREAD

**Issue by NightelfPL** [zigbee2mqtt/hassio-zigbee2mqtt#290]
**Description of problem:**
// Please do a short description of the problem
// Make sure your problem is related to the add-on, not to core Zigbee2mqtt functionality, like problems with specific devices - for such issues use https://github.com/Koenkk/zigbee2mqtt/issues
I installed Xiaomi WS-EUK03 switch and set it in pairing mode. Zigbe2mqtt show it as "Unsupported" device. 
In logs have error: "Zigbee2MQTT:warn  2022-02-12 16:14:50: Received message from unsupported device with Zigbee model 'lumi.switch.n1aeu1' and manufacturer name 'LUMI'
Zigbee2MQTT:warn  2022-02-12 16:14:50: Please see: https://www.zigbee2mqtt.io/how_tos/how_to_support_new_devices.html."

**Zigbee2mqtt add-on version (if edge, please report commit hash):**
```

1.18.1 commit: 1.18.1
```

**Your entire configuration from the frontend (with sensitive fields redacted)**:
```
data_path: /config/zigbee2mqtt
external_converters: []
devices: devices.yaml
groups: groups.yaml
homeassistant: true
permit_join: true
mqtt:
  base_topic: zigbee2mqtt
  user: homeassistant
  password: X
serial:
  port: /dev/ttyUSB0
advanced:
  log_level: warn
  pan_id: 6754
  channel: 11
  network_key:
    - X
  availability_blocklist: []
  availability_passlist: []
device_options: {}
blocklist: []
passlist: []
queue: {}
frontend:
  port: 8099
experimental: {}
socat:
  enabled: false
  master: pty,raw,echo=0,link=/tmp/ttyZ2M,mode=777
  slave: tcp-listen:8485,keepalive,nodelay,reuseaddr,keepidle=1,keepintvl=1,keepcnt=5
  options: '-d -d'
  log: false
```

**Running platform (details from Suypervisor > System)**
```
// Example
## System Health

version | core-2022.2.5
-- | --
installation_type | Home Assistant Supervised
dev | false
hassio | true
docker | true
user | root
virtualenv | false
python_version | 3.9.7
os_name | Linux
os_version | 4.19.0-13-amd64
arch | x86_64
timezone | Europe/Warsaw

<details><summary>Home Assistant Community Store</summary>

GitHub API | ok
-- | --
Github API Calls Remaining | 5000
Installed Version | 1.20.0
Stage | running
Available Repositories | 977
Downloaded Repositories | 6

</details>

<details><summary>Home Assistant Cloud</summary>

logged_in | false
-- | --
can_reach_cert_server | ok
can_reach_cloud_auth | ok
can_reach_cloud | ok

</details>

<details><summary>Home Assistant Supervisor</summary>

host_os | Debian GNU/Linux 10 (buster)
-- | --
update_channel | stable
supervisor_version | supervisor-2022.01.1
docker_version | 20.10.12
disk_total | 57.5 GB
disk_used | 10.9 GB
healthy | true
supported | failed to load: Unsupported
supervisor_api | ok
version_api | ok
installed_addons | Check Home Assistant configuration (3.9.0), Samba share (9.5.1), File editor (5.3.3), Mosquitto broker (6.0.1), Zigbee2mqtt (1.18.1-1), Zigbee2mqtt Edge (edge)

</details>

<details><summary>Lovelace</summary>

dashboards | 4
-- | --
resources | 4
views | 3
mode | storage

</details>

```

**Your logs from Home Assistant Supervisor**
```
// Your logs here
```
