### ISSUE TITLE
[supervisor.addons.options] Unknown option 'ext_pan_id' for Zigbee2mqtt

### ISSUE THREAD

**Issue by sau7777** [zigbee2mqtt/hassio-zigbee2mqtt#293]
**Description of problem:**
ext_pan_id settings doesn't accepted at Home Assistant Add-on configuration tab of Zigbee2mqtt

i.e.
- ext_pan_id is configurable via Home Assistant Add-on frontend of Zigbee2mqtt
- Zigbee2mqtt starts without any errors 
- then we got an "Unknown option 'ext_pan_id' for Zigbee2mqtt" error in supervisor logs
- when we navigate to Zigbee2mqtt configuration file via SSH there is no ext_pan_id section in it

**Zigbee2mqtt add-on version (if edge, please report commit hash):**
`> zigbee2mqtt@1.23.0 start`

**Your entire configuration from the frontend (with sensitive fields redacted)**:
```
data_path: /config/zigbee2mqtt
external_converters: []
devices: devices.yaml
groups: groups.yaml
homeassistant: false
permit_join: false
mqtt:
  base_topic: zigbee2mqtt
  server: mqtt://******:1883
  user: ********
  password: ********
serial:
  port: /dev/ttyUSB0
advanced:
  log_level: warn
  pan_id: 6971
  channel: 20
  network_key:
    - ***
 * truncated *
    - ***
  availability_blocklist: []
  availability_passlist: []
  last_seen: ISO_8601_local
  ext_pan_id:
    - 201
    - 6875
    - 522
    - 180
    - 323
    - 533
    - 64978
    - 20215
device_options: {}
blocklist: []
passlist: []
queue: {}
frontend:
  port: 8099
experimental: {}
availability: false
socat:
  enabled: false
  master: pty,raw,echo=0,link=/tmp/ttyZ2M,mode=777
  slave: tcp-listen:8485,keepalive,nodelay,reuseaddr,keepidle=1,keepintvl=1,keepcnt=5
  options: '-d -d'
  log: false
```

**Running platform (details from Suypervisor > System)**
```
Core: core-2022.2.6
Supervisor: supervisor-2022.01.1
Operating System: Home Assistant OS 7.4
```

**Your logs from Home Assistant Supervisor**
```
22-02-16 14:20:00 WARNING (MainThread) [supervisor.addons.options] Unknown option 'ext_pan_id' for Zigbee2mqtt (45df7312_zigbee2mqtt)
22-02-16 14:22:02 WARNING (MainThread) [supervisor.addons.options] Unknown option 'ext_pan_id' for Zigbee2mqtt (45df7312_zigbee2mqtt)
22-02-16 14:22:02 WARNING (MainThread) [supervisor.addons.options] Unknown option 'ext_pan_id' for Zigbee2mqtt (45df7312_zigbee2mqtt)
```
