### ISSUE TITLE
Cant add remote control to group (works in docker version)

### ISSUE THREAD

**Issue by Joly0** [zigbee2mqtt/hassio-zigbee2mqtt#294]
**Description of problem:**
// Please do a short description of the problem
// Make sure your problem is related to the add-on, not to core Zigbee2mqtt functionality, like problems with specific devices - for such issues use https://github.com/Koenkk/zigbee2mqtt/issues

Cant add device to group. Works in docker version.

**Zigbee2mqtt add-on version (if edge, please report commit hash):**
```
// Example:
// > zigbee2mqtt@1.17.0 start /app
```
zigbee2mqtt@1.23.0-1

**Your entire configuration from the frontend (with sensitive fields redacted)**:
```
data_path: /config/zigbee2mqtt
external_converters: []
devices: devices.yaml
groups: groups.yaml
homeassistant: true
permit_join: false
mqtt:
  base_topic: zigbee2mqtt
serial:
  port: >-
    /dev/serial/by-id/usb-ITead_Sonoff_Zigbee_3.0_USB_Dongle_Plus-port0
advanced:
  log_level: warn
  pan_id: 6754
  channel: 11
  network_key:
    - 1
    - 3
    - 5
    - 7
    - 9
    - 11
    - 13
    - 15
    - 0
    - 2
    - 4
    - 6
    - 8
    - 10
    - 12
    - 13
  availability_blocklist: []
  availability_passlist: []
device_options: {}
blocklist: []
passlist: []
queue: {}
frontend:
  port: 8099
experimental: {}
availability: false
socat:
  enabled: false
  master: pty,raw,echo=0,link=/tmp/ttyZ2M,mode=777
  slave: tcp-listen:8485,keepalive,nodelay,reuseaddr,keepidle=1,keepintvl=1,keepcnt=5
  options: '-d -d'
  log: false
```

**Running platform (details from Supervisor > System)**
```
// Example
Core: core- 2022.2.8
Supervisor: supervisor-2022.01.1
Operating System: Home Assistant OS 7.4
```

**Your logs from Home Assistant Supervisor**
```
Failed to add from group (Command 0x00158d00018bee5e/1 genGroups.add({"groupid":1,"groupname":""}, {"sendWhen":"immediate","timeout":10000,"disableResponse":false,"disableRecovery":false,"disableDefaultResponse":true,"direction":0,"srcEndpoint":null,"reservedBits":0,"manufacturerCode":null,"transactionSequenceNumber":null,"writeUndiv":false}) failed (Timeout - 26329 - 1 - 25 - 4 - 0 after 10000ms))
```
