### ISSUE TITLE
Timezone in hassio-zigbee2mqtt under supervisor

### ISSUE THREAD

**Issue by Elkropac** [zigbee2mqtt/hassio-zigbee2mqtt#298]
**Description of problem:**
Hi, is there a way to set correct time zone , when i run zigbee2mqtt as addon in homeassistant supervised?

My thermostat seems to be one hour off.
Also logs

I saw this
https://github.com/Koenkk/zigbee2mqtt/issues/2341

but i don't know, how to affect container settings under home assistant

Thanks for info

**Zigbee2mqtt add-on version (if edge, please report commit hash):**
```
zigbee2mqtt@1.24.0-1
```

**Your entire configuration from the frontend (with sensitive fields redacted)**:
```
data_path: /config/zigbee2mqtt
external_converters:
  - TZE200_ye5jkfsb.js
devices: devices.yaml
groups: groups.yaml
homeassistant: true
permit_join: false
mqtt:
  base_topic: zigbee2mqtt
serial:
  port: /dev/usbZigbee
advanced:
  log_level: warn
  pan_id: xxxxx
  channel: 25
  network_key: []
  availability_blocklist:
    - '0x01'
  availability_passlist:
   - '0x'
  report: true
  availability_timeout: 60
device_options: {}
blocklist: []
passlist: []
queue: {}
frontend:
  port: 8099
experimental: {}
availability: false
socat:
  enabled: false
  master: pty,raw,echo=0,link=/tmp/ttyZ2M,mode=777
  slave: tcp-listen:8485,keepalive,nodelay,reuseaddr,keepidle=1,keepintvl=1,keepcnt=5
  options: '-d -d'
  log: false

```

**Running platform (details from Suypervisor > System)**
```
Core: core-2022.2.9
Supervisor: supervisor-2022.01.1
Operating System: Debian 11
```

**Your logs from Home Assistant Supervisor**
```
// Your logs here
```
