### ISSUE TITLE
Zigbee2mqtt crash I don't understand why

### ISSUE THREAD

**Issue by thierry-rhone** [zigbee2mqtt/hassio-zigbee2mqtt#303]
**Description of problem:**

I use Z2mqtt in 2 identicals system
With the first I never have problem.
With the second Z2mqtt regulary crash I can't restart it
my devices are not specifics: switchs, bulbs...

my gateway : SONOFF ZBDongle-P  

**Zigbee2mqtt add-on version (if edge, please report commit hash):**
```
Current version: 1.24.0-1
```

**Your entire configuration from the frontend (with sensitive fields redacted)**:
```
data_path: /config/zigbee2mqtt
external_converters: []
devices: devices.yaml
groups: groups.yaml
homeassistant: true
permit_join: false
mqtt:
  base_topic: zigbee2mqtt
serial:
  port: /dev/ttyUSB0
advanced:
  log_level: warn
  pan_id: 6750
  channel: 11
  network_key:
    - 1
    - 3
    - 5
    - 7
    - 9
    - 11
    - 13
    - 15
    - 0
    - 2
    - 4
    - 6
    - 8
    - 10
    - 12
    - 13
  availability_blocklist: []
  availability_passlist: []
  rtscts: false
device_options: {}
blocklist: []
passlist: []
queue: {}
frontend:
  port: 8099
experimental: {}
availability: false
socat:
  enabled: false
  master: pty,raw,echo=0,link=/tmp/ttyZ2M,mode=777
  slave: tcp-listen:8485,keepalive,nodelay,reuseaddr,keepidle=1,keepintvl=1,keepcnt=5
  options: '-d -d'
  log: false

```

**Running platform (details from Suypervisor > System)**
```

Core: core-2022.3.5
Supervisor: supervisor-2022.03.5
Operating System: Debian GNU/Linux 10 (buster) (Armbian)
Docker version: 20.10..12
eMMC Lifetime: Used 10 % - 20 %
Used space: 47.3 %
```

**Your logs from Home Assistant Supervisor**
Log when I want to restart it
```
22-03-19 15:07:01 ERROR (MainThread) [supervisor.api.ingress] Ingress error: Cannot connect to host 172.30.33.4:8099 ssl:default [Connect call failed ('172.30.33.4', 8099)]
22-03-19 15:07:03 ERROR (MainThread) [supervisor.api.ingress] Ingress error: Cannot connect to host 172.30.33.4:8099 ssl:default [Connect call failed ('172.30.33.4', 8099)]
22-03-19 15:07:40 ERROR (SyncWorker_3) [supervisor.plugins.dns] Can't update hosts: [Errno 30] Read-only file system: '/data/dns/hosts'
22-03-19 15:07:40 WARNING (SyncWorker_3) [supervisor.docker.addon] Can't update DNS for addon_45df7312_zigbee2mqtt
22-03-19 15:07:41 INFO (SyncWorker_3) [supervisor.docker.interface] Stopping addon_45df7312_zigbee2mqtt application
22-03-19 15:07:41 INFO (SyncWorker_3) [supervisor.docker.interface] Cleaning addon_45df7312_zigbee2mqtt application
22-03-19 15:07:41 ERROR (MainThread) [supervisor.utils.json] Can't write /data/addons.json: [Errno 30] Read-only file system: '/data/tmpzp10z8dv'
22-03-19 15:07:41 ERROR (MainThread) [supervisor.utils.json] Can't write /data/addons/data/45df7312_zigbee2mqtt/options.json: [Errno 30] Read-only file system: '/data/addons/data/45df7312_zigbee2mqtt/tmpi4a640jv'
22-03-19 15:07:41 ERROR (MainThread) [supervisor.addons.addon] Add-on 45df7312_zigbee2mqtt can't write options
22-03-19 15:07:45 INFO (SyncWorker_4) [supervisor.docker.interface] Cleaning addon_45df7312_zigbee2mqtt application
22-03-19 15:07:49 ERROR (MainThread) [supervisor.utils.json] Can't write /data/addons.json: [Errno 30] Read-only file system: '/data/tmpgnrek6jh'
22-03-19 15:07:49 ERROR (MainThread) [supervisor.utils.json] Can't write /data/addons/data/45df7312_zigbee2mqtt/options.json: [Errno 30] Read-only file system: '/data/addons/data/45df7312_zigbee2mqtt/tmpqhblmizi'
22-03-19 15:07:49 ERROR (MainThread) [supervisor.addons.addon] Add-on 45df7312_zigbee2mqtt can't write options
22-03-19 15:07:58 WARNING (SyncWorker_7) [supervisor.docker.interface] Can't grep logs from zigbee2mqtt/zigbee2mqtt-aarch64: 409 Client Error for http+docker://localhost/v1.41/containers/ce091f37e6c6add125315f19a031eac0819dbfc4e629c49096724c0b756f9125/logs?stderr=1&stdout=1&timestamps=0&follow=0&tail=100: Conflict ("can not get logs from container which is dead or marked for removal")
22-03-19 15:08:00 WARNING (SyncWorker_2) [supervisor.docker.interface] Can't grep logs from zigbee2mqtt/zigbee2mqtt-aarch64: 409 Client Error for http+docker://localhost/v1.41/containers/ce091f37e6c6add125315f19a031eac0819dbfc4e629c49096724c0b756f9125/logs?stderr=1&stdout=1&timestamps=0&follow=0&tail=100: Conflict ("can not get logs from container which is dead or marked for removal")
22-03-19 15:13:41 INFO (MainThread) [supervisor.homeassistant.api] Updated Home Assistant API token
```
**End of log of zigbee2mqtt before crash**
```
> node index.js
(node:1556) UnhandledPromiseRejectionWarning: Error: EROFS: read-only file system, mkdir '/config/zigbee2mqtt/log/2022-03-19.17-17-53'
    at Object.mkdirSync (fs.js:1013:3)
    at mkdirSyncRecursive (/app/node_modules/mkdir-recursive/index.js:199:16)
    at mkdirSyncRecursive (/app/node_modules/mkdir-recursive/index.js:197:12)
    at mkdirSyncRecursive (/app/node_modules/mkdir-recursive/index.js:197:12)
    at mkdirSyncRecursive (/app/node_modules/mkdir-recursive/index.js:197:12)
    at Object.mkdirSync (/app/node_modules/mkdir-recursive/index.js:82:10)
    at Object.<anonymous> (/app/lib/util/logger.ts:22:8)
    at Module._compile (internal/modules/cjs/loader.js:1085:14)
    at Object.Module._extensions..js (internal/modules/cjs/loader.js:1114:10)
    at Module.load (internal/modules/cjs/loader.js:950:32)
(Use `node --trace-warnings ...` to show where the warning was created)
(node:1556) UnhandledPromiseRejectionWarning: Unhandled promise rejection. This error originated either by throwing inside of an async function without a catch block, or by rejecting a promise which was not handled with .catch(). To terminate the node process on unhandled promise rejection, use the CLI flag `--unhandled-rejections=strict` (see https://nodejs.org/api/cli.html#cli_unhandled_rejections_mode). (rejection id: 1)
(node:1556) [DEP0018] DeprecationWarning: Unhandled promise rejections are deprecated. In the future, promise rejections that are not handled will terminate the Node.js process with a non-zero exit code.
s6-supervise zigbee2mqtt: warning: unable to write supervise/death_tally: Read-only file system
s6-supervise zigbee2mqtt: warning: unable to write status file: Read-only file system
s6-supervise zigbee2mqtt: warning: unable to write status file: Read-only file system
s6-supervise zigbee2mqtt: warning: unable to write status file: Read-only file system
[17:17:55] INFO: Handing over control to Zigbee2mqtt Core ...
> zigbee2mqtt@1.24.0 start
> node index.js
```
