### ISSUE TITLE
1.25.0 and Sonoff Zigbee Bridge 

### ISSUE THREAD

**Issue by Duckshousemacservice** [zigbee2mqtt/hassio-zigbee2mqtt#311]
**Description of problem:**
Zigbee wont start after upgrade to 1.25.0 normal version

**Zigbee2mqtt add-on version (if edge, please report commit hash):**
```
1.25.0 hassio addon
```

**Your entire configuration from the frontend (with sensitive fields redacted)**:
```
data_path: /config/zigbee2mqtt
socat:
  enabled: false
  master: pty,raw,echo=0,link=/tmp/ttyZ2M,mode=777
  slave: tcp-listen:8485,keepalive,nodelay,reuseaddr,keepidle=1,keepintvl=1,keepcnt=5
  options: '-d'
  log: false
mqtt:
  base_topic: zigbee2mqtt
serial:
  port: tcp://10.0.0.150:8888
  adapter: ezsp
external_converters: []
devices: devices.yaml
groups: groups.yaml
homeassistant: true
permit_join: false
advanced:
  log_level: warn
  pan_id: 6722
  channel: 15
  network_key:
    - 1
    - 3
    - 5
    - 8
  ----
    - 0
    - 2
    - 4
    - 8
    - 8
    - 10
    - 12
    - 13
  availability_blocklist: []
  availability_passlist: []
device_options: {}
blocklist: []
passlist: []
queue: {}
frontend:
  port: 8099
experimental: {}
availability: false
```

**Running platform (details from Suypervisor > System)**
```
// Example
Core: core-2022.3.8
Supervisor: supervisor-2022.03.5
Operating System: Home Assistant OS 7.6
```

**Your logs from Home Assistant Supervisor**
```

this is from the add-on log:
[s6-init] making user provided files available at /var/run/s6/etc...exited 0.
[s6-init] ensuring user provided files have correct perms...exited 0.
[fix-attrs.d] applying ownership & permissions fixes...
[fix-attrs.d] done.
[cont-init.d] executing container initialization scripts...
[cont-init.d] socat.sh: executing... 
[21:13:02] INFO: Socat not enabled, marking service as down
[cont-init.d] socat.sh: exited 0.
[cont-init.d] zigbee2mqtt.sh: executing... 
[cont-init.d] zigbee2mqtt.sh: exited 0.
[cont-init.d] done.
[services.d] starting services
[services.d] done.
[21:13:03] INFO: Handing over control to Zigbee2mqtt Core ...
> zigbee2mqtt@1.25.0 start
> node index.js
Zigbee2MQTT:error 2022-04-01 21:13:07: Error while starting zigbee-herdsman
Zigbee2MQTT:error 2022-04-01 21:13:07: Failed to start zigbee
Zigbee2MQTT:error 2022-04-01 21:13:07: Check https://www.zigbee2mqtt.io/guide/installation/20_zigbee2mqtt-fails-to-start.html for possible solutions
Zigbee2MQTT:error 2022-04-01 21:13:07: Exiting...
Zigbee2MQTT:error 2022-04-01 21:13:07: Error: Error while opening socket
    at Socket.<anonymous> (/app/node_modules/zigbee-herdsman/src/adapter/ezsp/driver/uart.ts:257:24)
    at Socket.emit (events.js:412:35)
    at emitErrorNT (internal/streams/destroy.js:106:8)
    at emitErrorCloseNT (internal/streams/destroy.js:74:3)
    at processTicksAndRejections (internal/process/task_queues.js:82:21)
```
