### ISSUE TITLE
TS0011_switch_module not working anymore

### ISSUE THREAD

**Issue by NeeeeB** [zigbee2mqtt/hassio-zigbee2mqtt#313]
**Description of problem:**
See title, TS0011_switch_module (2 of them) are nor working anymore.
They worked properly until last update, now I can not control them anymore.
Z2M recognizes them, tries to pair, and then something fails and they are somewhat "ghosted"...
see this pastebin with what happens when I try to pair them :
https://pastebin.com/dd32Lu0n

**Zigbee2mqtt add-on version (if edge, please report commit hash):**
```
Version de Zigbee2MQTT [1.25.0] commit: [unknown]
```

**Your entire configuration from the frontend (with sensitive fields redacted)**:
```
data_path: /config/zigbee2mqtt
socat:
  enabled: false
  master: pty,raw,echo=0,link=/tmp/ttyZ2M,mode=777
  slave: tcp-listen:8485,keepalive,nodelay,reuseaddr,keepidle=1,keepintvl=1,keepcnt=5
  options: '-d -d'
  log: false
mqtt:
  base_topic: zigbee2mqtt
  user: *****
  password: ********
  server: mqtt://192.168.1.23:1883
serial:
  port: /dev/ttyUSB0
external_converters: []
devices: devices.yaml
groups: groups.yaml
homeassistant: true
permit_join: true
advanced:
  log_level: warn
  pan_id: 6754
  channel: 11
  network_key:
    - 1
    - 3
    - 5
    - 7
    - 9
    - 11
    - 13
    - 15
    - 0
    - 2
    - 4
    - 6
    - 8
    - 10
    - 12
    - 13
  availability_blocklist: []
  availability_passlist: []
device_options: {}
blocklist: []
passlist: []
queue: {}
frontend:
  port: 8099
experimental: {}
availability: false
```

**Running platform (details from Suypervisor > System)**
```
Core: core-2022.3.8
Supervisor: supervisor-2022.03.5
Operating System: HassOS 7.6
```

**Your logs from Home Assistant Supervisor**
```
...
```
