### ISSUE TITLE
Unable to remove base_topic : Warning Unknown Option 'base_topic'

### ISSUE THREAD

**Issue by MJWMJW2** [zigbee2mqtt/hassio-zigbee2mqtt#315]
**Description of problem:**
After update to 1.25.0-1 removing configuration from Configurations Options within Home Assistant UI, unable to remove 
base_topic: zigbee2mqtt

I hope I am simply being stupid and it needs to be removed elsewhere.

```
Failed to save add-on configuration, Invalid dict for option 'mqtt' in Zigbee2mqtt (45df7312_zigbee2mqtt). Got {'data_path': '/config/zigbee2mqtt', 'socat': {'enabled': False, 'master': 'pty,raw,echo=0,link=/tmp/ttyZ2M,mode=777', 'slave': 'tcp-listen:8485,keepalive,nodelay,reuseaddr,keepidle=1,keepintvl=1,keepcnt=5', 'options': '-d -d', 'log': False}, 'mqtt': None, 'serial': {'port': '/dev/serial/by-id/usb-1a86_USB_Serial-if00-port0'}}
```

**Zigbee2mqtt add-on version**
```
zigbee2mqtt@1.25.0-1
```

**Your entire configuration from the frontend (with sensitive fields redacted)**:
```
data_path: /config/zigbee2mqtt
socat:
  enabled: false
  master: pty,raw,echo=0,link=/tmp/ttyZ2M,mode=777
  slave: tcp-listen:8485,keepalive,nodelay,reuseaddr,keepidle=1,keepintvl=1,keepcnt=5
  options: '-d -d'
  log: false
mqtt:
  base_topic: zigbee2mqtt
serial:
  port: /dev/serial/by-id/usb-1a86_USB_Serial-if00-port0
```

**Running platform**
```
Core: core-2022.3.8
Supervisor: supervisor-2022.03.5
Operating System: Home Assistant OS 7.6
```

**Your logs from Home Assistant Supervisor**
```
WARNING (MainThread) [supervisor.addons.options] Unknown option 'base_topic' for Zigbee2mqtt (45df7312_zigbee2mqtt)
```
