### ISSUE TITLE
mqtt option client_id isn't supported

### ISSUE THREAD

**Issue by mgg1010** [zigbee2mqtt/hassio-zigbee2mqtt#316]
**Description of problem:**
I'm moving from standalone to HA.  Specifying client ID is useful for debugging, but it's not in the
list of options on the addin configuration - I checked the code.  So I get an error.

**Zigbee2mqtt add-on version (if edge, please report commit hash):**

version 1.25-01

**Your entire configuration from the frontend (with sensitive fields redacted)**:
```
data_path: /config/zigbee2mqtt
socat:
  enabled: false
  master: pty,raw,echo=0,link=/tmp/ttyZ2M,mode=777
  slave: tcp-listen:8485,keepalive,nodelay,reuseaddr,keepidle=1,keepintvl=1,keepcnt=5
  options: '-d -d'
  log: false
mqtt:
  server: mqtt://homeassistant.pixhome:1883
  user: 
  password: 
  client_id: newha
serial:
  port: /dev/ttyUSB0
```

**Running platform (details from Suypervisor > System)**
```
Version
supervisor-2022.03.5
Newest Version
supervisor-2022.03.5
Channel
stable
```

**Your logs from Home Assistant Supervisor**
```
22-04-03 11:18:55 WARNING (MainThread) [supervisor.addons.options] Unknown option 'client_id' for Zigbee2mqtt (45df7312_zigbee2mqtt)
```
