### ISSUE TITLE
Allow setting `mqtt.version` in configuration tab for addon

### ISSUE THREAD

**Issue by mdegat01** [zigbee2mqtt/hassio-zigbee2mqtt#324]
**Description of problem:**
When reviewing my supervisor log I saw that a lot of the configuration options of the addon had been removed from the schema. Which made sense, I saw the release note that everything should be configured via the GUI that could be. However when I tried to make changes to the configuration it blew up with this message:
```
!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!
READ THIS CAREFULLY
Refusing to start because configuration is not valid, found the following errors:
- MQTT retention requires protocol version 5
- MQTT retention requires protocol version 5

If you don't know how to solve this, read https://www.zigbee2mqtt.io/guide/configuration

!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!
```
The fix was pretty straightforward (although not actually at that link). Basically just set `mqtt.version` to `5` in the `configuration.yaml` file and it started up again.

I assume this just occurred because I hadn't modified the addon's config or `configuration.yaml` in a very long time (it was actually still json despite the name). But since it appears to be necessary to start the addon now I think think you should be able to set this from the configuration tab. This can't be fixed in the GUI if you can't actually get to the GUI.

**Zigbee2mqtt add-on version (if edge, please report commit hash):**
```
> zigbee2mqtt@1.25.0 start
```

**Your entire configuration from the frontend (with sensitive fields redacted)**:
```
data_path: /share/zigbee2mqtt
socat:
  enabled: false
  master: pty,raw,echo=0,link=/dev/ttyZ2M,mode=777
  slave: tcp-listen:8485,keepalive,nodelay,reuseaddr,keepidle=1,keepintvl=1,keepcnt=5
  options: '-d -d'
  log: false
mqtt:
  server: mqtts://core-mosquitto:8883
  ca: /share/ca.crt
  key: /data/ssl/zigbee2mqtt.key
  cert: /data/ssl/zigbee2mqtt.crt
  user: '!secret z2m_mqtt_username'
  password: '!secret z2m_mqtt_password'
serial:
  port: /dev/ttyACM0
  adapter: deconz
```

**Running platform (details from Supervisor > System)**
```
Core: core-2022.4.3
Supervisor: supervisor-2022.04.2
Operating System: Home Assistant OS 8.0.rc1
```

**Your logs from Home Assistant Supervisor**
```
Nothing relevant
```
