### ISSUE TITLE
Cannot read property 'ieeeAddr' of undefined

### ISSUE THREAD

**Issue by Sashik259** [zigbee2mqtt/hassio-zigbee2mqtt#326]
**Description of problem:**
I can't see my devices in Web UI (screenshot is attached), but they work and I can see them in "Map" page.
There's error in log.

**Zigbee2mqtt add-on version (if edge, please report commit hash):**
```
// > zigbee2mqtt@1.25.0-1
```

**Your entire configuration from the frontend (with sensitive fields redacted)**:
```
data_path: /config/zigbee2mqtt
socat:
  enabled: false
  master: pty,raw,echo=0,link=/tmp/ttyZ2M,mode=777
  slave: tcp-listen:8485,keepalive,nodelay,reuseaddr,keepidle=1,keepintvl=1,keepcnt=5
  options: '-d -d'
  log: false
mqtt:
  base_topic: zigbee2mqtt
  server: mqtt://core-mosquitto
  user: mqtuser
  password: mqtpass
serial:
  adapter: deconz
  port: /dev/ttyAMA0
external_converters: []
devices: devices.yaml
groups: groups.yaml
homeassistant: true
permit_join: false
advanced:
  log_level: warn
  pan_id: 6754
  channel: 11
  network_key:
    - 1
    - 3
    - 5
    - 7
    - 9
    - 11
    - 13
    - 15
    - 0
    - 2
    - 4
    - 6
    - 8
    - 10
    - 12
    - 13
  availability_blocklist: []
  availability_passlist: []
device_options: {}
blocklist: []
passlist: []
queue: {}
frontend:
  port: 8099
experimental: {}
```

**Running platform (details from Supervisor > System)**
```
Core: core-2022.4.4
Supervisor: supervisor-2022.04.0
Operating System: Raspbian GNU/Linux 10 (buster)
```

**Your logs from Home Assistant Supervisor**
```
[s6-init] making user provided files available at /var/run/s6/etc...exited 0.
[s6-init] ensuring user provided files have correct perms...exited 0.
[fix-attrs.d] applying ownership & permissions fixes...
[fix-attrs.d] done.
[cont-init.d] executing container initialization scripts...
[cont-init.d] socat.sh: executing... 
[13:17:22] INFO: Socat not enabled, marking service as down
[cont-init.d] socat.sh: exited 0.
[cont-init.d] zigbee2mqtt.sh: executing... 
[cont-init.d] zigbee2mqtt.sh: exited 0.
[cont-init.d] done.
[services.d] starting services
[services.d] done.
[13:17:24] INFO: Handing over control to Zigbee2mqtt Core ...
> zigbee2mqtt@1.25.0 start
> node index.js
CREATED DECONZ ADAPTER
Zigbee2MQTT:error 2022-04-16 13:17:30: Failed to call 'Bridge' 'start' (TypeError: Cannot read property 'ieeeAddr' of undefined
    at Bridge.publishInfo (/app/lib/extension/bridge.ts:571:81)
    at Bridge.start (/app/lib/extension/bridge.ts:104:20)
    at Controller.callExtensions (/app/lib/controller.ts:316:17)
    at Controller.start (/app/lib/controller.ts:153:9)
    at start (/app/index.js:101:5))
```

![Screenshot 2022-04-16 at 13 42 01](https://user-images.githubusercontent.com/77446865/163672159-be686f6d-c7cc-4ebc-b068-90f60f064971.png)
