### ISSUE TITLE
zigbee2mqtt and external broker

### ISSUE THREAD

**Issue by fredmaria** [zigbee2mqtt/hassio-zigbee2mqtt#341]
**Description of problem:**
// Please do a short description of the problem
// Make sure your problem is related to the add-on, not to core Zigbee2mqtt functionality, like problems with specific devices - for such issues use https://github.com/Koenkk/zigbee2mqtt/issues
My Z2M configuration.yaml has a 
server: mqtt://172.16.1.100:1883
user: mqtt-user
client_id: 'HomeAssistant'
password: xxxxx
defined for an external broker.
But in de debug file I do see another server and another user.
I'm sure the configuration file is used because if I change the client_id I see the changed client_id in the debug file.
:+1: 
Zigbee2MQTT:info  2022-05-22 12:54:22: Connecting to MQTT server at mqtt://core-mosquitto:1883
Zigbee2MQTT:debug 2022-05-22 12:54:22: Using MQTT keepalive: 60
Zigbee2MQTT:debug 2022-05-22 12:54:22: Using MQTT login with username: addons
Zigbee2MQTT:debug 2022-05-22 12:54:22: Using MQTT client ID: 'HomeAssistant'
Zigbee2MQTT:error 2022-05-22 12:54:26: MQTT failed to connect: getaddrinfo ENOTFOUND core-mosquitto
Zigbee2MQTT:error 2022-05-22 12:54:26: Exiting...

**Zigbee2mqtt add-on version (if edge, please report commit hash):**
```
// Example:
// > zigbee2mqtt@1.17.0 start /app
```
Current version: 1.25.1-1

**Your entire configuration from the frontend (with sensitive fields redacted)**:
```
/homeassistant: true
# Minimal configuration.yml example
permit_join: true
mqtt:
  # Required: MQTT server URL (use mqtts:// for SSL/TLS connection)
  server: 'mqtt://172.16.1.100:1883'
  # Optional: MQTT base topic for Zigbee2MQTT MQTT messages (default: zigbee2mqtt)
  base_topic: zigbee2mqtt
  # Optional: absolute path to SSL/TLS certificate of CA used to sign server and client certificates (default: nothing)
  #ca: '/etc/ssl/mqtt-ca.crt'
  # Optional: absolute paths to SSL/TLS key and certificate for client-authentication (default: nothing)
  #key: '/etc/ssl/mqtt-client.key'
  #cert: '/etc/ssl/mqtt-client.crt'
  # Optional: MQTT server authentication user (default: nothing)
  user: mqtt-user
  # Optional: MQTT server authentication password (default: nothing)
  password: FreDeriK
  # Optional: MQTT client ID (default: nothing)
  client_id: 'HomeAssistant'
  # Optional: disable self-signed SSL certificates (default: true)
  #reject_unauthorized: true
  # Optional: Include device information to mqtt messages (default: false)
  #include_device_information: true
  # Optional: MQTT keepalive in seconds (default: 60)
  keepalive: 60
  # Optional: MQTT protocol version (default: 4), set this to 5 if you
  # use the 'retention' device specific configuration
  #version: 4
  # Optional: Disable retain for all send messages. ONLY enable if you MQTT broker doesn't
  # support retained message (e.g. AWS IoT core, Azure IoT Hub, Google Cloud IoT core, IBM Watson IoT Platform).
  # Enabling will break the Home Assistant integration. (default: false)
  #force_disable_retain: false
frontend:
  port: 8089
serial:
    port: 'tcp://172.16.1.200:8888'
    adapter: ezsp
advanced:
  # Optional: Logging level, options: debug, info, warn, error (default: info)
  log_level: debug
  # Optional: log timestamp format (default: shown below)
  timestamp_format: 'YYYY-MM-DD HH:mm:ss'
  # Optional: Location of log directory (default: shown below)
  log_directory: data/log/%TIMESTAMP%
  # Optional: Log file name, can also contain timestamp, e.g.: zigbee2mqtt_%TIMESTAMP%.log (default: shown below)
  log_file: log.txt
  # Optional: Rotate log every 10MB around 3 files (default: true)
  log_rotation: true
```

**Running platform (details from Suypervisor > System)**
```
// Example
Home Assistant Core 2022.5.5
Home Assistant Supervisor 2022.05.2
Home Assistant OS 8.1
Kernel version 5.15.41
Agent version 1.2.1
```

**Your logs from Home Assistant Supervisor**
```
Zigbee2MQTT:info  2022-05-22 12:54:22: Connecting to MQTT server at mqtt://core-mosquitto:1883
Zigbee2MQTT:debug 2022-05-22 12:54:22: Using MQTT keepalive: 60
Zigbee2MQTT:debug 2022-05-22 12:54:22: Using MQTT login with username: addons
Zigbee2MQTT:debug 2022-05-22 12:54:22: Using MQTT client ID: 'HomeAssistant'
Zigbee2MQTT:error 2022-05-22 12:54:26: MQTT failed to connect: getaddrinfo ENOTFOUND core-mosquitto
Zigbee2MQTT:error 2022-05-22 12:54:26: Exiting...
```
