### ISSUE TITLE
Make measurement_poll_interval available via GUI

### ISSUE THREAD

**Issue by RubenKelevra** [zigbee2mqtt/hassio-zigbee2mqtt#36]
**Description of problem:**
I didn't found a way to specify a measurement_poll_interval for certain devices in the UI. The config file is split, so I can only access the main config file of the add-on. The devices section is managed by the add-on and not available to the user via the GUI in the supervisor section.

**Zigbee2mqtt add-on version:**
```
1.17.1-4
```

**Your entire configuration from the frontend (with sensitive fields redacted)**:
```
data_path: /share/zigbee2mqtt
external_converters: []
devices: devices.yaml
groups: groups.yaml
homeassistant: true
permit_join: false
mqtt:
  base_topic: zigbee2mqtt
  server: 'mqtt://core-mosquitto:1883'
  user: 
  password: 
serial:
  port: /dev/ttyUSB0
advanced:
  log_level: error
  pan_id: 6754
  channel: 11
  network_key:
  availability_blocklist: []
  availability_passlist: []
device_options: {}
blocklist: []
passlist: []
queue: {}
frontend:
  port: 8099
experimental: {}
socat:
  enabled: false
  master: 'pty,raw,echo=0,link=/dev/ttyZ2M,mode=777'
  slave: 'tcp-listen:8485,keepalive,nodelay,reuseaddr,keepidle=1,keepintvl=1,keepcnt=5'
  restartdelay: 1
  initialdelay: 1
  options: '-d -d'
  log: false
```

**Running platform**
```
Core: core-2021.2.3
Supervisor: supervisor-2021.02.11
Operating System: HassOS 5.11
```
