### ISSUE TITLE
502: Bad Gateway

### ISSUE THREAD

**Issue by Bethaaca** [zigbee2mqtt/hassio-zigbee2mqtt#366]
### Description of the issue

Previously I used z2m, no installation issues. I tested the ZHA and now I try to go back to the z2m, without success. I uninstalled ZHA, restarted home assistant, but I can't get back to z2m anymore. When I try to access, this error appears: `502: Bad Gateway`

Config:

```
data_path: /config/zigbee2mqtt
socat:
  enabled: false
  master: pty,raw,echo=0,link=/tmp/ttyZ2M,mode=777
  slave: tcp-listen:8485,keepalive,nodelay,reuseaddr,keepidle=1,keepintvl=1,keepcnt=5
  options: '-d -d'
  log: false
mqtt:
  server: mqtt://core-mosquitto:1883
  user: EDITED
  password: EDITED
  base_topic: zigbee2mqtt
serial:
  port: /dev/ttyUSB0
external_converters: []
devices: devices.yaml
groups: groups.yaml
homeassistant: true
permit_join: true
advanced:
  log_level: warn
  pan_id: 6754
  channel: 11
  network_key:
    - 1
    - 3
    - 5
    - 7
    - 9
    - 11
    - 13
    - 15
    - 0
    - 2
    - 4
    - 6
    - 8
    - 10
    - 12
    - 13
  availability_blocklist: []
  availability_passlist: []
device_options: {}
blocklist: []
passlist: []
queue: {}
frontend:
  port: 8099
experimental:
  transmit_power: 20
zigbee_herdsman_debug: false
```

### Addon version

 1.26.0-1

### Platform

Home Assistant Core 2022.6.7
Home Assistant Supervisor 2022.07.0

### Logs of the issue (if applicable)

s6-rc: info: service s6rc-oneshot-runner: starting
s6-rc: info: service s6rc-oneshot-runner successfully started
s6-rc: info: service fix-attrs: starting
s6-rc: info: service fix-attrs successfully started
s6-rc: info: service legacy-cont-init: starting
cont-init: info: running /etc/cont-init.d/socat.sh
[12:07:17] INFO: Socat not enabled, marking service as down
cont-init: info: /etc/cont-init.d/socat.sh exited 0
cont-init: info: running /etc/cont-init.d/zigbee2mqtt.sh
cont-init: info: /etc/cont-init.d/zigbee2mqtt.sh exited 0
s6-rc: info: service legacy-cont-init successfully started
s6-rc: info: service legacy-services: starting
services-up: info: copying legacy longrun socat (no readiness notification)
services-up: info: copying legacy longrun zigbee2mqtt (no readiness notification)
[12:07:18] INFO: Handing over control to Zigbee2MQTT Core ...
> zigbee2mqtt@1.26.0 start
> node index.js
Zigbee2MQTT:info  2022-07-31 12:07:23: Logging to console and directory: '/config/zigbee2mqtt/log/2022-07-31.12-07-22' filename: log.txt
Zigbee2MQTT:info  2022-07-31 12:07:23: Starting Zigbee2MQTT version 1.26.0 (commit #unknown)
Zigbee2MQTT:info  2022-07-31 12:07:23: Starting zigbee-herdsman (0.14.40)
Zigbee2MQTT:error 2022-07-31 12:08:28: Error while starting zigbee-herdsman
Zigbee2MQTT:error 2022-07-31 12:08:28: Failed to start zigbee
Zigbee2MQTT:error 2022-07-31 12:08:28: Check https://www.zigbee2mqtt.io/guide/installation/20_zigbee2mqtt-fails-to-start.html for possible solutions
Zigbee2MQTT:error 2022-07-31 12:08:28: Exiting...
Zigbee2MQTT:error 2022-07-31 12:08:28: Error: network commissioning timed out - most likely network with the same panId or extendedPanId already exists nearby
    at ZnpAdapterManager.beginCommissioning (/app/node_modules/zigbee-herdsman/src/adapter/z-stack/adapter/manager.ts:347:23)
    at ZnpAdapterManager.start (/app/node_modules/zigbee-herdsman/src/adapter/z-stack/adapter/manager.ts:92:17)
    at Controller.start (/app/node_modules/zigbee-herdsman/src/controller/controller.ts:123:29)
    at Zigbee.start (/app/lib/zigbee.ts:58:27)
    at Controller.start (/app/lib/controller.ts:101:27)
    at start (/app/index.js:109:5)
