### ISSUE TITLE
generate random PAN_ID doesn't work

### ISSUE THREAD

**Issue by bruvv** [zigbee2mqtt/hassio-zigbee2mqtt#39]
**Description of problem:**
When I want to gerenerate my pan_id I use because I switched from adapters and want to repair my network. I wanted to use
```pan_id: GENERATE```
As can be read from: https://www.zigbee2mqtt.io/information/configuration.html
But it is giving me an error.

**Zigbee2mqtt add-on version (if edge, please report commit hash):**
```
zigbee2mqtt@1.17.1
```

**Your entire configuration from the frontend (with sensitive fields redacted)**:
```
data_path: /config/zigbee2mqtt
external_converters: []
devices: devices.yaml
groups: groups.yaml
homeassistant: true
permit_join: false
mqtt:
  base_topic: zigbee2mqtt
serial:
  port: /dev/ttyUSB0
advanced:
  log_level: info
  pan_id: GENERATE
  channel: 11
  network_key:
    - 1
    - 3
    - 5
    - 7
    - 9
    - 11
    - 13
    - 15
    - 0
    - 2
    - 4
    - 6
    - 8
    - 10
    - 12
    - 13
  availability_blocklist: []
  availability_passlist: []
device_options: {}
blocklist: []
passlist: []
queue: {}
frontend:
  port: 8099
experimental: {}
socat:
  enabled: false
  master: 'pty,raw,echo=0,link=/tmp/ttyZ2M,mode=777'
  slave: 'tcp-listen:8485,keepalive,nodelay,reuseaddr,keepidle=1,keepintvl=1,keepcnt=5'
  options: '-d -d'
  log: false
```

**Running platform (details from Suypervisor > System)**
```
core-2021.2.3
supervisor-2021.02.11
Home Assistant OS 5.12
```

**Your logs from Home Assistant Supervisor**
```
Failed to save addon configuration, not a valid value for dictionary value @ data['options']. Got {'data_path': '/config/zigbee2mqtt', 'external_converters': [], 'devices': 'devices.yaml', 'groups': 'groups.yaml', 'homeassistant': True, 'permit_join': True, 'mqtt': {'base_topic': 'zigbee2mqtt'}, 'serial': {'port': '/dev/ttyUSB0'}, 'advanced': {'log_level': 'info', 'pan_id': 'GENERATE', 'channel': 11, 'network_key': [1, 3, 5, 7, 9, 11, 13, 15, 0, 2, 4, 6, 8, 10, 12, 13], 'availability_blocklist': [], 'availability_passlist': []}, 'device_options'...
```
