### ISSUE TITLE
Sonoff SNZB-04 as presence sensor - wrong status

### ISSUE THREAD

**Issue by akula3** [zigbee2mqtt/hassio-zigbee2mqtt#409]
### Description of the issue

I tried to use SNZB-04 as a presence sensor for a lawnmower robot.
When the sensor is closed (magnet is close to sensor), the status in HA is "away". When the sensor is open (magnet is away from sensor), the status is "present".  The same behavior as occupancy sensor. Whereas the other options (window, door) working as expected.
Of course, there is a workaround with a new template sensor and
```
binary_sensor:
  - platform: template
    sensors:
      inverted_sensor:
        value_template: >-
          {{ is_state('binary_sensor.window_door_sensor', 'off') }}
        device_class: door
        friendly_name: Inverted Sensor
```
But, in my point of view, this is a bug. I'm just not sure, if it is Z2M related or directly HA.

### Addon version

1.28.1

### Platform

Home Assistant 2022.10.5
Supervisor 2022.10.0
Operating System 9.3
