### ISSUE TITLE
Aqara D1 (QBKG23LM) - device has not successfully been paired

### ISSUE THREAD

**Issue by ghork125** [zigbee2mqtt/hassio-zigbee2mqtt#412]
### Description of the issue

Hello. I have several [aqara d1](https://www.zigbee2mqtt.io/devices/QBKG23LM.html#xiaomi-qbkg23lm) switches, not so long ago I accidentally reset one of them, tried to reconnect it to the z2m, but nothing happened. All other switches that have not been reset continue to function as they did.
I discovered the problem on version 1.28.0-1, after that there were already 2 updates, but the switch still cannot be added again to z2m.

Testing was carried out on 2 coordinators: v3 and v4 lan. All other devices, from those that I have, normally pass from one coordinator to another.
Distance from the coordinator is about 2 meters, without walls.

This image from z2m with coordinator v4 lan:
![image](https://user-images.githubusercontent.com/70881046/200901157-9a905ea1-bc70-42b8-bbbd-9ce500988e99.png)

This image from z2m with coordinator v3 usb, here you can see both switches that have not been reset and that continue to work:
![image](https://user-images.githubusercontent.com/70881046/200901786-cbac85c8-214c-47df-bd6c-83b96520cbbb.png)

### Addon version

v.1.28.2-1

### Platform

Home Assistant 2022.11.2
Supervisor 2022.10.2
Operating System 9.3
Frontend 20221108.0 - latest

### Logs of the issue (if applicable)

```
debug 2022-11-09 22:22:54: Received MQTT message on 'hamgeek/bridge/request/permit_join' with data '{"device":null,"time":254,"transaction":"lyz5e-1","value":true}'
info  2022-11-09 22:22:54: Zigbee: allowing new devices to join.
info  2022-11-09 22:22:55: MQTT publish: topic 'hamgeek/bridge/response/permit_join', payload '{"data":{"time":254,"value":true},"status":"ok","transaction":"lyz5e-1"}'
info  2022-11-09 22:23:11: Device '0x00158d000650cc74' joined
info  2022-11-09 22:23:11: MQTT publish: topic 'hamgeek/bridge/event', payload '{"data":{"friendly_name":"0x00158d000650cc74","ieee_address":"0x00158d000650cc74"},"type":"device_joined"}'
info  2022-11-09 22:23:11: Starting interview of '0x00158d000650cc74'
info  2022-11-09 22:23:11: MQTT publish: topic 'hamgeek/bridge/event', payload '{"data":{"friendly_name":"0x00158d000650cc74","ieee_address":"0x00158d000650cc74","status":"started"},"type":"device_interview"}'
debug 2022-11-09 22:23:11: Device '0x00158d000650cc74' announced itself
info  2022-11-09 22:23:11: MQTT publish: topic 'hamgeek/bridge/event', payload '{"data":{"friendly_name":"0x00158d000650cc74","ieee_address":"0x00158d000650cc74"},"type":"device_announce"}'
error 2022-11-09 22:25:30: Failed to interview '0x00158d000650cc74', device has not successfully been paired
info  2022-11-09 22:25:30: MQTT publish: topic 'hamgeek/bridge/event', payload '{"data":{"friendly_name":"0x00158d000650cc74","ieee_address":"0x00158d000650cc74","status":"failed"},"type":"device_interview"}'
debug 2022-11-09 22:25:31: Saving state to file /config/zigbee2mqtt/state.json
```

**Comment by ghork125** [comment]
I tried to raise z2m in docker, checked all versions from 1.19.0 to latest. None of the versions of aqara d1 can pass the interview. I tried to change the channel, each time I generated a new panid and network_key. Tell me during the interview how does Z2M get information about the device? via the Internet site https://www.zigbee2mqtt.io/ ? or the database of possible supported devices is located locally in the configs?

**Comment by ghork125** [comment]
As an example, an attempt to connect to z2m 1.23.0:

![image](https://user-images.githubusercontent.com/70881046/202854270-b6bc4670-c060-49b9-b1ac-6bf743e7b1e3.png)
![image](https://user-images.githubusercontent.com/70881046/202854285-f5c49764-0785-4d44-9713-5cd5f127b26a.png)
![image](https://user-images.githubusercontent.com/70881046/202854314-cbee85dc-ccf2-41b2-82fa-d46c944e90e9.png)

configuration.yaml:

```
homeassistant: true
permit_join: true
mqtt:
  base_topic: z2m_test
  server: mqtt://192.168.0.100:1883/
  user: usr
  password: pswd
serial:
  port: tcp://192.168.0.98:5000
advanced:
  log_level: debug
  pan_id: 40295
  channel: 11
  network_key:
    - 12
    - 223
    - 181
    - 57
    - 230
    - 150
    - 68
    - 117
    - 151
    - 85
    - 85
    - 132
    - 116
    - 114
    - 53
    - 110
  homeassistant_legacy_entity_attributes: false
  legacy_api: false
frontend:
  port: 8080
device_options:
  legacy: false
devices:
  '0x00158d000650cc74':
    friendly_name: '0x00158d000650cc74'
```

**Comment by ghork125** [comment]
During testing, I tried to reconnect 3 of these switches, now they all fail the interview. I would like to resolve the issue as soon as possible.

**Comment by Koenkk** [comment]
Please check https://www.zigbee2mqtt.io/guide/faq/#interview-fails 

If that doesn't help, provide the herdsman debug log when pairing the device close to the coordinator.

See https://www.zigbee2mqtt.io/guide/usage/debug.html on how to enable the herdsman debug logging. Note that this is only logged to STDOUT and not to log files.

**Comment by ghork125** [comment]
I create new clean MQTT, raise koenkk/zigbee2mqtt in docker, change config with my settings, and try to pair 2 device: [Blitzwolf SHP-13](https://www.zigbee2mqtt.io/devices/TS0121_plug.html#tuya-ts0121_plug), which is in another room, and Aqara D1, which is located 0.5 meters from the coordinator. Blitzwolf added in z2m before I got to the computer, but Aqara never added.
command to docker:

`docker run -itd --name="Zigbee2MQTT" --net=host -p 8080:8080 -e TZ=Asia/Yekaterinburg -e DEBUG=zigbee-herdsman* --restart=always -v /docker/z2m/data:/app/data koenkk/zigbee2mqtt`

configuration.yaml:

```
# Home Assistant integration (MQTT discovery)
homeassistant: true

# allow new devices to join
permit_join: true
external_converters: []
devices:
  - devices.yaml
groups:
  - groups.yaml
# MQTT settings
mqtt:
  # MQTT base topic for zigbee2mqtt MQTT messages
  base_topic: z2m_test
  # MQTT server URL
  server: 'mqtt://192.168.0.9:1883/'
  user: usr
  password: pswd
  # MQTT server authentication, uncomment if required:
  # user: my_user
  # password: my_password

# Serial settings
serial:
  # Location of CC2531 USB sniffer
  port: tcp://192.168.0.98:5000
advanced:
  log_level: debug
  pan_id: GENERATE
  channel: 11
  network_key: GENERATE
  availability_blocklist: []
  availability_passlist: []
  homeassistant_legacy_entity_attributes: false
  legacy_api: false
  legacy_availability_payload: false
device_options:
  legacy: false
blocklist: []
passlist: []
queue: {}
frontend:
  port: 8080
experimental: {}
availability: false
```

and at the end I got a log file:
[log.txt](https://github.com/zigbee2mqtt/hassio-zigbee2mqtt/files/10050253/log.txt)


0x60a423fffed2ef57 - Blitzwolf SHP-13
0x00158d0006e4bdb5 - Aqara D1
