### ISSUE TITLE
Zigbee devices working, but the front end not

### ISSUE THREAD

**Issue by gregolin** [zigbee2mqtt/hassio-zigbee2mqtt#428]
### Description of the issue

When I access the ADD-ONS page, I see Z2M as "not running", but checking the log and my dashboards all devices are working fine. It sounds good, but I can't add a new device since I can't access the Z2M page.
Again, the Z2M log is fine, I can see all devices and the state of each one initialized.
Thanks.

### Addon version

1.28.4-1

### Platform

Home Assistant 2022.11.5
Supervisor 2022.11.2
Frontend 20221108.0 - latest

**Comment by gerwim** [comment]
I had the same issue. Adding `frontend: true` in the configuration.yaml file fixed the issue for me.

**Comment by gregolin** [comment]
I'm sorry but I couldn't understand it.
Just a new line with this content? It shows me a syntax error for that.

**Comment by gerwim** [comment]
This is my zigbee2mqtt configuration file:

```
data_path: /config/zigbee2mqtt
socat:
  enabled: false
  master: pty,raw,echo=0,link=/tmp/ttyZ2M,mode=777
  slave: tcp-listen:8485,keepalive,nodelay,reuseaddr,keepidle=1,keepintvl=1,keepcnt=5
  options: "-d -d"
  log: false
mqtt: {}
serial:
  port: >-
    /dev/serial/by-id/usb-dresden_elektronik_ingenieurtechnik_GmbH_ConBee_II_DE2599763-if00
  adapter: deconz
frontend: true
advanced:
  network_key: [] # omitted
```

As you can see, above `advanced` there is the setting`frontend: true`
