### ISSUE TITLE
Addon fails to start after supervisor update

### ISSUE THREAD

**Issue by tomlut** [zigbee2mqtt/hassio-zigbee2mqtt#448]
### Description of the issue

Description of the issue

If the supervisor updates then the addon stops and I have to restart it manually.

If the host is rebooted the addon also has to be started manually.

I do have the addon "Start on boot" toggle on.

![IMG_0803](https://user-images.githubusercontent.com/10679300/214913389-e64fbe41-e6c8-46ad-8df6-72d4bd82f08e.png)

### Addon version

1.29.2-1 

### Platform

Home Assistant 2023.1.7
Supervisor 2023.01.1
Operating System 9.4
Frontend 20230110.0 - latest

**Comment by tomlut** [comment]
I will not be able to check if this is still an issue until after the next OS release.

**Comment by tomlut** [comment]
Supervisor just updated to 2023.3.1.

Zigbee2mqtt stopped and did not restart. 

All my other add-ons kept running.

**Comment by tomlut** [comment]
Still an issue. After automatic update to supervisor 2023.04.0 zigbee2mqtt was the only addon stopped and failed to restart.

**Comment by tomlut** [comment]
Just updated the host to HA OS 10.1 the addon did auto start. I'm waiting for another supervisor release test before closing this though.

**Comment by tomlut** [comment]
Still an issue. Supervisor just automatically updated to 2023.6.1 and Zigbee2MQTT addon stopped again.

**Comment by tomlut** [comment]
No relevant errors in the Core, Supervisor or Z2M logs. 

Z2M config:
```
external_converters:
  - ext_converter.js
devices:
  - devices.yaml
groups:
  - groups.yaml
homeassistant: true
permit_join: false
mqtt:
  base_topic: zigbee2mqtt
  user: <redacted>
  password: <redacted>
  server: mqtt://10.1.1.100:1883
serial:
  port: tcp://10.1.1.210:6638
advanced:
  log_level: warn
  pan_id: 6754
  channel: 11
  network_key:
    - <redacted>
  availability_blocklist: []
  availability_passlist: []
device_options: {}
blocklist:
  - '0x00124b000639b8f6'
passlist: []
queue: {}
frontend:
  port: 8099
experimental: {}
availability: false
```
