### ISSUE TITLE
Optimistic=False does not send updates to HASS.

### ISSUE THREAD

**Issue by th3w1zard1** [zigbee2mqtt/hassio-zigbee2mqtt#478]
### Description of the issue

When optimistic=False, no state updates are sent to HASS after a light.turn_on command. Worth mentioning this also happens in groups.
Reporting is correctly configured.
![image](https://user-images.githubusercontent.com/2219836/229384282-5c0173d8-8487-4a83-9ceb-cb6a4f51ca7b.png)

configuration.yaml:
```
device_options:
  homeassistant: true
  debounce: null
  # (DEPRECATED) Retrieves the state after setting it. Should only be enabled when the reporting feature does not work for this device.
  retrieve_state: false
advanced:
  # Optional: Enables report feature (default true), this feature is DEPRECATED since reporting is now setup by default
  # when binding devices. Docs can still be found here: https://github.com/Koenkk/zigbee2mqtt.io/blob/master/docs/information/report.md
  # ^ above link no longer exists, see instead https://github.com/sjorge/zigbee2mqtt.io/blob/4d8f358dade21b2a382fd18aec182b9bda633db1/docs/information/report.md
  report: true
  legacy_availability_payload: true
  # Optional: state caching, MQTT message payload will contain all attributes, not only changed ones.
  # Has to be true when integrating via Home Assistant (default: true)
  cache_state: true
  # Optional: persist cached state, only used when cache_state: true (default: true)
  cache_state_persistent: true
  # Optional: send cached state on startup, only used when cache_state_persistent: true (default: true)
  cache_state_send_on_startup: true
  # Optional: disables the legacy api (default: shown below)
  legacy_api: false
homeassistant:
  discovery_topic: 'homeassistant'
  status_topic: 'homeassistant/status'
  legacy_entity_attributes: true
  legacy_triggers: false
```

### Addon version

Latest as of 4/2/2023

### Platform

Latest core 2023.3.0
Latest supervisor as of 4/2/2023
OS: Ubuntu:latest
