### ISSUE TITLE
Error starting addon

### ISSUE THREAD

**Issue by Robifz** [zigbee2mqtt/hassio-zigbee2mqtt#488]
### Description of the issue

I have looked at known issues at startup. But I cannot see what I have wrong.
This is the error in the log:
[09:22:55] INFO: Preparing to start...
[09:22:55] INFO: Socat not enabled
[09:22:57] INFO: Starting Zigbee2MQTT...
Zigbee2MQTT:info  2023-05-16 09:23:03: Logging to console and directory: '/config/zigbee2mqtt/log/2023-05-16.09-23-03' filename: log.txt
Zigbee2MQTT:info  2023-05-16 09:23:03: Starting Zigbee2MQTT version 1.30.4 (commit #unknown)
Zigbee2MQTT:info  2023-05-16 09:23:03: Starting zigbee-herdsman (0.14.111)
Error: Reset error: Error: {"sequence":-1} after 10000ms
    at /app/node_modules/zigbee-herdsman/src/adapter/ezsp/driver/uart.ts:299:23
    at Queue.executeNext (/app/node_modules/zigbee-herdsman/src/utils/queue.ts:32:32)

This is the yaml:
```
data_path: /config/zigbee2mqtt
socat:
  enabled: false
  master: pty,raw,echo=0,link=/tmp/ttyZ2M,mode=777
  slave: tcp-listen:8485,keepalive,nodelay,reuseaddr,keepidle=1,keepintvl=1,keepcnt=5
  options: "-d -d"
  log: false
mqtt:
  mqtt: mqtt://core-mosquitto:1883
  user: mqqt_user
  password: XXXXXXXX
  server: localhost
serial:
  port: >-
    /dev/serial/by-id/usb-ITEAD_SONOFF_Zigbee_3.0_USB_Dongle_Plus_V2_20230220110458-if00
  adapter: ezsp
```

I have this Zigbee stick:
SONOFF Zigbee 3.0 USB Dongle Plus V2 ZBDongle-E

This stick works fine for ZHA devices. I just have a few devices I want to add that do not work with ZHA. 
Am I correct to assume that I can use Z2M and ZHA with the same Zigbee stick?

### Addon version

1.30.4-1

### Platform

Home Assistant Core
Installed version
2023.4.6
