### ISSUE TITLE
Can't start ziggbe2mqtt container

### ISSUE THREAD

**Issue by robertoprubio** [zigbee2mqtt/hassio-zigbee2mqtt#520]
### Description of the issue

When I try to start the container, it fails.
I'm using a docker-compose file.

```
version: '3.8'
services:
  zigbee2mqtt:
    image: koenkk/zigbee2mqtt
    container_name: zigbee2mqtt
    environment:
      - TZ=Europe/Madrid
    volumes:
      - ../dockers-data/zigbee2mqtt:/app/data
      - /run/udev:/run/udev:ro
    ports:
      - 1881:8080
    group_add:
      - dialout
    user: 1000:1000        
    devices:
      - /dev/serial/by-id/usb-Silicon_Labs_Sonoff_Zigbee_3.0_USB_Dongle_Plus_0001-if00-port0:/dev/ttyACM0
    restart: unless-stopped


```

The contents of the data folder

```
$ ls -l  ../dockers-data/zigbee2mqtt
total 4
-rw-rw-r-- 1 roberto roberto 265 sep 16 02:05 configuration.yml

```
The log of the compose up

```
[+] Running 1/0
 ✔ Container zigbee2mqtt  Recreated                                                                                                                                                                                                    0.0s 
Attaching to zigbee2mqtt
zigbee2mqtt  | Using '/app/data' as data directory
zigbee2mqtt  | Creating configuration file...
zigbee2mqtt  | cp: can't stat '/app/configuration.example.yaml': No such file or directory
zigbee2mqtt exited with code 0
```

### Addon version

-

### Platform

Operating System: Ubuntu server 22.04-LTS

### Logs of the issue (if applicable)

[+] Running 1/0
 ✔ Container zigbee2mqtt  Recreated                                                                                                                                                                                                    0.0s 
Attaching to zigbee2mqtt
zigbee2mqtt  | Using '/app/data' as data directory
zigbee2mqtt  | Creating configuration file...
zigbee2mqtt  | cp: can't stat '/app/configuration.example.yaml': No such file or directory
zigbee2mqtt exited with code 0
