### ISSUE TITLE
configuration options are ignored (e.g. availability)

### ISSUE THREAD

**Issue by letsruletheworld** [zigbee2mqtt/hassio-zigbee2mqtt#534]
### Description of the issue

"Last Seen" and "Availability" are not updated and marked with "N/A" and "Disabled".

If I follow the documentation of Z2M I should add something like:

```
device_options:
  homeassistant:
    last_seen:
      enabled_by_default: true
advanced:
  last_seen: ISO_8601_local
availability:
  active:
    timeout: 5
  passive:
    timeout: 1500
```

However - even if I add this to the Configuration via WEBGUI or directly to yaml (via the ... dots in WEBGUI) it doesnt change the behavior of Z2M and is simple ignored.

complete config looks like:

```
data_path: /config/zigbee2mqtt
socat:
  enabled: false
  master: pty,raw,echo=0,link=/tmp/ttyZ2M,mode=777
  slave: tcp-listen:8485,keepalive,nodelay,reuseaddr,keepidle=1,keepintvl=1,keepcnt=5
  options: "-d -d"
  log: false
  availability:
    active:
      timeout: 5
    passive:
      timeout: 1500
mqtt: {}
serial:
  adapter: ezsp
  port: >-
    /dev/serial/by-id/usb-ITEAD_SONOFF_Zigbee_3.0_USB_Dongle_Plus_V2_20220811135119-if00
device_options:
  homeassistant:
    last_seen:
      enabled_by_default: true
advanced:
  last_seen: ISO_8601_local
availability:
  active:
    timeout: 5
  passive:
    timeout: 1500
```

### Addon version

v1.33.2-1

### Platform

Core
2023.11.2
Supervisor
2023.11.3
Operating System
11.1

### Logs of the issue (if applicable)

14:23:17] INFO: Preparing to start...
[14:23:18] INFO: Socat not enabled
[14:23:19] INFO: Starting Zigbee2MQTT...
Zigbee2MQTT:info  2023-11-19 14:23:23: Logging to console and directory: '/config/zigbee2mqtt/log/2023-11-19.14-23-23' filename: log.txt
Zigbee2MQTT:info  2023-11-19 14:23:23: Starting Zigbee2MQTT version 1.33.2 (commit #unknown)
Zigbee2MQTT:info  2023-11-19 14:23:23: Starting zigbee-herdsman (0.21.0)
Assertion failed: Command (setConfigurationValue) returned unexpected state: [object Object]
