### ISSUE TITLE
Exception while calling fromZigbee converter

### ISSUE THREAD

**Issue by diaz66** [zigbee2mqtt/hassio-zigbee2mqtt#559]
### Description of the issue

- After switching to version 1.35.1-1 I started to encounter the error in question.
- From this moment on, zigbee2mqtt no longer sends anything to home assistant (Mosquitto broker)
-The device generating the error is a [PJ-MGW1203](https://www.zigbee2mqtt.io/devices/PJ-MGW1203.html#tuya-pj-mgw1203) 
- The system block occurs 2/3 times a day randomly

### Addon version

v1.35.1-1

### Platform

Core 2024.1.2
Supervisor 2023.12.0
Operating System 11.4

**my configuration**
```
homeassistant: true
mqtt:
  server: mqtt://core-mosquitto
  user: *****
  password: *****
serial:
  port: /dev/ttyACM0
  adapter: ezsp
frontend:
  port: 8099
advanced:
  homeassistant_legacy_entity_attributes: false
  legacy_api: false
  legacy_availability_payload: false
  log_syslog:
    app_name: Zigbee2MQTT
    eol: /n
    host: localhost
    localhost: localhost
    path: /dev/log
    pid: process.pid
    port: 123
    protocol: tcp4
    type: '5424'
  channel: 25
  log_level: info
device_options:
  legacy: false
devices:
  '0xe0798dfffea826ff':
    friendly_name: Router ZBDongle-E
  '0x003c84fffef0ecca':
    friendly_name: ZigBee Termosifone Camera Mat
  '0xa4c1380483ecb1b5':
    friendly_name: ZigBee Termometro Sala
  '0xa4c13878a044e674':
    friendly_name: ZigBee Termometro Soggiorno
  '0xa4c138fa78091d52':
    friendly_name: ZigBee Presa Frigorifero
  '0xa4c138bab31104b2':
    friendly_name: ZigBee Luce Terrazzo Camera Matrimoniale
  '0xa4c13831eaf7dbba':
    friendly_name: ZigBee Tapparella1 Sala
  '0xa4c138c3b27cee34':
    friendly_name: ZigBee Lampada Luna
  '0xa4c138bcec51d379':
    friendly_name: ZigBee Luce Sala
  '0xa4c1383aad8d029e':
    friendly_name: ZigBee Presa Sala TV
  '0xa4c138e52b567c58':
    friendly_name: ZigBee Presa Camera Grande Play
  '0xa4c138fe60c0d996':
    friendly_name: ZigBee Presa Camera Grande PC
  '0xa4c138ddd7cffecf':
    friendly_name: ZigBee Presa Soggiorno TV
  '0xa4c1388b23a3bf79':
    friendly_name: ZigBee Porta Frigo
  '0xa4c1382e0495eafe':
    friendly_name: ZigBee Porta Congelatore
  '0xa4c138a06155b4d5':
    friendly_name: ZigBee Luce Camera Grande
    power_precision: 1
    power_calibration: 3000
    current_calibration: 100
    energy_precision: 1
    voltage_precision: 1
    current_precision: 1
    state_action: true
  '0x70ac08fffe366ce1':
    friendly_name: Zigbee Power Meter Casa
    energy_precision: 2
    energy_calibration: 1
    current_precision: 2
    power_precision: 2
    voltage_precision: 2
    current_calibration: 1
    power_calibration: 1
    voltage_calibration: 1
  '0xa4c13851ad8d6f9b':
    friendly_name: ZigBee Termometro Esterno
    temperature_precision: 1
  '0xa4c1383a8254d9ae':
    friendly_name: ZigBee Termometro Camera Grande
  '0xa4c1382c28303539':
    friendly_name: ZigBee Termometro Camera Piccola
  '0xa4c13818fe6c6cd3':
    friendly_name: ZigBee Porta Ingresso Interna
  '0xa4c13800b40af798':
    friendly_name: ZigBee Porta Ingresso Esterna
  '0xa4c1380aa558d939':
    friendly_name: ZigBee Presa Camera Piccola
  '0xa4c138af878589ac':
    friendly_name: ZigBee Presa Camera Mat
  '0xa4c138351db79811':
    friendly_name: ZigBee Sensore Acqua Esterno
  '0x4c5bb3fffe2eeaf7':
    friendly_name: Zigbee Power Meter Cucina
    description: Cappa Cucina + le due prese
    current_calibration: 1
    current_precision: 2
    power_precision: 2
    voltage_precision: 2
    energy_precision: 2
    power_calibration: 1
    voltage_calibration: 1
    energy_calibration: 1
  '0x00124b00291ffbe0':
    friendly_name: ZigBee Termometro Camera Mat
blocklist: []
availability: false
```

### Logs of the issue (if applicable)

[log.txt](https://github.com/zigbee2mqtt/hassio-zigbee2mqtt/files/13921076/log.txt)
**`error 2024-01-12 16:11:45: Exception while calling fromZigbee converter: Command 0x4c5bb3fffe2eeaf7/1 manuSpecificTuya.mcuGatewayConnectionStatus({"payloadSize":1,"payload":1}, {"sendWhen":"immediate","timeout":10000,"disableResponse":false,"disableRecovery":false,"disableDefaultResponse":false,"direction":0,"srcEndpoint":null,"reservedBits":0,"manufacturerCode":null,"transactionSequenceNumber":null,"writeUndiv":false}) failed (sendZclFrameToEndpointInternal error)}

`**
