### ISSUE TITLE
Zigbee2mqtt not starting zigbee-herdsman, SyntaxError: Unexpected token m in JSON

### ISSUE THREAD

**Issue by Sharper007** [zigbee2mqtt/hassio-zigbee2mqtt#57]
**Description of problem:**
Zigbee2mqtt simply stopped functioning and will not connect. No system updates or changes were occurring, connection just failed. I've re-flashed the firmware on the CC2531 and removed/reinstalled zigbee2mqtt, but no change. I've reset the entire system several times. This is running in a Synology VM and has worked fine for more than a month since transitioning from a Docker setup. Z-Wave Js to mqtt, Mosquitto broker, and Node Red are all still functioning properly.
**Zigbee2mqtt add-on version (if edge, please report commit hash):**
```
zigbee2mqtt@1.18.1 start /app
```

**Your entire configuration from the frontend (with sensitive fields redacted)**:
```
data_path: /share/zigbee2mqtt
external_converters: []
devices: devices.yaml
groups: groups.yaml
homeassistant: true
permit_join: true
mqtt:
  base_topic: zigbee2mqtt
  server: 'mqtt://10.0.xxx.xxx:1883'
  user: <user_id>
  password: <user_pass>
serial:
  port: >-
    /dev/serial/by-id/usb-Texas_Instruments_TI_CC2531_USB_CDC___0X00124B0018E2AC54-if00
  disable_led: false
advanced:
  log_level: debug
  log_directory: /share/log/%TIMESTAMP%
  log_file: log.txt
  log_output: file
  pan_id: 6754
  channel: 20
  network_key:
    - 1
    - 3
    - 5
    - 7
    - 9
    - 11
    - 13
    - 15
    - 0
    - 2
    - 4
    - 6
    - 8
    - 10
    - 12
    - 13
  availability_blocklist: []
  availability_passlist: []
device_options: {}
blocklist: []
passlist: []
queue: {}
frontend:
  host: 10.0.xxx.xxx
  port: 8099
experimental: {}
socat:
  enabled: false
  master: 'pty,raw,echo=0,link=/tmp/ttyZ2M,mode=777'
  slave: 'tcp-listen:8485,keepalive,nodelay,reuseaddr,keepidle=1,keepintvl=1,keepcnt=5'
  options: '-d -d'
  log: true

```

**Running platform (details from Suypervisor > System)**
```
Core: core-2021.3.2
Supervisor: supervisor-2021.03.4
Operating System: HassOS 5.12
```

**Your logs from Home Assistant Supervisor**
```
> zigbee2mqtt@1.18.1 start /app
> node index.js
Zigbee2MQTT:debug 2021-03-08 11:14:42: Loaded state from file /share/zigbee2mqtt/state.json
Zigbee2MQTT:info  2021-03-08 11:14:42: Logging to console and directory: '/share/log/2021-03-08.11-14-41' filename: log.txt
Zigbee2MQTT:debug 2021-03-08 11:14:42: Removing old log directory '/share/log/2021-03-08.11-13-11'
Zigbee2MQTT:info  2021-03-08 11:14:42: Starting Zigbee2MQTT version 1.18.1 (commit #1.18.1)
Zigbee2MQTT:info  2021-03-08 11:14:42: Starting zigbee-herdsman (0.13.71)
Zigbee2MQTT:debug 2021-03-08 11:14:43: Using zigbee-herdsman with settings: '{"adapter":{"concurrent":null,"delay":null},"backupPath":"/share/zigbee2mqtt/coordinator_backup.json","databaseBackupPath":"/share/zigbee2mqtt/database.db.backup","databasePath":"/share/zigbee2mqtt/database.db","network":{"channelList":[20],"extendedPanID":[221,221,221,221,221,221,221,221],"networkKey":"HIDDEN","panID":6754},"serialPort":{"path":"/dev/serial/by-id/usb-Texas_Instruments_TI_CC2531_USB_CDC___0X00124B0018E2AC54-if00"}}'
Zigbee2MQTT:error 2021-03-08 11:14:43: Error while starting zigbee-herdsman
Zigbee2MQTT:error 2021-03-08 11:14:43: Failed to start zigbee
Zigbee2MQTT:error 2021-03-08 11:14:43: Exiting...
Zigbee2MQTT:error 2021-03-08 11:14:43: SyntaxError: Unexpected token m in JSON at position 73
    at JSON.parse (<anonymous>)
    at Function.open (/app/node_modules/zigbee-herdsman/dist/controller/database.js:17:35)
    at Controller.<anonymous> (/app/node_modules/zigbee-herdsman/dist/controller/controller.js:106:48)
    at Generator.next (<anonymous>)
    at fulfilled (/app/node_modules/zigbee-herdsman/dist/controller/controller.js:24:58)
    at processTicksAndRejections (internal/process/task_queues.js:93:5)
npm ERR! code ELIFECYCLE
npm ERR! errno 1
npm ERR! zigbee2mqtt@1.18.1 start: `node index.js`
npm ERR! Exit status 1
npm ERR! 
npm ERR! Failed at the zigbee2mqtt@1.18.1 start script.
npm ERR! This is probably not a problem with npm. There is likely additional logging output above.

```
