### ISSUE TITLE
Unknown option 'initialdelay' for Zigbee2mqtt

### ISSUE THREAD

**Issue by danbayliss** [zigbee2mqtt/hassio-zigbee2mqtt#59]
**Description of problem:**
In my Home Assistant Supervisor log it has the following entry 
`21-03-11 16:59:20 WARNING (MainThread) [supervisor.addons.options] Unknown option 'initialdelay' for Zigbee2mqtt (7ad98f9c_zigbee2mqtt)`

**Zigbee2mqtt add-on version (if edge, please report commit hash):**
```
1.18.1-1 
```

**Your entire configuration from the frontend (with sensitive fields redacted)**:
```
data_path: /share/zigbee2mqtt
external_converters: []
devices: devices.yaml
groups: groups.yaml
homeassistant: false
permit_join: false
mqtt:
  base_topic: zigbee2mqtt
  server: 'mqtt://192.168.0.3:1883'
  user: 
  password: 
serial:
  adapter: deconz
  port: /dev/ttyACM0
advanced:
  availability_timeout: 600
  log_level: info
  pan_id: 6754
  channel: 11
  network_key:
    - 1
    - 3
    - 5
    - 7
    - 9
    - 11
    - 13
    - 15
    - 0
    - 2
    - 4
    - 6
    - 8
    - 10
    - 12
    - 13
  availability_blocklist: []
  availability_passlist: []
device_options: {}
blocklist: []
passlist: []
queue: {}
frontend:
  port: 8099
experimental:
  new_api: true
socat:
  enabled: false
  master: 'pty,raw,echo=0,link=/dev/ttyZ2M,mode=777'
  slave: 'tcp-listen:8485,keepalive,nodelay,reuseaddr,keepidle=1,keepintvl=1,keepcnt=5'
  restartdelay: 1
  initialdelay: 1
  options: '-d -d'
  log: false

```

**Running platform (details from Suypervisor > System)**
```
// Example
Core: core-2021.3.3
Supervisor: supervisor-2021.03.4
Operating System: Ubuntu
```

**Your logs from Home Assistant Supervisor**
```
As above
```
