### ISSUE TITLE
zigbee-herdsman fails to connect to adapter

### ISSUE THREAD

**Issue by Xaymar** [zigbee2mqtt/hassio-zigbee2mqtt#596]
### Description of the issue

A fresh install of Home Assistant OS and the Zigbee2MQTT seems to be unable to open/connect to the adapter. This works just fine when not running in Home Assistant OS, possibly being a problem with the container's rights.

```
data_path: /config/zigbee2mqtt
socat:
  enabled: false
  master: pty,raw,echo=0,link=/tmp/ttyZ2M,mode=777
  slave: tcp-listen:8485,keepalive,nodelay,reuseaddr,keepidle=1,keepintvl=1,keepcnt=5
  options: "-d -d"
  log: false
mqtt: {}
serial:
  port: /dev/ttyACM0
```
(Forgot to paste this into the field in the original post.)

### Addon version

1.36.1-1

### Platform

Core 2024.4.3
Supervisor 2024.04.0
Operating System 12.2
Frontend 20240404.2
Sonoff ZBDongle-E running the firmware recommended by Zigbee2MQTT

### Logs of the issue (if applicable)

[01:20:45] INFO: Preparing to start...
[01:20:45] INFO: Socat not enabled
[01:20:47] INFO: Starting Zigbee2MQTT...
Zigbee2MQTT:info  2024-04-15 01:20:53: Logging to console and directory: '/config/zigbee2mqtt/log/2024-04-15.01-20-53' filename: log.txt
Zigbee2MQTT:info  2024-04-15 01:20:53: Starting Zigbee2MQTT version 1.36.1 (commit #unknown)
Zigbee2MQTT:info  2024-04-15 01:20:53: Starting zigbee-herdsman (0.40.3)
Zigbee2MQTT:error 2024-04-15 01:21:14: Error while starting zigbee-herdsman
Zigbee2MQTT:error 2024-04-15 01:21:14: Failed to start zigbee
Zigbee2MQTT:error 2024-04-15 01:21:14: Check https://www.zigbee2mqtt.io/guide/installation/20_zigbee2mqtt-fails-to-start.html for possible solutions
Zigbee2MQTT:error 2024-04-15 01:21:14: Exiting...
Zigbee2MQTT:error 2024-04-15 01:21:14: Error: Failed to connect to the adapter (Error: SRSP - SYS - ping after 6000ms)
    at ZStackAdapter.start (/app/node_modules/zigbee-herdsman/src/adapter/z-stack/adapter/zStackAdapter.ts:103:27)
    at Controller.start (/app/node_modules/zigbee-herdsman/src/controller/controller.ts:132:29)
    at Zigbee.start (/app/lib/zigbee.ts:62:27)
    at Controller.start (/app/lib/controller.ts:109:27)
    at start (/app/index.js:107:5)
