### ISSUE TITLE
Dev branch can't load my configuration (string error) - stable works fine

### ISSUE THREAD

**Issue by ASNNetworks** [zigbee2mqtt/hassio-zigbee2mqtt#63]
**Description of problem:**
The dev branch can't load up my configuration suddenly. The error lies with devices.yaml and says it needs to be a string. The exact configuration works fine with stable branch (and has always worked with both dev and stable). This is how devices.yaml is setup (and what works under stable and previous dev).

Just to clarify: I switch between stable and dev now and then when I propose a change for dev. I ran dev for a while. Switched to stable and then switched to a dev (newer build than before) and that one doesn’t work. Stable works fine.
```
'0x90fd9ffffe67aa7b':
  friendly_name: Keuken Lamp Plafond 1
  transition: 0.4
```

**Zigbee2mqtt add-on version (if edge, please report commit hash):**
```
zigbee2mqtt@1.18.1start /app
```
**Configuration:**
```
data_path: /share/zigbee2mqtt
external_converters: []
devices: devices.yaml
groups: groups.yaml
homeassistant: true
permit_join: false
mqtt:
  base_topic: zigbee2mqtt
  server: 'mqtt://core-mosquitto'
  user:  [REDACTED]
  password:  [REDACTED]
serial:
  adapter: deconz
  disable_led: false
  port: >-
    /dev/serial/by-id/usb-dresden_elektronik_ingenieurtechnik_GmbH_ConBee_II_DE2133075-if00
advanced:
  log_level: debug
  last_seen: ISO_8601_local
  log_directory: /share/zigbee2mqtt/log/
  log_file: log.txt
  report: true
  pan_id: 62369
  channel: 25
  network_key: [REDACTED]
  availability_blocklist: []
  availability_passlist: []
device_options: {}
blocklist: []
passlist: []
queue: {}
frontend:
  port: 8099
experimental:
  new_api: true
socat:
  enabled: false
  master: 'pty,raw,echo=0,link=/dev/ttyZ2M,mode=777'
  slave: 'tcp-listen:8485,keepalive,nodelay,reuseaddr,keepidle=1,keepintvl=1,keepcnt=5'
  restartdelay: 1
  initialdelay: 1
  options: '-d -d'
  log: false```
```

**Running platform (details from Suypervisor > System)**

```
Core: core-2021.3.3
Supervisor: supervisor-2021.03.4
Operating System: Home Assistant OS 5.12
```

**Your logs from Home Assistant Supervisor**

```
[s6-init] making user provided files available at /var/run/s6/etc...exited 0.
[s6-init] ensuring user provided files have correct perms...exited 0.
[fix-attrs.d] applying ownership & permissions fixes...
[fix-attrs.d] done.
[cont-init.d] executing container initialization scripts...
[cont-init.d] socat.sh: executing... 
[13:12:52] INFO: Socat not enabled, marking service as down
[cont-init.d] socat.sh: exited 0.
[cont-init.d] zigbee2mqtt.sh: executing... 
[13:12:53] INFO: MQTT available, fetching server detail ...
[13:12:53] INFO: Previous config file found, checking backup
[13:12:53] INFO: Creating backup config in '/share/zigbee2mqtt/.configuration.yaml.bk'
[13:12:53] INFO: Adjusting Zigbee2mqtt core yaml config with add-on quirks ...
[cont-init.d] zigbee2mqtt.sh: exited 0.
[cont-init.d] done.
[services.d] starting services
[services.d] done.
[13:12:55] INFO: Handing over control to Zigbee2mqtt Core ...
> zigbee2mqtt@1.18.1-dev start /app
> node index.js
!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!
            READ THIS CAREFULLY
Refusing to start because configuration is not valid, found the following errors:
- devices['0xd0cf5efffed82e95']['transition'] should be string
- devices['0x90fd9ffffe67aa7b']['transition'] should be string
- devices['0x000b57fffed96377']['transition'] should be string
- devices['0x000b57fffeeaff88']['transition'] should be string
- devices['0x90fd9ffffe6dfed5']['transition'] should be string
- devices['0x90fd9ffffe6fc60e']['transition'] should be string
- devices['0x00158d00012f5559']['transition'] should be string
- devices['0x00158d00013bcd7b']['transition'] should be string
- devices['0x00158d00013bcde0']['transition'] should be string
- devices['0x00158d00012ec354']['transition'] should be string
- devices['0xccccccfffecba5ce']['transition'] should be string
- devices['0xccccccfffe36abbf']['transition'] should be string
- devices['0xccccccfffe36009f']['transition'] should be string
- devices['0xccccccfffe31f456']['transition'] should be string
- devices['0x14b457fffe744c51']['transition'] should be string
- devices['0x00158d00012f558f']['transition'] should be string
- devices['0x00158d000126faf1']['transition'] should be string
- devices['0x00158d000126fb1f']['transition'] should be string
- devices['0x00158d00012ee7ae']['transition'] should be string
- devices['0x7cb03eaa0a074f90']['transition'] should be string
- devices['0x7cb03eaa00b03420']['transition'] should be string
- devices['0x00158d0001271b2b']['transition'] should be string
- devices['0x5c0272fffebe23d3']['reverse_direction'] should be string
- devices['0x7cb03eaa0a0749ed']['transition'] should be string
- devices['0x14b457fffe6be2fe']['legacy'] should be string
- devices['0x00158d00012ee461']['transition'] should be string
- devices['0x00158d00012f41a4']['transition'] should be string
- devices['0x847127fffe1b72fc']['reverse_direction'] should be string
- devices['0x00158d00012f40c1']['transition'] should be string
- devices['0xbc33acfffe8acbb3']['legacy'] should be string
- devices['0xbc33acfffec040dc']['transition'] should be string
- devices['0x7cb03eaa00b02f2f']['transition'] should be string
If you don't know how to solve this, read https://www.zigbee2mqtt.io/information/configuration.html
!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!
npm ERR! code ELIFECYCLE
npm ERR! errno 1
npm ERR! zigbee2mqtt@1.18.1-dev start: `node index.js`
npm ERR! Exit status 1
npm ERR! 
npm ERR! Failed at the zigbee2mqtt@1.18.1-dev start script.
npm ERR! This is probably not a problem with npm. There is likely additional logging output above.
npm ERR! A complete log of this run can be found in:
npm ERR!     /root/.npm/_logs/2021-03-13T12_12_57_341Z-debug.log
[13:12:57] INFO: Handing over control to Zigbee2mqtt Core ...
```
