### ISSUE TITLE
z2m: Error while starting zigbee-herdsman

### ISSUE THREAD

**Issue by pabloandrei** [zigbee2mqtt/hassio-zigbee2mqtt#653]
### Description of the issue

Hello everyone. I'm trying to start Zigbee2MQTT, but it returns this error: error: zh:zstack:znp: Failed to determine if the path is valid: 'Error: spawn udevadm ENOENT'

Does anyone have any tips?

Config:
```
data_path: /config/zigbee2mqtt
socat:
  enabled: false
  master: pty,raw,echo=0,link=/tmp/ttyZ2M,mode=777
  slave: tcp-listen:8485,keepalive,nodelay,reuseaddr,keepidle=1,keepintvl=1,keepcnt=5
  options: "-d -d"
  log: true
mqtt:
  server: mqtt://localhost:1883
serial:
  port: /dev/ttyUSB0
```

### Addon version

v1.40.2-1

### Platform

Core 2024.10.4
Supervisor 2024.10.3
Operating System 13.2

### Logs of the issue (if applicable)

[20:09:31] INFO: Preparing to start...
[20:09:32] INFO: Socat not enabled
[20:09:33] INFO: Starting Zigbee2MQTT...
Starting Zigbee2MQTT without watchdog.
[2024-10-31 20:09:35] info: 	z2m: Logging to console, file (filename: log.log)
[2024-10-31 20:09:35] info: 	z2m: Starting Zigbee2MQTT version 1.40.2 (commit #unknown)
[2024-10-31 20:09:35] info: 	z2m: Starting zigbee-herdsman (2.1.3)
[2024-10-31 20:09:35] error: 	zh:zstack:znp: Failed to determine if path is valid: 'Error: spawn udevadm ENOENT'
[2024-10-31 20:09:35] info: 	zh:zstack:znp: Opening SerialPort with {"path":"/dev/ttyUSB0","baudRate":115200,"rtscts":false,"autoOpen":false}
[2024-10-31 20:09:35] info: 	zh:zstack:znp: Serialport opened
[2024-10-31 20:09:35] info: 	zh:zstack:znp: Writing CC2530/CC2531 skip bootloader payload
[2024-10-31 20:09:36] info: 	zh:zstack:znp: Skip bootloader for CC2652/CC1352
[2024-10-31 20:09:55] error: 	z2m: Error while starting zigbee-herdsman
[2024-10-31 20:09:55] error: 	z2m: Failed to start zigbee
[2024-10-31 20:09:55] error: 	z2m: Check https://www.zigbee2mqtt.io/guide/installation/20_zigbee2mqtt-fails-to-start.html for possible solutions
[2024-10-31 20:09:55] error: 	z2m: Exiting...
[2024-10-31 20:09:55] error: 	z2m: Error: Failed to connect to the adapter (Error: SRSP - SYS - ping after 6000ms)
    at ZStackAdapter.start (/app/node_modules/zigbee-herdsman/src/adapter/z-stack/adapter/zStackAdapter.ts:113:27)
    at Controller.start (/app/node_modules/zigbee-herdsman/src/controller/controller.ts:137:29)
    at Zigbee.start (/app/lib/zigbee.ts:69:27)
    at Controller.start (/app/lib/controller.ts:161:27)
    at start (/app/index.js:154:5)
