### ISSUE TITLE
Z2M won´t start - required add-on configuration ‘data_path’ option is missing!

### ISSUE THREAD

**Issue by kyrgorsh** [zigbee2mqtt/hassio-zigbee2mqtt#662]
### Description of the issue

Hi 
I´m running HAOS and I’m using the default data_path of /config/zigbee2mqtt. Here’s my current Z2mqtt configuration:

```
data_path: /config/zigbee2mqtt
socat:
  enabled: false
  master: pty,raw,echo=0,link=/tmp/ttyZ2M,mode=777
  slave: tcp-listen:8485,keepalive,nodelay,reuseaddr,keepidle=1,keepintvl=1,keepcnt=5
  options: "-d -d"
  log: false
mqtt:
  server: mqtt://localhost:1883
  user: mqttuser
  password: password
serial:
  port: >-
    /dev/serial/by-id/usb-ITEAD_SONOFF_Zigbee_3.0_USB_Dongle_Plus_V2_20230508112711-if00
  adapter: ezsp
```

When I try to Start the add-on, it will not and the log is filled with repetitive errors:

```
INFO: Preparing to start...
ERROR: Something went wrong contacting the API
FATAL: A required add-on configuration option is missing!
FATAL: Please set a value for the 'data_path' option.
FATAL: If unsure, check the add-on manual for more information
```

### Addon version

1.41.0-1

### Platform

Core: 2024.11.3
Supervisor: 2024.11.4
Operating System: 13.2
Frontend: 20241106.2
