### ISSUE TITLE
Set the speed of the roller shutter using Home Assistant

### ISSUE THREAD

**Issue by jeffconrad18** [zigbee2mqtt/hassio-zigbee2mqtt#70]
**Description of problem:**
I can only control the position of my roller shutter [https://www.zigbee2mqtt.io/devices/TS0601_cover.html], which I have connected to Home Assistant via zigbee, but it is also possible to set the speed and the status (open, close) in Zigbee2Mqtt.
However, these values ​​only appear as attributes in Home Assistant and cannot be changed. Above all, the speed that the roller shutter needs to be closed is at a speed of "1" 3 minutes and at a speed of "255" 20 seconds, which incidentally also makes a large difference in volume of the motor. (e.g. important in the morning and in the evening)

**Zigbee2mqtt add-on version (if edge, please report commit hash):**
```
current version: 1.17.1-4 
```

**Your entire configuration from the frontend (with sensitive fields redacted)**:
```
data_path: /config/zigbee2mqtt
external_converters: []
devices: devices.yaml
groups: groups.yaml
homeassistant: true
permit_join: true
mqtt:
  base_topic: zigbee2mqtt
  server: 'mqtt://192.168.178.128:1883'
  user: pi
  password: smarthome2020
serial:
  disable_led: true
  port: >-
    /dev/serial/by-id/usb-Texas_Instruments_TI_CC2531_USB_CDC___0X00124B0018E334C7-if00
advanced:
  log_level: warn
  pan_id: 6754
  channel: 11
  network_key:
    - 1
    - 3
    - 5
    - 7
    - 9
    - 11
    - 13
    - 15
    - 0
    - 2
    - 4
    - 6
    - 8
    - 10
    - 12
    - 13
  availability_blocklist: []
  availability_passlist: []
device_options: {}
blocklist: []
passlist: []
queue: {}
frontend:
  port: 8099
experimental: {}
socat:
  enabled: false
  master: 'pty,raw,echo=0,link=/tmp/ttyZ2M,mode=777'
  slave: 'tcp-listen:8485,keepalive,nodelay,reuseaddr,keepidle=1,keepintvl=1,keepcnt=5'
  options: '-d -d'
  log: false

```

**Running platform (details from Suypervisor > System)**
```
// Example
Core: core-2021.3.4
Supervisor: supervisor-2021.03.6
Operating System: Home Assistant OS 5.12
```

![Zigbee3](https://user-images.githubusercontent.com/78684384/111904874-459b8d80-8a49-11eb-8806-f67e7e2664c0.PNG)
![Zigbee2](https://user-images.githubusercontent.com/78684384/111904876-46342400-8a49-11eb-9f1b-961f43263143.PNG)
![Zigbee1](https://user-images.githubusercontent.com/78684384/111904877-46ccba80-8a49-11eb-89c9-5558b2c924e6.PNG)
