### ISSUE TITLE
Cannot bind since button is greyed out

### ISSUE THREAD

**Issue by ronniebee** [zigbee2mqtt/hassio-zigbee2mqtt#71]
**Description of problem:**
@Koenkk 

I created a group of 2 ikea light which I want to bind to the ikea witch (tadfri on/off) but the bind button is "greyed out". I did unbind it from the default group (went ok). But when I want to bind the switch to the group (on/off option) I can't select the blue button.

![image](https://user-images.githubusercontent.com/7029899/111908806-f0687780-8a5a-11eb-9ab9-55aee1440a4e.png)

**Zigbee2mqtt add-on version (if edge, please report commit hash):**
```
Current version: 1.18.1-2 

```

**Your entire configuration from the frontend (with sensitive fields redacted)**:
```
data_path: /config/zigbee2mqtt
external_converters: []
devices: devices.yaml
groups: groups.yaml
homeassistant: true
permit_join: false
mqtt:
  base_topic: zigbee2mqtt
serial:
  port: /dev/ttyUSB1
advanced:
  log_level: warn
  pan_id: 6753
  channel: 11
  network_key:
    - 1
    - 3
    - 5
    - 7
    - 9
    - 11
    - 13
    - 15
    - 0
    - 2
    - 4
    - 6
    - 8
    - 10
    - 12
    - 13
  availability_blocklist: []
  availability_passlist: []
device_options: {}
blocklist: []
passlist: []
queue: {}
frontend:
  port: 8099
experimental: {}
socat:
  enabled: false
  master: 'pty,raw,echo=0,link=/tmp/ttyZ2M,mode=777'
  slave: 'tcp-listen:8485,keepalive,nodelay,reuseaddr,keepidle=1,keepintvl=1,keepcnt=5'
  options: '-d -d'
  log: false
```

**Running platform (details from Suypervisor > System)**
```

core-2021.3.4
supervisor-2021.03.6
Debian GNU/Linux 10 (buster)
Docker versie 20.10.5
```

**Your logs from Home Assistant Supervisor**
```
21-03-21 13:43:16 INFO (MainThread) [supervisor.resolution.check] Starting system checks with state CoreState.RUNNING
21-03-21 13:43:16 INFO (MainThread) [supervisor.resolution.checks.base] Run check for IssueType.PWNED/ContextType.ADDON
21-03-21 13:43:16 INFO (MainThread) [supervisor.resolution.checks.base] Run check for IssueType.FREE_SPACE/ContextType.SYSTEM
21-03-21 13:43:16 INFO (MainThread) [supervisor.resolution.checks.base] Run check for IssueType.SECURITY/ContextType.CORE
21-03-21 13:43:16 INFO (MainThread) [supervisor.resolution.check] System checks complete
21-03-21 13:43:16 INFO (MainThread) [supervisor.resolution.fixup] Starting system autofix at state CoreState.RUNNING
21-03-21 13:43:16 INFO (MainThread) [supervisor.resolution.fixup] System autofix complete
21-03-21 13:45:50 INFO (MainThread) [supervisor.homeassistant.api] Updated Home Assistant API token
21-03-21 14:06:32 INFO (MainThread) [supervisor.host.info] Updating local host information
21-03-21 14:06:32 INFO (MainThread) [supervisor.host.services] Updating service information
21-03-21 14:06:32 INFO (MainThread) [supervisor.host.network] Updating local network information
21-03-21 14:06:39 INFO (MainThread) [supervisor.host.sound] Updating PulseAudio information
21-03-21 14:06:39 INFO (MainThread) [supervisor.host] Host information reload complete

and mqtt

Error Nothing to bind from 'Wc schakelaar' to 'Coordinator'
Error Nothing to bind

```
