### ISSUE TITLE
Z2M add-on keeps generating warning message zigbee_herdsman_debug

### ISSUE THREAD

**Issue by rp2019433** [zigbee2mqtt/hassio-zigbee2mqtt#732]
### Description of the issue

I've seen many warning messages on Supervisor Log from Home Asssistant.

```
WARNING (MainThread) [supervisor.addons.options] Option 'zigbee_herdsman_debug' does not exist in the schema for Zigbee2MQTT (98df4511_zigbee2mqtt)
```

But there isn't any `zigbee_herdsman_debug` statement in zigbee2mqtt/configuration.yaml file.

```
homeassistant:
  enabled: true
  last_seen: ISO_8601_local
  log_syslog:
    app_name: Zigbee2MQTT
    eol: /n
    host: localhost
    localhost: localhost
    path: /dev/log
    pid: process.pid
    port: 514
    protocol: udp4
    type: '5424'
  transmit_power: 14
  channel: 20
mqtt:
  server: mqtt://core-mosquitto:1883
  user: XXXX
  password: XXXX
frontend:
  enabled: true
  port: 8099
serial:
  port: >-
    /dev/serial/by-id/usb-ITEAD_SONOFF_Zigbee_3.0_USB_Dongle_Plus_V2
  adapter: ember
  baudrate: 230400
  rtscts: false
device_options: {}
devices:
availability:
  enabled: true
version: 4
```

I found this [PR 21984](https://github.com/Koenkk/zigbee2mqtt/pull/21984), but I double checked and I dont't have any configuration related to zigbee_herdsman_debug.

How do I get rid of these messages?

### Addon version

v2.1.1-1

### Platform

Core: 2025.2.4
Supervisor: 2025.02.1
Operating System: 14.2
