### ISSUE TITLE
dict object has no element Undefined when rendering 

### ISSUE THREAD

**Issue by nighthawk321** [zigbee2mqtt/hassio-zigbee2mqtt#86]
I updated home assistant core to 2021.4 with supervisor and hassio-zigbee2mqtt. It is running on Ubuntu 20.4 with docker. Since the update I have started to get this error many times-

Template variable warning: dict object has no element Undefined when rendering '{% set values = {'idle':'off','heat':'heating','cool':'cooling','fan only':'fan'} %}{{ values[value_json.running_state] }}'

I believe it to be due to my zigbee Spirit Zigbee wireless heater thermostat which was added via the added via the discovery automation which I added when I followed the installation guide. 

Sorry if this wrong to add this issue here, someone on home assistant discord suggested it

Zigbee2mqtt add-on version 1.18.1-1
```
``

**Your entire configuration from the frontend (with sensitive fields redacted)**:
data_path: /share/zigbee2mqtt
external_converters: []
devices: '[]'
groups: groups.yaml
homeassistant: true
permit_join: true
mqtt:
  base_topic: zigbee2mqtt
  server: 'mqtt://homeassistant'
  user: user
  password: 'password'
serial:
  port: /dev/ttyACM0
advanced:
  pan_id: 6754
  channel: 11
  network_key:
    - 1
    - 3
    - 5
    - 7
    - 9
    - 11
    - 13
    - 15
    - 0
    - 2
    - 4
    - 6
    - 8
    - 10
    - 12
    - 13
  availability_blocklist: []
  availability_passlist: []
device_options: {}
blocklist: []
passlist: []
queue: {}
frontend:
  port: 8099
experimental: {}
socat:
  enabled: false
  master: 'pty,raw,echo=0,link=/dev/ttyZ2M,mode=777'
  slave: 'tcp-listen:8485,keepalive,nodelay,reuseaddr,keepidle=1,keepintvl=1,keepcnt=5'
  restartdelay: 1
  initialdelay: 1
  options: '-d -d'
  log: false
```

**Running platform (details from Suypervisor > System)**
```
// Example
Core: core-2021.4.3
Supervisor: supervisor-2021.03.9
Operating System: Ubuntu 20.4 with docker supervised (dedicated machine)
```

**Your logs from Home Assistant Supervisor**
```
Logger: homeassistant.helpers.template
Source: helpers/template.py:1335
First occurred: 16:41:05 (6 occurrences)
Last logged: 16:41:05

Template variable warning: dict object has no element Undefined when rendering '{% set values = {'idle':'off','heat':'heating','cool':'cooling','fan only':'fan'} %}{{ values[value_json.running_state] }}'
```
