### ISSUE TITLE
Exception in state_received

### ISSUE THREAD

**Issue by DavyRoswinkel** [zigbee2mqtt/hassio-zigbee2mqtt#97]
**Description of problem:**
Since +/- a week I need to tap every LIDL bulb twice (lovelacedashboard) to match the state.
The error log shows an exception in state_received. 
Looks like it has something to do with each other.
How to solve this problem? ( error log added at the end)

**Zigbee2mqtt add-on version (if edge, please report commit hash):**
```
1.18.2-dev commit: e4d8686
```

**Your entire configuration from the frontend (with sensitive fields redacted)**:
```
data_path: /share/zigbee2mqtt
external_converters: []
devices: devices.yaml
groups: groups.yaml
homeassistant: true
permit_join: false
mqtt:
  base_topic: zigbee2mqtt
  server: 'mqtt://192.168.1.55:1883'
  user: *****
  password: ******
serial:
  adapter: deconz
  port: >-
    /dev/serial/by-id/usb-dresden_elektronik_ingenieurtechnik_GmbH_ConBee_II_DE2403707-if00
advanced:
  log_level: info
  pan_id: 6754
  channel: 11
  network_key:
    - 1
    - 3
    - 5
    - 7
    - 9
    - 11
    - 13
    - 15
    - 0
    - 2
    - 4
    - 6
    - 8
    - 10
    - 12
    - 13
  availability_blocklist: []
  availability_passlist: []
device_options: {}
blocklist: []
passlist: []
queue: {}
frontend:
  port: 8099
experimental: {}
socat:
  enabled: false
  master: 'pty,raw,echo=0,link=/tmp/ttyZ2M,mode=777'
  slave: 'tcp-listen:8485,keepalive,nodelay,reuseaddr,keepidle=1,keepintvl=1,keepcnt=5'
  options: '-d -d'
  log: false
```

**Running platform (details from Suypervisor > System)**
```
## System Health

version | core-2021.4.6
-- | --
installation_type | Home Assistant OS
dev | false
hassio | true
docker | true
virtualenv | false
python_version | 3.8.7
os_name | Linux
os_version | 5.4.83-v8
arch | aarch64
timezone | Europe/Amsterdam

<details><summary>Home Assistant Community Store</summary>

GitHub API | ok
-- | --
Github API Calls Remaining | 4830
Installed Version | 1.12.1
Stage | running
Available Repositories | 845
Installed Repositories | 26

</details>

<details><summary>Home Assistant Cloud</summary>

logged_in | true
-- | --
subscription_expiration | 17 mei 2021 02:00
relayer_connected | true
remote_enabled | true
remote_connected | true
alexa_enabled | false
google_enabled | true
can_reach_cert_server | ok
can_reach_cloud_auth | ok
can_reach_cloud | ok

</details>

<details><summary>Home Assistant Supervisor</summary>

host_os | Home Assistant OS 5.13
-- | --
update_channel | stable
supervisor_version | supervisor-2021.04.0
docker_version | 19.03.15
disk_total | 116.7 GB
disk_used | 25.1 GB
healthy | true
supported | true
board | rpi4-64
supervisor_api | ok
version_api | ok
installed_addons | Check Home Assistant configuration (3.6.0), File editor (5.3.0), Grafana (6.3.2), Home Assistant Google Drive Backup (0.104.2), InfluxDB (4.0.6), Samba share (9.3.1), Terminal & SSH (9.1.0), FTP (4.1.0), TimescaleDB (1.1.6), DSMR Reader (0.4.2), phpMyAdmin (0.4.0), Visual Studio Code (3.3.0), MariaDB (2.3.0), ESPHome (1.16.2), Node-RED (9.0.1), Mosquitto broker (5.1.1), TooGoodToGo Home Assistant MQTT Bridge (1.6.0), Zigbee2mqtt Edge (edge)

</details>

<details><summary>Lovelace</summary>

dashboards | 2
-- | --
resources | 8
views | 30
mode | storage

</details>
```

Error log:
Logger: homeassistant.util.logging
Source: util/logging.py:101
First occurred: 08:15:41 (26 occurrences)
Last logged: 10:20:30

Exception in state_received when handling msg on 'zigbee2mqtt/Lamp Gang': '{"brightness":254,"color":{"x":0.510741103773325,"y":0.414986678216401},"color_temp":464,"linkquality":null,"state":"OFF"}' Traceback (most recent call last): File "/usr/src/homeassistant/homeassistant/components/mqtt/debug_info.py", line 32, in wrapper msg_callback(msg) File "/usr/src/homeassistant/homeassistant/components/mqtt/light/schema_json.py", line 306, in state_received self._update_color(values) File "/usr/src/homeassistant/homeassistant/components/mqtt/light/schema_json.py", line 245, in _update_color color_mode = values["color_mode"] KeyError: 'color_mode'
Exception in state_received when handling msg on 'zigbee2mqtt/Lamp Keuken Tafel': '{"brightness":254,"color":{"x":0.510741103773325,"y":0.414986678216401},"color_temp":464,"linkquality":null,"state":"OFF"}' Traceback (most recent call last): File "/usr/src/homeassistant/homeassistant/components/mqtt/debug_info.py", line 32, in wrapper msg_callback(msg) File "/usr/src/homeassistant/homeassistant/components/mqtt/light/schema_json.py", line 306, in state_received self._update_color(values) File "/usr/src/homeassistant/homeassistant/components/mqtt/light/schema_json.py", line 245, in _update_color color_mode = values["color_mode"] KeyError: 'color_mode'
Exception in state_received when handling msg on 'zigbee2mqtt/Lamp Keuken Koken': '{"brightness":254,"color":{"x":0.510741103773325,"y":0.414986678216401},"color_temp":464,"linkquality":null,"state":"OFF"}' Traceback (most recent call last): File "/usr/src/homeassistant/homeassistant/components/mqtt/debug_info.py", line 32, in wrapper msg_callback(msg) File "/usr/src/homeassistant/homeassistant/components/mqtt/light/schema_json.py", line 306, in state_received self._update_color(values) File "/usr/src/homeassistant/homeassistant/components/mqtt/light/schema_json.py", line 245, in _update_color color_mode = values["color_mode"] KeyError: 'color_mode'
Exception in state_received when handling msg on 'zigbee2mqtt/Lamp Kantoor': '{"brightness":254,"color":{"x":0.509709837429556,"y":0.415043632474748},"color_temp":461,"linkquality":50,"state":"ON"}' Traceback (most recent call last): File "/usr/src/homeassistant/homeassistant/components/mqtt/debug_info.py", line 32, in wrapper msg_callback(msg) File "/usr/src/homeassistant/homeassistant/components/mqtt/light/schema_json.py", line 306, in state_received self._update_color(values) File "/usr/src/homeassistant/homeassistant/components/mqtt/light/schema_json.py", line 245, in _update_color color_mode = values["color_mode"] KeyError: 'color_mode'
Exception in state_received when handling msg on 'zigbee2mqtt/Lamp Kantoor': '{"brightness":254,"color":{"x":0.509709837429556,"y":0.415043632474748},"color_temp":461,"linkquality":50,"state":"OFF"}' Traceback (most recent call last): File "/usr/src/homeassistant/homeassistant/components/mqtt/debug_info.py", line 32, in wrapper msg_callback(msg) File "/usr/src/homeassistant/homeassistant/components/mqtt/light/schema_json.py", line 306, in state_received self._update_color(values) File "/usr/src/homeassistant/homeassistant/components/mqtt/light/schema_json.py", line 245, in _update_color color_mode = values["color_mode"] KeyError: 'color_mode'
