### ISSUE TITLE
Not able to set "device_options" in add on configuration

### ISSUE THREAD

**Issue by darootler** [zigbee2mqtt/hassio-zigbee2mqtt#99]
**Description of problem:**
We already discussed this a bit [here](https://github.com/Koenkk/zigbee2mqtt/discussions/7249). I am not able to set "device_options" like this:

```
data_path: /share/zigbee2mqtt
external_converters: []
devices: devices.yaml
groups: groups.yaml
homeassistant: true
permit_join: false
mqtt:
  base_topic: zigbee
  password: '!secret zigbee_password'
  server: 'mqtt://core-mosquitto:1883'
  user: '!secret zigbee_username'
serial:
  port: /dev/serial/by-id/usb-1a86_USB_Serial-if00-port0
advanced:
  availability_timeout: 600
  channel: 25
  last_seen: ISO_8601_local
  log_level: warn
  network_key: []
  network_key_string: '!secret zigbee_network_key'
  pan_id: '!secret zigbee_pan_id'
  report: true
device_options:
  homeassistant:
    json_attributes_topic: null
blocklist: []
passlist: []
queue: {}
frontend:
  port: 8099
experimental: {}
socat:
  enabled: false
```

The add on will write the configuration.yaml file like this:

```
{
  "external_converters": [],
  "devices": [
    "devices.yaml"
  ],
  "groups": [
    "groups.yaml"
  ],
  "homeassistant": true,
  "permit_join": false,
  "mqtt": {
    "base_topic": "zigbee",
    "password": "xxx",
    "server": "mqtt://core-mosquitto:1883",
    "user": "xxx"
  },
  "serial": {
    "port": "/dev/serial/by-id/usb-1a86_USB_Serial-if00-port0"
  },
  "advanced": {
    "availability_timeout": 600,
    "channel": 25,
    "last_seen": "ISO_8601_local",
    "log_level": "warn",
    "network_key": [
      xx,
      xx,
      xx,
      xxx,
      xxx,
      xxx,
      xxx,
      xxx,
      xxx,
      xxx,
      xxx,
      xxx,
      xxx,
      xxx,
      xxx,
      xx
    ],
    "pan_id": xxxx,
    "report": true
  },
  "device_options": {},
  "blocklist": [],
  "passlist": [],
  "queue": {},
  "frontend": {
    "port": 8099
  },
  "experimental": {}
}
```

**Zigbee2mqtt add-on version (if edge, please report commit hash):**
```
1.18.2-1
```

**Your entire configuration from the frontend (with sensitive fields redacted)**:
```
See above
```

**Running platform (details from Suypervisor > System)**
```
Core: core-2021.4.6
Supervisor: supervisor-2021.04.0
Operating System: HassOS 5.13
```

**Your logs from Home Assistant Supervisor**
```
21-05-01 11:59:23 WARNING (MainThread) [supervisor.addons.options] Unknown option 'homeassistant' for Zigbee2mqtt (45df7312_zigbee2mqtt)
```

Let me know if you need more information.

Regards
Richard
